content/blog/2021-06-02-introducing-dvc-studio.md

Fixed comments URL

---

src/components/LayoutHeader/alert.tsx

Removed svg and added rocket

---

content/blog/2021-06-02-introducing-dvc-studio.md

Corrected comments URL for Studio launch blog post

---

content/docs/sidebar.json
content/docs/studio/create-view.md
content/docs/studio/get-started.md
content/docs/studio/view-settings.md

Added section on preparing your repositores, and other small changes

---

content/docs/user-guide/experiment-management/checkpoints.md

Moved project installation to `<details>`
Some typos fixed

Minor edits for the UG:Experiment-Management:Checkpoints

---

content/docs/command-reference/remote/modify.md

Per https://github.com/iterative/dvc/pull/6086#issuecomment-857287644

azure: remove note about bucket autocreation

---

content/docs/cml/cml-with-npm.md

CML: explicitly mark step

---

content/docs/cml/cml-with-dvc.md

Fixed a typo which took some time to figure out.

CML: fix missing redirect

---

content/docs/user-guide/project-structure/internal-files.md

user guide: update internal files

---

content/blog/2021-02-22-cml-runner-prerelease.md
content/blog/2021-03-03-dvc-2-0-release.md
content/docs/cml/start-github.md

CML: replace cml-action => setup-cml

---

content/docs/dvclive/usage.md
content/docs/user-guide/experiment-management/checkpoints.md

- Mini change per https://github.com/iterative/dvc.org/issues/2552#issuecomment-859895417
- Close https://github.com/iterative/dvc.org/issues/2564

dvclive: Keras typo and link from Checkpoints guide

---

content/blog/2021-06-18-june-21-dvc-heartbeat.md

Adjusting some of the picture dates that were wrong so they were broken in article.
Solves https://github.com/iterative/dvc.org/pull/2567#pullrequestreview-687762528

adjust missed pic dates

---

content/docs/command-reference/destroy.md

hotfix: fix md link in `destroy` ref.

---

.github/workflows/link-check-all.yml
.github/workflows/link-check-deploy.yml

After https://github.com/iterative/link-check/pull/6

Update link-check to 0.8 for ref link support

---

content/blog/2020-01-17-january-20-dvc-heartbeat.md
content/blog/2020-02-10-february-20-dvc-heartbeat.md
content/blog/2020-03-11-march-20-dvc-heartbeat.md
content/blog/2020-04-06-april-20-dvc-heartbeat.md
content/blog/2020-05-14-may-20-dvc-heartbeat.md
content/blog/2020-06-08-june-20-dvc-heartbeat.md
content/blog/2020-07-10-july-20-dvc-heartbeat.md
content/blog/2020-08-10-august-20-dvc-heartbeat.md
content/blog/2020-09-09-september-20-dvc-heartbeat.md
content/blog/2020-10-12-october-20-dvc-heartbeat.md
content/blog/2020-11-11-november-20-dvc-heartbeat.md
content/blog/2020-12-18-december-20-dvc-heartbeat.md
content/blog/2021-01-20-january-21-dvc-heartbeat.md
content/blog/2021-02-16-february-21-dvc-heartbeat.md
content/blog/2021-03-15-March-21-dvc-heartbeat.md
content/blog/2021-04-16-april-21-dvc-heartbeat.md
content/blog/2021-05-21-may-21-dvc-heartbeat.md

Can we config linters to pick up on this automatically?

fix metadata

---

content/docs/command-reference/get-url.md
content/docs/command-reference/import-url.md

https://github.com/iterative/dvc/issues/2865#issuecomment-872220646
Thank you for the contribution - we'll …

import-url: remove gdrive

---

content/community.json
content/docs/start/metrics-parameters-plots.md

This adds @flippedcoder 's Metric video to the end of the Get Started:  Metrics, Parameters, and Plots Doc.

Metrics update

---

config/prismjs/dvctable.js
content/docs/start/experiments.md
gatsby-config.js
src/components/Blog/Post/Markdown/styles.module.css
src/components/Documentation/Markdown/Main/styles.module.css

* add bold, italic, and colored(blue, yellow, or white) table cell options
* See styled tables at https://dvc-org-table-syntax-hi-b7phhe.herokuapp.com/doc/start/experiments
Fixes #2516

Update prismjs config for `dvc` table styling

---

content/docs/command-reference/remote/modify.md

for service account wuth with delegation
per https://github.com/iterative/dvc.org/pull/2612#discussion_r665389271
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the …

ref: clarify how to setup GDrive for

---

content/docs/command-reference/push.md

rf: download (typo) in push

---

content/docs/command-reference/exp/index.md
content/docs/start/experiments.md
content/docs/user-guide/basic-concepts/experiment.md
content/docs/user-guide/experiment-management/index.md
content/docs/user-guide/project-structure/pipelines-files.md

Update DVC 2.0 availability info

---

content/docs/command-reference/remote/modify.md

https://github.com/iterative/dvc/pull/6359 adds some additional parameters to the azure config. This PR is the documentation for those.

Update modify.md with params for #6359

---

content/docs/dvclive/api-reference/init.md
content/docs/dvclive/api-reference/log.md

Updated info about cleanup

---

content/docs/command-reference/stage/add.md

Copy edit `--live`

---

content/docs/user-guide/experiment-management/checkpoints.md

Adding Milecia's Checkpoints video to the doc.

Checkpoints vid add

---

content/docs/start/experiments.md

Adding Milecia's experiment video

add experiment video

---

content/docs/user-guide/project-structure/internal-files.md

fix file hash examples in internal-files.md #2678

---

content/docs/command-reference/index.md

because you probably didn't mean it is
Thank you for the contribution - we'll try to review it as soon as …

Fixed typo in it's

---

content/docs/command-reference/remote/modify.md

docs: fix push usage in remote modify docs

---

src/components/Blog/Feed/Item/styles.module.css

Fix Blog/Feed/Item component spacing

---

content/blog/2021-08-17-august-21-dvc-heartbeat.md

Oops we missed this one from https://github.com/iterative/dvc.org/pull/2723#discussion_r690756415

blog: remove accidental doc update

---

content/docs/command-reference/exp/show.md

exp: prexif => prefix

---

content/docs/dvclive/user-guide/ml-frameworks/huggingface.md

PR for the second task in iterative/dvclive#83

dvclive - HuggingFace integration

---

content/docs/dvclive/user-guide/ml-frameworks/index.md
content/docs/sidebar.json

DVCLive - Hugging Face: Added missing link

---

config/link-check/excluded-links.yml
gatsby-config.js
package.json
src/components/SubscribeSection/Form/index.tsx

- sync with https://github.com/iterative/cml.dev
- `sweedom.us10.list-manage.com` -> `dvc.us10.list-manage.com`
- fix repo url
- add author

misc meta update

---

content/docs/command-reference/import.md

Closes https://github.com/iterative/dvc.org/issues/2610

docs: document chained `dvc import` behavior

---

content/docs/user-guide/project-structure/pipelines-files.md

per https://github.com/iterative/dvc.org/pull/2705#issuecomment-905189675

guide: fix dvclive link

---

content/docs/command-reference/params/index.md

Added note about unsuported expressions in Python parameters file

---

content/docs/dvclive/user-guide/dvclive-with-dvc.md

See https://github.com/iterative/dvc.org/pull/2722

manual refresh of dvclive html no longer needed

---

content/docs/command-reference/exp/remove.md

Remaining issues from https://github.com/iterative/dvc.org/pull/2722

Remove all exps (2)

---

content/docs/command-reference/status.md

status cmd ref: indent to fix the options list

---

README.md

- related https://github.com/iterative/dvc/pull/6552
- related https://github.com/sourcerer-io/sourcerer-app/issues/632

replace sourcerer -> contrib.rocks

---

content/blog/2021-07-19-hyperparam-tuning.md

Adding Milecia's Hyperparameter Video to her blog post.  Do we want to add this to the queues section of docs as this is mentioned there as well?

blog: Hyperparams video

---

content/docs/command-reference/exp/show.md

Added -n/--num option

---

.github/workflows/download-link-check-deploy.yml
.github/workflows/download-link-check-schedule.yml

Fix broken dvc download link check

---

content/docs/use-cases/fast-data-caching-hub.md

per https://github.com/iterative/dvc.org/pull/2791#pullrequestreview-764848551 …

cases: include multi-machine scenario in Caching Hub

---

content/docs/api-reference/open.md

api: `open` now supports GDrive too

---

content/docs/dvclive/ml-frameworks/index.md
content/docs/dvclive/ml-frameworks/pytorch-lightning.md
content/docs/sidebar.json

Fix #2882 
Documentation about the new [feature](https://github.com/iterative/dvclive/pull/168)

doc: PyTorch Lightning integration

---

.github/workflows/update.yaml

This came up when merging `master` into some branch.

`yarn format-all`

---

.github/workflows/download-link-check-schedule.yml

* rename `automated issue` to `link-checker`

Update DVC Download Link Check issue labels

---

content/blog/2021-08-24-transfer-learning-experiments.md

Adding Milecia's video on the topic to the post.

blog: adding transfer learning video to bee and ants post

---

src/components/Documentation/Markdown/ToggleProvider/index.tsx
src/components/Documentation/Markdown/styles.module.css

* updates tabs, matching changes made to cml.dev (styling and url tab query). 
* converted to draft until tabs added inside docs index page for testing have been deleted

Update `md` tabs

---

content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/modify.md

Updates to WebHDFS remote documentation to reflect changes in:
https://github.com/iterative/dvc/pull/6936
Also see dvc issue:
https://github.com/iterative/dvc/issues/6935

Update WebHDFS docs pending https://github.com/iterative/dvc/pull/6936

---

src/components/Page/DefaultSEO/index.tsx
src/components/SEO/index.tsx
src/templates/blog-post.tsx

* add missing og tags
* fix broken blog post og:image height and width tags
* add og:article tags to blog posts
Fixes #1119

Update meta tags

---

content/docs/command-reference/gc.md

Closes https://github.com/iterative/dvc.org/issues/154

ref: copy edit `gc -c` section

---

content/docs/user-guide/project-structure/internal-files.md

Mention `dvc exp run` in `Run-cache`

---

content/docs/install/linux.md
content/docs/install/macos.md
content/docs/install/pre-release.md
content/docs/user-guide/contributing/core.md
content/docs/user-guide/contributing/docs.md

docs: python 3.6 -> 3.7

---

content/docs/command-reference/exp/apply.md
content/docs/user-guide/experiment-management/persisting-experiments.md

`exp apply`: simplify `--no-force` note, add it to guide

---

content/docs/command-reference/status.md

ref: close a parenthesis

---

content/docs/command-reference/root.md

replace "dvc run" references with "dvc stage add"

---

redirects-list.json

redirects: fix pipeline files redirect

---

content/blog/2021-12-07-ml-experiment-versioning.md

exp versioning blog post: fix image link

---

content/docs/command-reference/exp/index.md
content/docs/command-reference/exp/init.md

Small fixes to exp init cmd ref

Exp init fixes

---

src/components/Documentation/Markdown/ToggleProvider/index.tsx
src/components/Documentation/Markdown/index.tsx

* Since this is a copy of the pull request on cml.dev, I didn't add test tabs (it worked fine locally). But if we want to be sure, I'll add them.

Add nested md tabs

---

package.json

* Can be useful when you need to be rebuild your app from scratch :)

Add "gatsby clean" script to package.json

---

content/docs/command-reference/commit.md

ref: Update `dvc run` references in `dvc commit`

---

src/components/Home/LandingHero/index.tsx
src/components/Home/WhatsNewModal/index.tsx

* take off youtube video from hero, using old animation
* Update the "What's New" modal, populating it with the latest blog post
Fixes #3108

Update landing page

---

content/docs/command-reference/plots/diff.md
content/docs/command-reference/plots/index.md
content/docs/command-reference/plots/show.md

The description and example output were outdated

Update `dvc plots` output.

---

src/components/Community/Section/index.tsx
src/components/Community/Section/styles.module.css

* replaces clickable div with button inside `Community/Section`
Fixes #1290

Fix visibile outline in /community section headers

---

content/docs/user-guide/experiment-management/comparing-experiments.md

Per https://github.com/iterative/dvc.org/pull/3105#discussion_r771283960

guide: clarify that exp show --json is not a table

---

src/components/Home/UseCases/Video/index.tsx

Use `youtube-nocookie` domain in Video component

---

content/docs/command-reference/exp/init.md

exp init --model -> --models, fixes #3158

---

src/components/Home/WhatsNewModal/index.tsx

* Have the modal check if image exists before adding `GatsbyImage`. Otherwise a build will fail if a main blog image isn't provided

Add `WhatsNewModal` Image Check

---

redirects-list.json

Per https://github.com/iterative/dvc.org/pull/3162#issuecomment-1008958193
Plus another one that should be 302 I think.

redirects: make a couple 302

---

src/components/Documentation/Markdown/styles.module.css

Add margin-bottom to docs toggle component

---

content/docs/dvclive/api-reference/live/log.md

for consistency with DVC docs terminology

term: subfolder -> subdirectory (in DVCLive API ref.)

---

content/docs/dvclive/api-reference/live/index.md
content/docs/dvclive/api-reference/live/log.md
content/docs/dvclive/dvclive-with-dvc.md

dvclive copy edits

---

content/docs/start/experiments.md

For consistency
Maybe there was a reason to go with 2 words though?

term: dataset (one word)

---

content/docs/command-reference/exp/run.md

Very small typo fix
> Follow up to https://github.com/iterative/dvc.org/pull/3182

ref: exp show can list queued exps too

---

content/docs/use-cases/sharing-data-and-model-files.md

For #2076
Note that there are other mentions in https://dvc.org/doc/use-cases/versioning-data-and-model-files/tutorial but that's legacy so we can keep them, I think.

cases: `run` -> `add`

---

content/docs/user-guide/troubleshooting.md

For https://github.com/iterative/dvc/pull/7300

troubleshooting: add entry for pickle protocol errors

---

content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md
content/docs/dvclive/ml-frameworks/tensorflow.md

ref: update DVCLive links

---

src/components/HamburgerMenu/index.tsx
src/components/LayoutHeader/Nav/LinkItems/index.tsx
src/components/LayoutHeader/Nav/LinkItems/styles.module.css
src/components/LayoutHeader/Nav/Popup/index.tsx
src/components/LayoutHeader/Nav/Popup/styles.module.css
src/gatsby/hooks/usePopup.tsx

* refactors nav popup code
* adds `...` dropdown to nav bar (holds items that don't fit on the nav bar)
* add "Course" nav item
Fixes #2955

Add course link and "..." dropdown to nav bar

---

plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Main/styles.module.css
src/components/Blog/Post/Markdown/styles.module.css

Added margins to youtube embed block itself instead of wrapping it within a paragraph.
Fix #3290

Added margins to youtube embeds

---

content/blog/2022-2-17-february-22-heartbeat.md

Turns out there were a couple of bad links in HB.  Correcting with this.

correcting bad links

---

content/blog/2022-2-17-february-22-heartbeat.md

A couple more bad links and corrected some things that should have been there the first time.  Sorry.  🤦‍♀️ My attempt to speed up my process on the front end, failed on the backend.

fix links plus a couple other things

---

content/docs/dvclive/api-reference/live/log.md
content/docs/dvclive/api-reference/live/log_image.md
content/docs/dvclive/api-reference/live/log_plot.md

Follow up to #3207
Includes other misc. edits.

term: "metricS history" (file), et al. [DVCLive]

---

content/docs/command-reference/exp/branch.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/remote/index.md
content/docs/command-reference/status.md
content/docs/start/data-and-model-versioning.md
content/docs/studio/user-guide/prepare-repositories.md
content/docs/use-cases/ci-cd-for-machine-learning.md
content/docs/use-cases/data-registries.md
content/docs/use-cases/fast-data-caching-hub.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/user-guide/experiment-management/sharing-experiments.md
redirects-list.json

per https://github.com/iterative/dvc.org/pull/3275#issuecomment-1041896835
---

redirect: from removed UC to GS section

---

content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md
content/docs/dvclive/api-reference/live/index.md
content/docs/dvclive/api-reference/live/log.md
content/docs/dvclive/dvclive-with-dvc.md
content/docs/dvclive/get-started.md
content/docs/dvclive/ml-frameworks/catalyst.md
content/docs/dvclive/ml-frameworks/fastai.md
content/docs/dvclive/ml-frameworks/huggingface.md
content/docs/dvclive/ml-frameworks/keras.md
content/docs/dvclive/ml-frameworks/lightgbm.md
content/docs/dvclive/ml-frameworks/mmcv.md
content/docs/dvclive/ml-frameworks/pytorch-lightning.md
content/docs/dvclive/ml-frameworks/xgboost.md

P.R. for https://github.com/iterative/dvclive/pull/217

live: remove summary

---

content/docs/start/experiments.md

per https://github.com/iterative/dvc.org/pull/3197#issuecomment-1055724585

start: reorg params section in Exps page

---

content/docs/command-reference/exp/show.md

Related to https://github.com/iterative/dvc/pull/7204
> & https://github.com/iterative/dvc/pull/7245

`exp show`: add `--rev` option

---

content/docs/command-reference/config.md
content/docs/command-reference/status.md
content/docs/dvclive/dvclive-with-dvc.md
content/docs/dvclive/ml-frameworks/pytorch-lightning.md

per https://github.com/iterative/dvc.org/issues/2486#issuecomment-1067192170

hotfix: content/docs/... broken links

---

content/docs/command-reference/add.md
content/docs/command-reference/dag.md
content/docs/command-reference/import-url.md
content/docs/command-reference/move.md
content/docs/user-guide/experiment-management/index.md
content/docs/user-guide/project-structure/dvcignore-files.md
content/docs/user-guide/project-structure/internal-files.md
content/docs/user-guide/project-structure/pipelines-files.md

Typo corrections and some other small fixes

---

content/docs/install/linux.md
content/docs/install/macos.md
content/docs/user-guide/contributing/core.md

Closes https://github.com/iterative/dvc.org/issues/2449
Closes https://github.com/iterative/dvc.org/issues/2112
Closes https://github.com/iterative/dvc.org/issues/3134

install: missing `pip` optional paks

---

content/docs/user-guide/how-to/share-many-experiments.md

how: double `exp push` fix

---

content/docs/command-reference/exp/list.md

Related to https://github.com/iterative/dvc/pull/7245

`exp list`: add `--num` option, rename `--all` to `--all-commits`

---

content/docs/user-guide/how-to/update-tracked-data.md

per https://github.com/iterative/dvc.org/issues/3354#issuecomment-1081295479

how: link to `move` from Update Tracked Data

---

content/docs/command-reference/dag.md
content/docs/command-reference/exp/show.md

rel. https://github.com/iterative/dvc.org/pull/3310#pullrequestreview-890227517

pager: examples are Linux

---

src/components/LayoutHeader/alert.tsx

Rename Studio leftover

---

content/docs/command-reference/import.md

Minor fixes

---

content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md

Related to https://github.com/iterative/dvc/pull/7255
> & https://github.com/iterative/dvc/pull/7245

`exp push/pull`: add `--rev`, `-n`, `-A` flags

---

content/docs/command-reference/exp/remove.md

Related to https://github.com/iterative/dvc/pull/7275
> & https://github.com/iterative/dvc/pull/7245

`exp remove`: add `--rev` and `-n` options

---

content/docs/command-reference/plots/index.md

per https://github.com/iterative/dvc.org/pull/3426#pullrequestreview-938544110 …

ref: simplify `plots` rev+target example

---

content/docs/start/experiments.md

start: consistent title for Exps page

---

content/docs/sidebar.json
content/docs/studio/get-started.md
content/docs/studio/user-guide/account-management.md
content/docs/studio/user-guide/connect-custom-gitlab-server.md
content/docs/studio/user-guide/index.md
content/docs/studio/user-guide/teams.md
content/docs/studio/user-guide/views/create-view.md

**Main pages to review**
Changed:
- https://dvc-org-studio-accounts-vedlrg.herokuapp.com/doc/studio/get-started
- https://dvc-org-studio-accounts-vedlrg.herokuapp.com/doc/studio/user-guide/views/create-view
- https://dvc-org-studio-accounts-vedlrg.herokuapp.com/doc/studio/user-guide/teams
- https://dvc-org-studio-accounts-vedlrg.herokuapp.com/doc/studio/user-guide/account-management
New:
- https://dvc-org-studio-accounts-vedlrg.herokuapp.com/doc/studio/user-guide/connect-custom-gitlab-server

Added Studio docs for email sign up and custom Gitlab server support

---

content/docs/command-reference/exp/run.md
content/docs/command-reference/repro.md

From https://github.com/iterative/dvc/pull/7524/files#r839641294 (https://github.com/iterative/dvc/pull/7524)

ref: reorder repro options

---

src/components/LayoutFooter/styles.module.css
src/components/MainLayout/index.tsx
src/components/MainLayout/styles.module.css

* updates our `MainLayout` component and `Footer` components
Fixes #2430

Keep footer at bottom of page

---

content/blog/2022-04-27-terraform-provider.md

Correcting mis-spelling in the description.

cloud correction

---

content/blog/2022-04-26-CML-runners-saving-models-1.md

- partially reverts 5df4c30
- depends on https://github.com/iterative/cml/pull/992

blog: sanitise cml send-comment

---

content/docs/user-guide/setup-google-drive-remote.md

Followup based on https://github.com/iterative/dvc.org/pull/3473#issuecomment-1112659711
-----------------------------
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when …

Follow up to improve gdrive and move auth before service accounts

---

content/blog/2022-05-09-end-to-end-computer-vision-api-part-3-remote-exp-ci-cd.md

Fix line length in `descriptionLong`

Fix line length

---

content/blog/2022-05-03-end-to-end-computer-vision-api-part-1-data-versioning-and-ml-pipelines.md
content/blog/2022-05-05-end-to-end-computer-vision-api-part-2-local-experiments.md
content/blog/2022-05-09-end-to-end-computer-vision-api-part-3-remote-exp-ci-cd.md

Add links to and from different parts of the E2E series of posts

Blog: add links to and from different parts

---

content/blog/2020-07-07-cml-release.md
content/blog/2021-10-15-october-21-heartbeat.md

Closes https://github.com/iterative/cml/issues/1000 along with all the pull requests listed in https://github.com/iterative/cml/issues/1000#issuecomment-1124628318

Remove `cml publish` pipe from examples

---

.github/workflows/deploy-master.yaml

This pr is a draft since I can't add secrets to dvc.org.

Add action for `master` automatic deployment

---

content/docs/studio/get-started.md
content/docs/studio/user-guide/account-management.md
content/docs/studio/user-guide/connect-custom-gitlab-server.md
content/docs/studio/user-guide/teams.md
content/docs/studio/user-guide/views/create-view.md

Files changed (all inside `content/docs/studio/`) as per comments in #3419 :
- get-started.md
- user-guide/account-management.md
- user-guide/connect-custom-gitlab-server.md
- user-guide/teams.md
- user-guide/views/create-view.md

Addressed comments from Jorge in PR #3419

---

content/docs/studio/user-guide/teams.md
plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Main/styles.module.css

Give h4s a font-weight of 600

---

src/components/SubscribeSection/index.tsx
src/components/SubscribeSection/styles.module.css

Fixes #3570 
This PR adds a link to the blog RSS that we've always had but never linked to.
Right now it's next to the email subscription box, but I'm open to other suggestions.
small:
mid:
large:

Add RSS Link

---

content/docs/command-reference/dag.md

Per https://github.com/iterative/dvc/pull/7383

ref: dag: Add `--mermaid` and `--md` flags.

---

content/docs/command-reference/dag.md

Per https://github.com/iterative/dvc/pull/7803

ref: dag: Update mermaid with quotation marks.

---

content/docs/command-reference/plots/index.md

cmd-ref: plots fix syntax highlighter

---

content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md

ref: exp push/pull experiment metavar

---

content/blog/2022-05-31-aws-remotes-in-dvc.md

#3519 was merged with some typos in the images. This caused [master](https://github.com/iterative/dvc.org/actions/runs/2415417748) and pr deployment (#3560) to break. This pr corrects the typos, fixing deployment!

Fix broken deployment

---

src/components/LayoutHeader/alert.tsx

This PR changes the content of our alert component to inform users of the MLEM release.
It's a bit early, but this way we'll be able to collaborate on what content we want and have it ready to merge when we need it with no delay.
I just winged the content to have something there, I fully expect it to be changed.

Add MLEM alert box

---

content/docs/command-reference/params/index.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md

Follow-up to https://github.com/iterative/dvc.org/pull/3579

ref: ruamel.yaml admons

---

content/docs/api-reference/index.md
content/docs/command-reference/index.md
content/docs/index.md
content/docs/install/ide-plugins.md
content/docs/sidebar.json
content/docs/start/data-management/index.md
content/docs/start/index.md
content/docs/use-cases/experiment-tracking.md
content/docs/user-guide/experiment-management/experiments-overview.md
content/docs/user-guide/experiment-management/index.md
content/docs/user-guide/running-dvc-on-windows.md
content/docs/user-guide/what-is-dvc.md
redirects-list.json

vs-code: link from nav and key docs

---

content/docs/command-reference/cache/dir.md
content/docs/command-reference/metrics/diff.md
content/docs/command-reference/metrics/index.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/params/diff.md
content/docs/command-reference/params/index.md
content/docs/command-reference/plots/diff.md
content/docs/command-reference/plots/modify.md
content/docs/command-reference/plots/show.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/default.md
content/docs/command-reference/remote/index.md
content/docs/command-reference/remote/list.md
content/docs/command-reference/remote/modify.md
content/docs/command-reference/remote/remove.md
content/docs/command-reference/remote/rename.md
content/docs/command-reference/stage/add.md
content/docs/command-reference/stage/list.md

Replace fenced dvc block with new cli notation

---

content/docs/command-reference/params/index.md

Add missing supported bool type to params ref

ref: params support bool type

---

content/docs/api-reference/get_url.md
content/docs/api-reference/open.md
content/docs/api-reference/read.md

per https://github.com/iterative/dvc.org/pull/3459#pullrequestreview-1012748850

api: clarify `rev` param

---

content/docs/dvclive/ml-frameworks/xgboost.md

Fix xgb import

---

content/docs/command-reference/metrics/show.md

ref: update metrics show examples

---

content/docs/dvclive/ml-frameworks/catalyst.md
content/docs/dvclive/ml-frameworks/fastai.md
content/docs/dvclive/ml-frameworks/huggingface.md
content/docs/dvclive/ml-frameworks/keras.md
content/docs/dvclive/ml-frameworks/pytorch-lightning.md

Per https://github.com/iterative/dvclive/releases/tag/0.9.0
Closes https://github.com/iterative/dvclive/issues/263

live: Updates for log standardization.

---

content/docs/command-reference/list.md

Documentation for dvc list - adding missing word

---

content/docs/command-reference/plots/index.md
content/docs/start/experiments/index.md

~~Rel. https://github.com/iterative/dvc.org/issues/3718#issuecomment-1175589529~~ https://github.com/iterative/dvc.org/issues/3717

vs-code: more links

---

app.json

Upgrade Heroku stack. Part of ( #3765 )

Upgrade heroku stack

---

content/docs/command-reference/index.md
content/docs/command-reference/params/index.md
content/docs/command-reference/plots/index.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md
content/docs/start/data-management/index.md
content/docs/start/experiments/index.md
content/docs/start/index.md
content/docs/user-guide/experiment-management/index.md
content/docs/user-guide/running-dvc-on-windows.md

> tbh, I would remove them completely - they are noisy
_Originally posted by @shcheklein in https://github.com/iterative/dvc.org/issues/3717#issuecomment-1181202014_

admons: remove for VS Code, update `type`s

---

content/docs/dvclive/dvclive-with-dvc.md
content/docs/user-guide/experiment-management/checkpoints.md

Depends on https://github.com/iterative/dvc/pull/8000

Update checkpoints and DVCLive with DVC

---

package.json

Ported from https://github.com/iterative/cml.dev/pull/274#discussion_r925529078

add `yarn doc`

---

content/docs/index.md

Virtual Studio Code -> Visual Studio Code

---

content/docs/sidebar.json

> Typo noticed after https://github.com/iterative/dvc.org/pull/3794

hotfix: Virtual -> Visual (Studio Code)

---

src/components/Blog/Post/index.tsx

This will fix the `srcSet` issue for the blog.

Apply patch for srcSet issue for blog

---

content/blog/2022-07-26-iterative-studio-model-registry.md

Changed as per issue raised [here](https://iterativeai.slack.com/archives/C6YHPP2TB/p1658915684127089?thread_ts=1658849927.520119&cid=C6YHPP2TB).

Changed name of model shown in artifacts.yaml

---

content/docs/command-reference/metrics/index.md

https://github.com/iterative/dvc.org/pull/3361#discussion_r940683186

Add TOML version

---

content/docs/command-reference/push.md

Insert video DVC Cache. 
The format follows the getting started structure series . 
If there is another Markdown style format I should follow, let me know 
Thanks ! Have a nice day

Video DVC Cache

---

content/docs/api-reference/params_show.md

Per https://github.com/iterative/dvc/pull/8167

api: Add details for params_show stages syntax.

---

content/docs/command-reference/exp/run.md

P.R. for https://github.com/iterative/dvc/pull/8067

ref: Hydra support for `exp run --set-param`

---

content/docs/user-guide/experiment-management/comparing-experiments.md

Follow up to https://github.com/iterative/dvc.org/pull/3884#pullrequestreview-1084707615 …

guide: edits for `exp show` options

---

content/docs/user-guide/project-structure/dvcyaml-files.md

Fix extension supported files

---

package.json
yarn.lock

Upgrade gatsby-theme-iterative v0.1.14

---

content/docs/studio/get-started.md
content/docs/studio/user-guide/account-management.md
content/docs/studio/user-guide/billing-and-payment.md
content/docs/studio/user-guide/change-team-plan-and-size.md
content/docs/studio/user-guide/projects-and-experiments/create-a-project.md
content/docs/studio/user-guide/projects-and-experiments/share-a-project.md
content/docs/studio/user-guide/teams.md

Related to https://github.com/iterative/studio/issues/4141
Closes https://github.com/iterative/studio/issues/4203

Changed Team to Basic and added a new Teams plan in Studio pricing

---

content/docs/command-reference/import-url.md

Prevents horizontal scrolling in https://dvc.org/doc/command-reference/import-url#synopsis.

ref: reorg and wrap `import-url` usage block

---

renovate.json

I am hoping this way we get our packages grouped together which will make it easier to review and also it will be available sooner.

Renovate group iterative/dvcorg packages

---

content/docs/command-reference/plots/index.md
content/docs/user-guide/pipelines/index.md
content/docs/user-guide/visualizing-plots.md

start: fix links to Data Pipelines page

---

content/docs/start/index.md

per https://github.com/iterative/dvc.org/pull/3955#issuecomment-1248684568

start: clarify that trails are comprehensive

---

content/docs/command-reference/plots/index.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md
content/docs/user-guide/visualizing-plots.md

per https://github.com/iterative/dvc.org/pull/3940#issuecomment-1251843556

plots: clarify (more) that stage-level plots can be dirs

---

package.json
sentry.config.js
yarn.lock

I guess it will be faster if we get the Renovate PR for the bump once https://github.com/iterative/dvc.org/pull/3951 gets merged.

Bump gatsby-theme-iterative@v0.1.16

---

content/docs/api-reference/make_checkpoint.md

IANADS so any help on improving this code/docs would be great.

make_checkpoint: rewrite code for every100th iterations

---

content/docs/command-reference/data/status.md
content/docs/command-reference/status.md

ref: add git status refs to data status

---

content/docs/start/data-management/metrics-parameters-plots.md

start: update `git add`

---

content/docs/api-reference/dvcfilesystem.md
content/docs/command-reference/exp/index.md
content/docs/user-guide/experiment-management/checkpoints.md
content/docs/user-guide/experiment-management/index.md
content/docs/user-guide/project-structure/dvcyaml-files.md

Per https://github.com/iterative/dvc/issues/7093

doc: remove New in DVC 2.0 quotes

---

package.json
yarn.lock

Just speeding up what Renovate otherwise would do.

Bump theme to v0.1.17

---

content/docs/start/data-management/data-and-model-access.md
content/docs/start/data-management/data-pipelines.md
content/docs/start/data-management/data-versioning.md
content/docs/start/data-management/metrics-parameters-plots.md
content/docs/start/experiment-management/experiments.md
content/docs/start/experiment-management/visualization.md
content/docs/start/index.md

In review app: https://dvc-org-start-quick-to--pzygfe.herokuapp.com/doc/start

start: get faster to actionable commands

---

content/docs/command-reference/add.md

update add.md `--to-remote` description to remove repetitive mention of not caching the target

update add.md --to-remote description

---

content/docs/command-reference/exp/run.md
content/docs/user-guide/experiment-management/running-experiments.md

clarify exp untracked files

---

content/docs/sidebar.json

Per https://github.com/iterative/dvc.org/pull/3994#discussion_r1000150493

dvclive: update sidebar order

---

content/docs/command-reference/get.md

ref: add get --show-url option

---

content/docs/user-guide/how-to/setup-google-drive-remote.md

Added instructions for setting up delegation with google service accounts.
Closes https://github.com/iterative/dvc.org/issues/3963

Fix #3963. Update setup-google-drive-remote.md 

---

content/docs/user-guide/experiment-management/visualizing-plots.md

Trying to make the code samples easier to read and more informative (marginally perhaps).

guide: updates to Plots config samples

---

content/docs/user-guide/how-to/resolve-merge-conflicts.md

Clarifying based on feedback in https://discord.com/channels/485586884165107732/563406153334128681/1034722319379222568

guide: drop dvc.lock for merge conflicts

---

content/docs/user-guide/experiment-management/visualizing-plots.md

Follow up to https://github.com/iterative/dvc.org/pull/4054#discussion_r1006434440

guide: apply top-level plots list format to all examples

---

content/docs/studio/get-started.md
content/docs/studio/user-guide/prepare-your-repositories.md
content/docs/studio/user-guide/projects-and-experiments/run-experiments.md

Related to https://github.com/iterative/studio/pull/4188
Pending:
1. Setting up credentials/authorization for the CML create action
2. Any troubleshooting tips (things that could go wrong for many users, and how they should resolve them)

DON'T MERGE YET: Content for CML workflow in Studio

---

content/docs/studio/get-started.md
content/docs/studio/user-guide/model-registry/add-a-model.md
content/docs/studio/user-guide/prepare-your-repositories.md

Fix #4064
Related https://github.com/iterative/studio/issues/4104

docs(add-a-model): document LWMM with data (dvc)

---

content/docs/sidebar.json
content/docs/studio/get-started.md

... before How it Works (more of a mid-level explanation type doc)

Studio/nav: start with GS

---

content/docs/user-guide/project-structure/dvcyaml-files.md

term: metafile vs DVC file

---

content/docs/command-reference/plots/show.md
content/docs/user-guide/experiment-management/visualizing-plots.md
content/docs/user-guide/project-structure/dvcyaml-files.md

Depends on https://github.com/iterative/dvc/pull/8482

Support for str fields in top-level plots

---

content/docs/start/data-management/metrics-parameters-plots.md

Depends on https://github.com/iterative/example-repos-dev/pull/142

start: update metrics/plots for dvclive 1.0

---

content/docs/command-reference/plots/index.md
content/docs/command-reference/plots/show.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md
content/docs/studio/user-guide/projects-and-experiments/visualize-and-compare.md
content/docs/user-guide/experiment-management/visualizing-plots.md

Per https://github.com/iterative/dvc/pull/8542
Fixes #4109.

Document support for SVG plots

---

content/docs/studio/user-guide/projects-and-experiments/run-experiments.md

Small fixes to the links. Only 1 file changed.

Fixed 2 links in the run experiments page

---

content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md

Address https://github.com/iterative/dvc.org/pull/4090#discussion_r1023320555

Studio: Shortened the example for auto-hiding with [skip studio]

---

content/docs/install/completion.md
redirects-list.json

install/completion: add tabs, add tcsh

---

.github/workflows/check-deployment.yml

Add check deployment action that will run if:
- branch name starts with `renovate/`
- branch name contains `no-deploy`
#pass-ci

Add check deployment workflow action

---

content/docs/start/data-management/metrics-parameters-plots.md

Adds missing word in to metrics get started tutorial

---

content/docs/command-reference/exp/save.md
content/docs/sidebar.json
content/docs/start/experiment-management/experiments.md
content/docs/user-guide/experiment-management/experiments-overview.md
content/docs/user-guide/experiment-management/persisting-experiments.md
content/docs/user-guide/experiment-management/running-experiments.md

Initial documentation for `dvc exp save`
#4148

exp save docs

---

content/docs/command-reference/plots/index.md
content/docs/user-guide/project-structure/dvcyaml-files.md

Quick fix to add in some basic reference info for top-level metrics and params.
@skshetry Could you please review and take this one over so we can get it merged today 🙏 ?

Top level metrics and params

---

content/docs/user-guide/how-to/setup-google-drive-remote.md

added setting gdrive_acknowledge_abuse to true to address the issue #4184 …

added gdrive_acknowledge_abuse modifier

---

content/docs/user-guide/how-to/setup-google-drive-remote.md

guide: edits around `gdrive_acknowledge_abuse`

---

content/docs/command-reference/dag.md
content/docs/command-reference/repro.md
content/docs/command-reference/run.md
content/docs/start/data-management/data-pipelines.md
content/docs/start/data-management/metrics-parameters-plots.md
content/docs/user-guide/overview.md

> Follow-up to https://github.com/iterative/dvc.org/pull/3414

pipelines: wording updates

---

content/docs/start/data-management/data-pipelines.md

start: link to data step from Pipelines

---

content/docs/start/index.md

Small improvement per https://github.com/iterative/dvc.org/pull/4000#issuecomment-1361750787

start: reader instructions (2)

---

content/docs/command-reference/exp/apply.md
content/docs/command-reference/exp/branch.md
content/docs/command-reference/exp/diff.md
content/docs/command-reference/exp/gc.md
content/docs/command-reference/exp/list.md
content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/command-reference/exp/run.md
content/docs/command-reference/exp/save.md
content/docs/command-reference/exp/show.md

> Found in https://github.com/iterative/dvc.org/pull/4166#discussion_r1055098240

hotfix: fix some broken MD link refs.

---

content/docs/user-guide/troubleshooting.md

This has been supported for a while: https://github.com/iterative/scmrepo/pull/138

troubleshooting: remove outdated section

---

.github/workflows/update.yaml
content/docs/user-guide/data-management/cloud-versioning.md

As part of an effort to use our own tools more/where appropriate cml can create the PR for the download links.

Use cml to create download link PR

---

content/docs/start/data-management/data-pipelines.md

Fix tag in data-pipelines.md

---

content/docs/user-guide/experiment-management/sharing-experiments.md

guide: experiment tracking edits

---

content/docs/studio/get-started.md
content/docs/studio/user-guide/projects-and-experiments/create-a-project.md

fix(docs/studio): update gitlab self-hosted link

---

content/docs/command-reference/queue/kill.md

and a link fix
> Follow-up to https://github.com/iterative/dvc.org/pull/4183

ref: `queue kill --force` update &

---

content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md

Studio: add admon about live.end()

---

content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md

Address https://github.com/iterative/dvc.org/pull/4242#issuecomment-1385937862

Studio: mention live.end() in live metrics docs

---

content/docs/start/data-management/metrics-parameters-plots.md

See https://github.com/iterative/dvc.org/pull/4207#discussion_r1068268762. tldr: This updates better matches the text in https://dvc.org/doc/start/data-management/metrics-parameters-plots#visualizing-plots.
Related example-get-started repo updates in https://github.com/iterative/example-repos-dev/pull/160.

get-started: update plots ordering

---

content/docs/command-reference/config.md

ref: md link ref in `config`

---

content/docs/command-reference/exp/gc.md
content/docs/command-reference/exp/init.md
content/docs/command-reference/exp/list.md
content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/command-reference/exp/run.md
content/docs/command-reference/exp/save.md
content/docs/command-reference/queue/index.md
content/docs/command-reference/queue/kill.md
content/docs/command-reference/queue/logs.md
content/docs/command-reference/queue/remove.md
content/docs/command-reference/queue/status.md
content/docs/command-reference/queue/stop.md
content/docs/install/index.md
content/docs/start/experiment-management/experiments.md
content/docs/user-guide/experiment-management/checkpoints.md
content/docs/user-guide/experiment-management/sharing-experiments.md
content/docs/user-guide/experiment-management/visualizing-plots.md

per https://github.com/iterative/dvc.org/pull/4271#pullrequestreview-1272139385

fix: link to Experiments (index page)

---

redirects-list.json

Per https://github.com/iterative/dvc.org/pull/4272#pullrequestreview-1272162127

guide: redirect from (dead) exp/overview page (to index)

---

content/docs/studio/how-it-works.md
content/docs/studio/troubleshooting.md
content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md
content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md

Closes https://github.com/iterative/dvc.org/issues/4279

Studio: Parent commit must be in Git for live metrics

---

content/docs/command-reference/import-url.md
content/docs/command-reference/push.md

@jorgeorpinel WDYT about these in the ref vs the guide?

ref: add cloud versioning examples

---

content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md

Explain `save_dvc_exp=True` as described [here](https://github.com/iterative/dvc.org/pull/4278#issuecomment-1422925443).

Studio: Explain save_dvc_exp=True

---

content/docs/api-reference/metrics_show.md
content/docs/sidebar.json

api: add docs for api.metrics_show command

---

content/docs/studio/how-it-works.md
content/docs/studio/index.md
content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md
content/docs/studio/user-guide/projects-and-experiments/run-experiments.md

Changes to Studio docs on top of https://github.com/iterative/dvc.org/pull/4285

Changes to Studio docs on top of #4285

---

content/docs/command-reference/status.md

ref: fix data status link

---

content/docs/dvclive/get-started.md

Fix the link of "track the results"

---

content/docs/studio/user-guide/projects-and-experiments/configure-a-project.md

Minor change (changed `This means ..` to `This meant ..`).

Studio: Minor change

---

content/docs/user-guide/experiment-management/sharing-experiments.md
content/docs/user-guide/troubleshooting.md

guide: git auth troubleshooting

---

package.json
yarn.lock

Bump there to update the top banner.

bump theme to 0.3.3

---

content/docs/command-reference/pull.md

Per https://github.com/iterative/dvc/pull/9071

pull: Add `allow-missing` flag.

---

content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md

Minor fix to address https://github.com/iterative/dvc.org/pull/4285#discussion_r1125636474

Studio: Minor fix

---

content/docs/command-reference/exp/show.md

ref: document `dvc exp show --force`

---

content/docs/command-reference/exp/clean.md
content/docs/command-reference/exp/index.md
content/docs/sidebar.json

ref: document `dvc exp clean`

---

content/docs/sidebar.json
content/docs/studio/user-guide/model-registry/download-models.md
content/docs/studio/user-guide/model-registry/what-is-a-model-registry.md

Add basic instructions to download model file, according to [this conversation](https://github.com/iterative/studio/issues/5215#issuecomment-1458608249).

Studio: Basic instructions to dvc get model file

---

content/docs/command-reference/exp/clean.md
content/docs/command-reference/exp/index.md

fix(exp): cleanup and update help messages

---

content/docs/dvclive/api-reference/index.md
content/docs/dvclive/api-reference/live/index.md
content/docs/dvclive/api-reference/live/log_artifact.md
content/docs/dvclive/how-it-works.md
content/docs/sidebar.json

Per https://github.com/iterative/dvclive/pull/464

live: Add log_artifact

---

src/components/DownloadButton/index.tsx

Reverts iterative/dvc.org#4402

Revert "dvc 2.50.0"

---

content/docs/studio/self-hosting/installation/aws-ami.md
content/docs/studio/self-hosting/installation/k8s-helm.md
content/docs/studio/self-hosting/troubleshooting/502.md

With the latest version of Studio Self-hosted, it's required to add an `nginx` configuration block where you set the hostname

Fix config in Studio Self-hosted docs

---

content/docs/dvclive/how-it-works.md

Addresses #468 and better explains how to use DVCLive with DVC.
Fixes #4386

dvclive: add transition to pipelines

---

package.json
yarn.lock

Fixes https://github.com/iterative/dvc.org/issues/4432. I assume this would get auto-bumped soon, but let's merge it ASAP since it breaks our linking.

update gatsby-theme-iterative to 0.3.4

---

content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/user-guide/troubleshooting.md

Minor corrections to exp push/pull behavior

corrections to exp push/pull

---

content/docs/studio/get-started.md

Part of https://github.com/iterative/studio/issues/5426 and a followup for https://github.com/iterative/dvc.org/pull/4418#discussion_r1143877764

Be more precise in how we select the metrics to be displayed

---

content/docs/user-guide/data-management/remote-storage/ssh.md

user-guide: add SSH jobs troubleshooting note

---

content/docs/dvclive/how-it-works.md

Docs PR to accompany https://github.com/iterative/dvclive/pull/540

dvclive: dvclive doesn't print pipeline

---

content/docs/dvclive/live/log_sklearn_plot.md

Per https://github.com/iterative/dvclive/pull/538
------------ …

feat(docs): add normalized option to CM docs

---

content/docs/command-reference/add.md
content/docs/command-reference/get-url.md
content/docs/command-reference/get.md
content/docs/command-reference/import-url.md

Docs: Commands update: add/get/get-url/import-url - adding force flag

---

content/docs/command-reference/gc.md

Per https://github.com/iterative/dvc/pull/9350

gc: Add `--not-in-remote`.

---

content/docs/command-reference/data/status.md

Docs PR for https://github.com/iterative/dvc/pull/9411.

data status: update remote flags

---

content/docs/start/data-management/data-pipelines.md
content/docs/start/data-management/data-versioning.md

Get Started - data management, minor followups, aesthetics

---

content/docs/dvclive/how-it-works.md
content/docs/dvclive/live/log_artifact.md

Per https://github.com/iterative/dvclive/pull/559

feat(doc, dvclive): add copy parameter description to log_artifact

---

README.md

fix(readme): remove blog mention

---

content/docs/dvclive/how-it-works.md

fix(style): dvclive how it works linted

---

content/docs/api-reference/exp_show.md
content/docs/api-reference/metrics_show.md
content/docs/api-reference/params_show.md
content/docs/api-reference/scm.md
content/docs/sidebar.json

Per https://github.com/iterative/dvc/pull/9356

api-reference: Add `exp_show` and `scm`.

---

content/docs/use-cases/experiment-tracking.md

Closes #4087. Still need to add a good Studio gif once we have other functionality like the PRs working well enough.

Exp tracking use case updates

---

package.json
renovate.json
yarn.lock

- bump theme package
- reuse renovate config
- Closes #4535
<details>
<summary>Demo Video</summary>
https://github.com/iterative/dvc.org/assets/20840228/5909903d-b07a-4f82-8d09-f5aa417a9e86
</details>

Bump theme and reuse renovate config

---

content/docs/user-guide/experiment-management/hydra-composition.md
content/docs/user-guide/pipelines/running-pipelines.md

Docs for https://github.com/iterative/dvc/pull/9460

guide: how to debug interpolated values

---

content/docs/command-reference/stage/add.md

See https://github.com/iterative/dvc/pull/9487

document `--run` for `dvc stage add`

---

content/docs/use-cases/model-registry.md
content/docs/user-guide/project-structure/dvcyaml-files.md

Update MR use case

---

content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md
content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md
content/docs/user-guide/experiment-management/sharing-experiments.md
content/docs/user-guide/project-structure/configuration.md

Docs PR for https://github.com/iterative/dvc/pull/9433 and https://github.com/iterative/dvclive/pull/561

guide: live metrics config

---

content/docs/studio/get-started.md
content/docs/studio/user-guide/projects-and-experiments/configure-a-project.md
content/docs/studio/user-guide/projects-and-experiments/create-a-project.md

Per https://github.com/iterative/studio/pull/5945/files

feat(studio, docs): specify multiple values in monorepo setup

---

content/docs/command-reference/exp/run.md

ref: grid search range example

---

content/docs/start/experiments/experiment-collaboration.md

Fix the empty tab.
https://github.com/iterative/dvc.org/assets/20840228/ee23cdd9-043d-44f9-a332-d6a67c757b0e

Fix empty tab

---

content/docs/studio/troubleshooting.md
content/docs/studio/user-guide/account-management.md
content/docs/studio/user-guide/billing-and-payment.md
content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md
content/docs/studio/user-guide/projects-and-experiments/share-a-project.md
content/docs/studio/user-guide/projects-and-experiments/visualize-and-compare.md
content/docs/studio/user-guide/team-collaboration/teams.md

Closes https://github.com/iterative/dvc.org/issues/4092

Remove admons about renaming of views to projects

---

content/docs/studio/troubleshooting.md

Closes https://github.com/iterative/studio/issues/2275

Add more errors to troubleshooting guide

---

content/docs/command-reference/plots/show.md

Fix for https://github.com/iterative/dvc/issues/9637

ref: clarify plots targets

---

content/docs/api-reference/dvcfilesystem.md
content/docs/api-reference/exp_show.md
content/docs/api-reference/metrics_show.md
content/docs/api-reference/open.md
content/docs/api-reference/params_show.md
content/docs/api-reference/read.md

docs: api-reference: add config to open/read/dvcfs

---

content/docs/studio/index.md
content/docs/user-guide/experiment-management/index.md

Fixes #4646 (video is no private/no longer available)

update studio video

---

package.json
yarn.lock

- Propagating https://github.com/iterative/gatsby-theme-iterative/pull/222
- Related https://github.com/iterative/iterative.ai/pull/858

Bump theme to fix code selection

---

content/docs/dvclive/ml-frameworks/catalyst.md
content/docs/dvclive/ml-frameworks/fastai.md
content/docs/dvclive/ml-frameworks/huggingface.md
content/docs/dvclive/ml-frameworks/keras.md
content/docs/dvclive/ml-frameworks/lightgbm.md
content/docs/dvclive/ml-frameworks/mmcv.md
content/docs/dvclive/ml-frameworks/pytorch-lightning.md
content/docs/dvclive/ml-frameworks/tensorflow.md
content/docs/dvclive/ml-frameworks/xgboost.md
content/docs/start/experiments/experiment-tracking.md

Fixes #4666 
Also drops `model_file` examples

dvclive: use save_dvc_exp everywhere

---

content/docs/dvclive/how-it-works.md
content/docs/dvclive/live/index.md
content/docs/dvclive/live/log_image.md

Docs for https://github.com/iterative/dvclive/pull/605
Closes #4659

dvclive: cache_images

---

content/docs/user-guide/experiment-management/running-experiments.md

cloud experiments gif

---

content/docs/command-reference/exp/run.md

Closes https://github.com/iterative/dvc.org/issues/4695

Remove outdated `--reset`

---

content/docs/command-reference/remote/default.md
content/docs/user-guide/data-management/large-dataset-optimization.md
content/docs/user-guide/index.md

- part of https://github.com/iterative/dvc.org/issues/4376

Fix: update broken links

---

content/docs/user-guide/experiment-management/sharing-experiments.md

- Follow up to https://github.com/iterative/dvc.org/pull/4689
- part of https://github.com/iterative/dvc.org/issues/4376

Follow up: fix broken link

---

content/docs/command-reference/exp/run.md
content/docs/command-reference/repro.md

exp run: add options from repro

---

src/components/DownloadButton/styles.module.css
src/components/Home/LandingHero/Slides/index.tsx
src/components/Home/WhatsNewModal/styles.module.css

Spotted a couple small bugs while working on #4707 (highlighted in comments)
* ~Fix "What's New" button animation~ https://github.com/iterative/dvc.org/pull/4708#discussion_r1268374693
* Fix scrollbar possibly showing on terminal demo
* Fix Download button dropdown being obscured by company logos

Fix home page CSS bugs

---

src/components/Home/LandingHero/index.tsx
src/components/Home/LandingHero/styles.module.css
src/components/TwoRowsButton/link.tsx
src/components/TwoRowsButton/styles.module.css
static/img/vscode-alt-icon.svg

~https://github.com/iterative/dvc.org/assets/43496356/c9dd0d5a-5291-484c-a2b1-4da81afab339~
Replaces #4702

Add VSCode Button to Header

---

content/docs/studio/index.md
content/docs/user-guide/experiment-management/index.md

Closes https://github.com/iterative/studio/issues/6831

Update links to Studio overview video

---

content/docs/command-reference/fetch.md

docs: fetch: add --max-size and --types

---

content/docs/command-reference/fetch.md

Leftover from https://github.com/iterative/dvc.org/pull/4716

docs: fetch: fix formatting

---

content/docs/studio/get-started.md

Minor update to complete 2nd task in https://github.com/iterative/studio/issues/5426

Indicate that all metrics/params don't have to be defined in dvc.yaml

---

content/docs/dvclive/how-it-works.md

Follow up per https://github.com/iterative/dvc.org/pull/4750#pullrequestreview-1573979908

dvclive: use step-based images in how-it-works

---

content/docs/dvclive/live/log_plot.md

dvclive: remove self from log_plot

---

content/docs/dvclive/ml-frameworks/huggingface.md

per https://github.com/iterative/dvclive/pull/649
Closes https://github.com/iterative/dvc.org/issues/4770

dvclive: Add huggingface updates

---

content/docs/command-reference/list-url.md
content/docs/command-reference/list.md

docs: ls/ls-url: add --size

---

content/docs/start/data-management/metrics-parameters-plots.md

Depends on https://github.com/iterative/example-repos-dev/pull/238.
Related to #4769. It doesn't fix all issues but might be enough to lower the priority. It introduces metrics and plots via dvclive instead of having to manually configure them, and leaves additional customization as an extra step in a details section.

start: use dvclive config for initial plots

---

content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md
content/docs/user-guide/integrations/sagemaker.md

- Update outdated screenshots in the [explore-ml-experiments page](https://dvc.org/doc/studio/user-guide/projects-and-experiments/explore-ml-experiments).
- Update some of the text in this page to better fit the updated screenshots.
Completes https://github.com/iterative/dvc.org/issues/4679 and https://github.com/iterative/studio/issues/4770
Required png and gif files have been updated in the static repo in [this commit](https://github.com/iterative/static/commit/5e9f4eee257b550e2021f7907c5405e1e9fed348).

Studio update images

---

src/components/Home/Hero/HeroTitleSection.tsx
src/components/Home/Hero/styles.module.css

https://github.com/iterative/dvc.org/pull/4737#discussion_r1305950865
https://github.com/iterative/dvc.org/pull/4737#discussion_r1305961716
@yathomasi The `<em>` tag doesn't seem to apply an italic font style here. Is there an override somewhere?

chore: update hero title section text

---

src/components/Home/Hero/HeroSection.tsx

https://github.com/iterative/dvc.org/pull/4737#discussion_r1296245717
https://github.com/iterative/dvc.org/pull/4737#discussion_r1305947560

chore: update subtitles of the hero section

---

src/components/Home/Hero/BetterTogether/index.tsx

https://github.com/iterative/dvc.org/pull/4737#discussion_r1305961080

chore: update color scheme of better together section

---

src/@dvcorg/gatsby-theme-iterative/components/HamburgerMenu/index.tsx
src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/Nav/LinkItems/styles.module.css
src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/Nav/index.tsx
src/utils/externalUrls.ts

- Link to enterprise site from dvc.org

chore: link to enterprise site from dvc.org

---

content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md

As per https://iterativeai.slack.com/archives/C01SR9Q12LB/p1691741488374799?thread_ts=1691718179.138419&cid=C01SR9Q12LB

Add tip about commit message

---

content/docs/studio/get-started.md
content/docs/studio/troubleshooting.md
content/docs/studio/user-guide/model-registry/remove-a-model-or-its-details.md
content/docs/studio/user-guide/projects-and-experiments/create-a-project.md

Closes https://github.com/iterative/studio/issues/3909

Studio: Minor change - Remove unnecessary use of 'dashboard'

---

content/docs/command-reference/get.md
content/docs/command-reference/params/index.md
content/docs/command-reference/plots/show.md
content/docs/studio/user-guide/model-registry/remove-a-model-or-its-details.md
content/docs/user-guide/how-to/resolve-merge-conflicts.md

Apply linter to #4819 to merge it

---

content/docs/user-guide/project-structure/dvcyaml-files.md

Related to [this](https://iterativeai.slack.com/archives/CB41NAL8H/p1692882747850079) Slack discussion.

more descriptive artifacts in dvc.yaml

---

content/docs/sidebar.json
content/docs/user-guide/integrations/databricks.md

docs: start databricks page

---

content/docs/command-reference/import.md

Per https://github.com/iterative/dvc/pull/9927

import: Add `--force` flag.

---

content/docs/user-guide/integrations/databricks.md

docs: integrations: add note about dbx web terminal

---

src/components/Home/Hero/HeroSection.tsx

"Data factory" → "GenAI data chain"

Update DVCX hero with new messaging

---

content/docs/command-reference/gc.md

Docs for https://github.com/iterative/dvc/pull/9952

ref: gc --dry

---

content/docs/command-reference/cache/migrate.md
content/docs/user-guide/upgrade.md

cmd-ref: document dvc cache migrate --dvc-files

---

content/docs/user-guide/data-management/remote-storage/azure-blob-storage.md

docs: azure: add timeouts

---

content/docs/command-reference/get-url.md
content/docs/command-reference/import-url.md
content/docs/command-reference/list-url.md

Fixes #4824
Also adjusted metavars on dvc side https://github.com/iterative/dvc/pull/10047

docs: get-url/ls-url/import-url: document --fs-config

---

content/docs/command-reference/artifacts/get.md
content/docs/user-guide/data-management/discovering-and-accessing-data.md

Adds sections to the existing guide on discovering and accessing data to mention artifacts and the model registry.

guide: explain artifacts and model registry

---

content/docs/dvclive/live/index.md
content/docs/dvclive/live/log_artifact.md
content/docs/dvclive/live/make_dvcyaml.md

Docs for https://github.com/iterative/dvclive/pull/729

dvclive: update dvcyaml arg

---

content/docs/dvclive/live/index.md

Docs for https://github.com/iterative/dvclive/pull/725

dvclive: add exp_name

---

package.json
yarn.lock

Bumps our theme, updating banner for VSCode Extension Product Hunt
**Note:** To be merged by @tapadipti on product hunt launch

Update nav banner text

---

content/docs/start/model-management/model-registry.md

info about non-model artifacts

---

content/docs/command-reference/studio/index.md
content/docs/command-reference/studio/login.md
content/docs/command-reference/studio/logout.md
content/docs/command-reference/studio/token.md
content/docs/sidebar.json
content/docs/studio/user-guide/account-and-billing/index.md

Add guides for dvc studio login feature introduced in  dvc: https://github.com/iterative/dvc/pull/10074 …

studio: Add DVC Studio commands to documentation

---

content/docs/user-guide/how-to/run-dvc-on-windows.md

Noticed that we don't have this in the doc.

docs: user-guide: add section about CRLF issues on Windows

---

content/docs/start/model-management/model-cicd.md

Adding GitLab template examples to the Get Started guide on the model registry.

Get Started: Model management- GitLab template

---

content/docs/dvclive/ml-frameworks/fabric.md
content/docs/sidebar.json

Docs for https://github.com/iterative/dvclive/pull/749

dvclive: add fabric integration

---

content/docs/user-guide/experiment-management/comparing-experiments.md

Minor suggestion to improve readability of Comparing Experiments doc.

Suggested readability change for dvc garbage collection

---

content/docs/command-reference/status.md

ref: status --no-updates

---

content/docs/studio/user-guide/experiments/visualize-and-compare.md

Small update as per https://github.com/iterative/studio/pull/8894

Mention that up to 7 exps can be compared in Studio

---

content/docs/user-guide/how-to/run-dvc-on-windows.md

docs: mixed-line-endings -> mixed-line-ending

---

content/docs/studio/user-guide/experiments/explore-ml-experiments.md

- Needs https://github.com/iterative/static/pull/21 to be merged
Preview:
https://github.com/iterative/dvc.org/assets/20840228/eb736c9f-3c28-46dc-aa85-12ce1e799f53

add docs for ability to toggle the filters

---

content/docs/sidebar.json
content/docs/studio/rest-api/create-project.md
content/docs/studio/rest-api/download-model.md
content/docs/studio/rest-api/index.md

Addresses https://github.com/iterative/dvc.org/pull/5120/files#r1488521265

Split rest-api api doc into sub-pages

---

content/docs/dvclive/install.md
content/docs/sidebar.json

related to this discussion: https://iterativeai.slack.com/archives/CB41NAL8H/p1707823158357019

add an `install` section for DVClive

---

src/components/Home/Alert/index.tsx

This pull request updates the banner under the navigation on DVC.org for the upcoming February 28th Meetup.

change banner for feb 28

---

content/docs/start/data-management/data-pipelines.md

It looks like we miss a step to `dvc add` the raw data in our get-started

include dvc add in pipeline setup

---

src/components/Support/RequestAQuoteForm.tsx

- fixed the stuck in submitting
- added * to required fields so make it visible

fix: submit loading issue and add required fields sign

---

content/docs/studio/user-guide/account-and-billing/index.md

The `ADMIN` scope currently enables the creation of projects and the execution of SCIM operations.

Add description of ADMIN scope

---

content/docs/user-guide/env.md
content/docs/user-guide/experiment-management/sharing-experiments.md
content/docs/user-guide/project-structure/configuration.md

Waiting for https://github.com/iterative/dvc/pull/10323
Thank you for the contribution - we'll try to review …

add documentation for auto-push experiments in DVC

---

config/link-check/excluded-links.yml
content/docs/start/index.md
content/docs/start/model-registry/manage-models.md
content/docs/studio/user-guide/account-management/index.md
content/docs/user-guide/integrations/sagemaker.md

Addresses partially https://github.com/iterative/dvc.org/issues/4925

chore(links): fix some broken links

---

src/components/Home/Alert/index.tsx

This changes the banner for the next meetup next week.

Changing banner for next meetup

---

content/docs/api-reference/get_url.md
content/docs/api-reference/open.md
content/docs/api-reference/read.md

Docs PR for https://github.com/iterative/dvc/pull/10349

api: add remote config args and reorg

---

src/@dvcorg/gatsby-theme-iterative/components/LayoutFooter/index.tsx

As stated - Updating the link that I changed last night on LinkedIn.

adjust LinkedIn to new url

---

content/docs/studio/user-guide/openid-connect.md

@0x2b3bfa0 I made some changes to provide a little more context. PTAL.

add more oidc instructions

---

content/docs/studio/user-guide/openid-connect.md

Continuation of #5197, small cosmetic change

Fix naming on openid-connect.md examples

---

content/docs/command-reference/add.md

close parentheses

---

content/docs/user-guide/project-structure/dvcyaml-files.md

Docs for https://github.com/iterative/dvc/pull/10359
Reorganized `dvc.yaml` guide to have h2 headings for each top-level `dvc.yaml` section, as well as one for templating and one for `dvc.lock`. All other headings (like `foreach` and `matrix` stages) have been moved to h3 or lower.
Here is the table of contents before and after:
Before
After

guide: top-level templating (not just stages)

---

src/components/DownloadButton/index.tsx
src/utils/front/useUserOS.ts

- As per: https://github.com/iterative/dvc.org/pull/5214#issuecomment-2045741418

chore: drop macOS from download option

---

content/docs/user-guide/data-management/remote-storage/amazon-s3.md

Document the anonymous access option for s3.
related:
- https://github.com/iterative/dvc-s3/pull/85

remote-storage: s3: add 'allow_anonymous_login' option

---

content/docs/studio/self-hosting/configuration/index.md
content/docs/studio/self-hosting/configuration/ssl.md

Adding info about setting up self-hosted Studio for HTTPS

configuring ssl

---

content/docs/command-reference/add.md
content/docs/command-reference/commit.md

PR for https://github.com/iterative/dvc/pull/10389

ref: --no-relink

---

content/docs/command-reference/plots/templates.md

See https://github.com/iterative/vscode-dvc/issues/5503 for background

clarify how to use custom templates

---

content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/command-reference/fetch.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md

See https://github.com/iterative/dvc/pull/10433

update run-cache docs

---

content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/command-reference/fetch.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md

Try to revert iterative/dvc.org#5242

Revert "update run-cache docs"

---

src/gatsby/models/github/index.js

Quick fix to try to stabilize it first.

try quick fix: disable GH stars for now

---

content/docs/command-reference/exp/run.md
content/docs/command-reference/repro.md
content/docs/user-guide/pipelines/running-pipelines.md

See https://github.com/iterative/dvc/pull/10435#discussion_r1610281275

clarify repro --pull behavior

---

content/docs/command-reference/artifacts/get.md

Docs for https://github.com/iterative/dvc/pull/10423

ref: artifacts get --show-url

---

content/docs/use-cases/versioning-data-and-models/tutorial.md

Followup to: https://github.com/iterative/example-versioning/pull/13/files

Updated documentation to match current example.

---

content/docs/dvclive/ml-frameworks/pytorch-lightning.md

fix mr ref

---

gatsby-config.js
package.json
yarn.lock

feat: gtm setup

---

content/docs/start/index.md

start: fix example remote path

---

content/docs/studio/self-hosting/upgrading/airgap-procedure.md

Rename `dvcx` to `datachain` on airgap-procedure.md

---

src/components/Home/Alert/index.tsx
src/components/Home/index.tsx

Updating banner for release event.

Updating banner for release event

---

content/data/datachain.yml
src/components/Home/Hero/BetterTogether/index.tsx
src/components/Home/Hero/HeroSection.tsx

Reverts iterative/dvc.org#5281

Revert "Replace occurrences of 'DataChain' with 'DVCx' in the website"

---

content/docs/dvclive/live/log_plot.md

Docs for https://github.com/iterative/dvclive/pull/837

support lists for log_plot y val

---

gatsby-browser.js
gatsby-shared.tsx
gatsby-ssr.js
tsconfig.json

feat: reo setup

---

content/docs/user-guide/data-management/remote-storage/google-drive.md

Fix three typos in google-drive.md

---

src/components/Home/WhatsNewModal/styles.module.css

https://iterativeai.slack.com/archives/C01RHKGKCBT/p1729421365711889

Remove "What's new" button ripple

---

content/docs/command-reference/install.md

This PR documents the changes in https://github.com/iterative/dvc/pull/10621.

Update `pre-commit` `yaml` code-block

---

content/data/datachain.yml
src/components/Home/Hero/HeroSection.tsx
src/components/Home/Hero/HeroTitleSection.tsx

First steps. As part of the effort of improving DVC + DataChain messaging and the website funnel.

Simplify / make explicit main page messaging

---

content/docs/user-guide/data-management/cloud-versioning.md

As the title says, fixing a minor typo in the docs.

Fixed small typo in cloud-versioning.md

---

content/docs/command-reference/list-url.md

Merge when released. See https://github.com/iterative/dvc/pull/10664.

docs: cmd-reference: add `--tree`/`--level`

---

gatsby-shared.tsx

feat: add apollo integration

---

src/@dvcorg/gatsby-theme-iterative/components/HamburgerMenu/index.tsx
src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/Nav/index.tsx
src/components/Support/RequestAQuoteForm.tsx
src/components/Support/utils.tsx
src/utils/externalUrls.ts

- Drop hubspot form
- Related: https://github.com/iterative/datachain.ai/pull/261

feat: replace hubspot with studio contacts

---

src/components/Support/RequestAQuoteForm.tsx
src/components/Support/utils.tsx
src/utils/externalUrls.ts

- Related PR : https://github.com/iterative/datachain.ai/pull/263

refactor: remove CSRF token handling from RequestAQuoteForm and utils

---

redirects-list.json

Closes https://github.com/iterative/itops/issues/5741

Migrate S3 redirects to R2

---

src/@dvcorg/gatsby-theme-iterative/components/LayoutFooter/index.tsx

remove LI link from the footer

---

redirects-list.json

remove some redirects

---

package.json

allow node22

---

content/docs/use-cases/ci-cd-for-machine-learning.md

docs: align equation

---

content/docs/use-cases/ci-cd-for-machine-learning.md

fix font-size

---

package.json
packages/websites-server/package.json
yarn.lock

Reverts iterative/dvc.org#5396

Revert "fix(deps): update dependency @octokit/request to v10"

---

content/docs/user-guide/data-management/remote-storage/google-cloud-storage.md

- https://github.com/iterative/dvc-gs/pull/115
- https://github.com/iterative/dvc/pull/10756
- https://github.com/iterative/dvc/pull/10757
- https://github.com/iterative/dvc/issues/5797

docs: document allow_anonymous_login support for gs

---

content/blogs/2023-06-14-dvc-3.0-ml-experiments-data-versioning.md
content/docs/api-reference/dvcfilesystem.md
content/docs/user-guide/integrations/huggingface.md

See https://github.com/iterative/dvc/pull/10754.

docs: dvcfs: rename parameter

---

content/docs/studio/self-hosting/installation/index.md

remove sales team link from docs

---

content/docs/command-reference/exp/pull.md

Fixed a small typo involving a word repeated twice

Fix typo in pull.md

---

src/components/SubscribeSection/Form/index.tsx

Reverts iterative/dvc.org#5436

Revert "send error to sentry if no hubspot form is created or script is loaded"

---

content/docs/command-reference/exp/show.md

Documents new feature in iterative/dvc#10741

docs: document new --hide-workspace flag

---

content/docs/command-reference/exp/show.md

Noticed while wrapping up a SO anwser.

fix `dvc exp show` docs

---

content/docs/studio/user-guide/account-management/index.md

This updates the latest changes in client access tokens
Thank you for the contribution - we'll try to review …

Update the docs for scopes

---

.yarnrc.yml

disable scripts
