iterative/dvc.org

static/docs/get-started/configuration.md

This is the documentation change for the code change in https://github.com/iterative/dvc/pull/868.
This change was created together with @EricSchles.

Add documentation for Azure Blob Storage remote

---

pages/features.js
src/Diagram/index.js
static/docs/commands-reference/import.md
static/docs/commands-reference/remote.md
static/docs/introduction/core-features.md
static/docs/introduction/how-it-works.md

This is a follow-up to https://github.com/iterative/dvc.org/pull/40.

Add Azure remote to more places in docs

---

src/Documentation/sidebar.json
static/docs/commands-reference/pipeline.md

docs: add `dvc pipeline`

---

src/Documentation/sidebar.json
static/docs/use-cases/share-data-and-model-files.md

Fixes #45
Signed-off-by: Ruslan Kuprieiev <kupruser@gmail.com>

docs: add s3 and gs to use cases

---

src/Documentation/sidebar.json
static/docs/commands-reference/destroy.md

docs: add `dvc destroy` reference

---

static/docs/commands-reference/metrics.md

docs: update info about `dvc metrics`

---

src/Documentation/sidebar.json
static/docs/user-guide/contributing.md

docs: user guide: add "Contributing" section

---

static/docs/commands-reference/fetch.md
static/docs/commands-reference/pull.md
static/docs/commands-reference/push.md
static/docs/commands-reference/status.md

docs: add --show-checksums option to push/pull/status

---

static/docs/get-started/compare-experiments.md

Master eval.json should have contents: {"AUC": "0.521324"}, hence the output for metrics, should show 0.521324 for master

Spelling and metrics

---

static/docs/get-started/example.md

Created https://github.com/iterative/dvc.org/issues/73 for later .

docs: get-started: make example work

---

src/Documentation/sidebar.json
static/docs/get-started/visualize.md

docs: get-started: add "Visualize" section

---

src/Documentation/sidebar.json
static/docs/use-cases/update-tracked-file.md

Detailed explanation how to update a tracked file
Fixes #82

dvc.org: use-case handling file updates

---

static/docs/get-started/experiments.md

doc: fix typo in experiments

---

static/docs/use-cases/data-and-model-files-versioning.md

As far as I know, `git-lfs` is open and free too: https://git-lfs.github.com/

Update comparation with git-lfs

---

static/docs/commands-reference/import.md
static/docs/commands-reference/remote.md
static/docs/get-started/add-files.md
static/docs/get-started/configure.md
static/docs/user-guide/external-dependencies.md

Support HTTP as a remote

---

static/docs/commands-reference/remote.md

Docs for https://github.com/iterative/dvc/pull/1428

Add option to disable the use of SSL

---

static/docs/get-started/add-files.md
static/docs/get-started/compare-experiments.md
static/docs/get-started/configure.md
static/docs/get-started/connect-code-and-data.md
static/docs/get-started/example-pipeline.md
static/docs/get-started/example-versioning.md
static/docs/get-started/experiments.md
static/docs/get-started/index.md
static/docs/get-started/pipeline.md
static/docs/get-started/reproduce.md
static/docs/get-started/retrieve-data.md
static/docs/get-started/share-data.md
static/docs/tutorial/index.md
static/docs/tutorial/preparation.md
static/docs/tutorial/reproducibility.md
static/docs/tutorial/sharing-data.md

Some grammar fixes in two sections: the `tutorial` and the `get started`

Fix grammar

---

static/docs/commands-reference/config.md

docs: command-reference: config: mention how cache.dir is resolved

---

static/docs/commands-reference/remote.md

Related to https://github.com/iterative/dvc/pull/1474

docs: command-reference: remote: update ssh config

---

static/docs/commands-reference/fetch.md
static/docs/commands-reference/pull.md
static/docs/commands-reference/push.md

Related do https://github.com/iterative/dvc/pull/1479

docs: command reference: pull/push/fetch: update with --recursive option

---

static/docs/commands-reference/gc.md
static/docs/commands-reference/remove.md

docs: add missing optional argument for gc and remove

---

static/docs/user-guide/external-dependencies.md

related: https://github.com/iterative/dvc/pull/1538

remote http: add support for Content-MD5

---

static/docs/tutorial/reproducibility.md

Small fix in the tutorial: trees is 700 in the code and 500 in the commit/text.

Update the trees number

---

static/docs/tutorial/reproducibility.md

Use the DVC command to show all the metrics to compare the branches.

Compare AUC using the metrics

---

static/docs/commands-reference/remote.md

remote s3: Integration with compatible services

---

pages/features.js

Fixed a typo on the features page.

Fixed typo

---

src/Documentation/sidebar.json
static/docs/commands-reference/add.md
static/docs/commands-reference/commit.md
static/docs/commands-reference/run.md

Related to https://github.com/iterative/dvc/pull/1601

docs: update `add/run`, add `commit`

---

static/docs/commands-reference/status.md

related: https://github.com/iterative/dvc/pull/1651

status: imply --cloud when a remote is given

---

static/docs/get-started/compare-experiments.md

While reading through the documentation I found this little typo.

Documentation: Typo correction

---

static/docs/commands-reference/remote:add.md
static/docs/commands-reference/remote:modify.md

Adds documentation for s3.list_objects.   See https://github.com/iterative/dvc/pull/1708

remote: adds support for s3.list_objects

---

static/docs/commands-reference/pull.md
static/docs/commands-reference/remote:add.md
static/docs/commands-reference/status.md

This is mostly finished.  I was unable to determine anything about `--force`.  With `--recursive` the discussion in the discord area was useful, and I wrote some text corresponding to that discussion, but in my own testing was unable to replicate the behavior.  While working I saw a couple other places where discussion of the default remote can be improved.

New Pull documentation for review

---

static/docs/commands-reference/pipeline.md

Add documentation on `pipeline show --tree`

---

static/docs/commands-reference/run.md

Fix a mistake in `dvc run --metrics` documentation

---

static/docs/commands-reference/metrics:show.md

Updating the documentation according to this PR: https://github.com/iterative/dvc/pull/1809

metrics: update metrics.show() documentation

---

src/Documentation/Markdown/lang/dvc.js
src/Documentation/Markdown/lang/usage.js
src/Documentation/sidebar.json

Hey, @jorgeorpinel - please, take a look at these small changes.

fix diff docs naming, add diff and other new commands to hightlighter js

---

static/docs/get-started/install.md

Use `yum` to be consistent with README.rst.

Update Get Started documentation

---

static/docs/commands-reference/add.md
static/docs/commands-reference/import.md

This PR add description about `file` option for `add` and `import`

add description about `file` option for `add` and `import`

---

static/docs/commands-reference/config.md

config: document default link types (reflink, cache)

---

app.json
package.json
src/Documentation/sidebar.json
static/docs/commands-reference/diff.md
static/docs/get-started/add-files.md
static/docs/get-started/connect-code-and-data.md
static/docs/tutorial/define-ml-pipeline.md

Matches tutorial/define-ml-pipeline with get-started/add-files and connect-code-and-data; et al

---

static/docs/commands-reference/metrics:show.md

per PR [#1944](https://github.com/iterative/dvc/pull/1944#discussion_r279194083)

Updates metrics:show.md

---

src/Documentation/sidebar.json
static/docs/user-guide/dvcignore.md

Fixes #248 
Related to https://github.com/iterative/dvc/pull/1820

dvcignore: initial description

---

static/docs/user-guide/contributing.md

This pull request updates the command for running a single test for DVC.

Update command for running a single test

---

static/docs/user-guide/external-outputs.md

External Outputs modified to add dvc add url code block.
Fixes #232

Fixes #232

---

static/docs/commands-reference/remote:modify.md

Documentation for changes in [dvc#1965](https://github.com/iterative/dvc/pull/1965)

add note about ssh config in commands-reference/remote:modify.md

---

static/docs/commands-reference/remote.md
static/docs/commands-reference/remote:add.md
static/docs/commands-reference/remote:list.md
static/docs/get-started/configure.md
static/docs/get-started/share-data.md

Addresses "local remote" and S3 remote example confusions

---

package-lock.json
package.json
src/Documentation/SidebarMenu/SidebarMenu.js

Fixes #272. The best option is to use jquery.slideToggle, since this function can calculate the height of the element in the case of height: auto

Fixes #272

---

static/docs/commands-reference/remote:add.md
static/docs/commands-reference/remote:list.md
static/docs/user-guide/autocomplete.md

Added -f option to `dvc remote add` #231

---

src/Documentation/sidebar.json
static/docs/commands-reference/remote.md
static/docs/commands-reference/remote:add.md
static/docs/commands-reference/remote:default.md
static/docs/commands-reference/remote:list.md
static/docs/commands-reference/remote:modify.md
static/docs/commands-reference/remote:remove.md

Added `dvc remote default` command reference

---

static/docs/tutorial/define-ml-pipeline.md

Fix #139 
If you want to change the message, please let me know. Also should we mention about the innacurate space calculation by du command?
I am GSOD applicant as well 😊

Add note about reflinks in tutorial

---

static/docs/commands-reference/destroy.md
static/docs/commands-reference/init.md
static/docs/commands-reference/metrics:remove.md
static/docs/get-started/example-pipeline.md
static/docs/get-started/initialize.md
static/docs/tutorial/preparation.md
static/docs/user-guide/dvc-files-and-directories.md

Working on my next big contribution I detected some widespread inconsistencies throughout the docs and I'm addressing them in this first PR. It should be a quick one to review/approve, hopefully.

Round of general improvements for docs!

---

static/docs/commands-reference/add.md
static/docs/commands-reference/import.md
static/docs/commands-reference/init.md
static/docs/commands-reference/repro.md
static/docs/commands-reference/run.md
static/docs/get-started/initialize.md
static/docs/get-started/reproduce.md
static/docs/tutorial/define-ml-pipeline.md
static/docs/tutorial/preparation.md
static/docs/user-guide/contributing-documentation.md
static/docs/user-guide/contributing.md
static/docs/user-guide/dvc-files-and-directories.md

Continuation of https://github.com/iterative/dvc.org/pull/322 which was merged super fast. This PR includes a couple more commits along the same lines.

Round 2 of general improvements for docs

---

pages/doc.js

Fixes #286. It seems that with no connection there should be no changes.

Fixes #286

---

pages/_document.js
pages/doc.js
pages/features.js
src/Diagram/index.js
src/Documentation/Markdown/Markdown.js
src/Documentation/Markdown/lang/dvc.js
src/Documentation/SidebarMenu/SidebarMenu.js
src/DownloadButton/index.js
src/FeaturesHero/index.js
src/Footer/index.js
src/GithubLine/index.js
src/HamburgerMenu/index.js
src/LandingHero/index.js
src/Page404/index.js
src/SearchForm/index.js
src/SubscribeForm/index.js
src/TextRotate/index.js
src/TopMenu/index.js
src/UseCases/index.js
src/Video/index.js
src/styles.js

- All the prose are wrapped at 80 characters.

Format JS files according to prettier

---

static/docs/user-guide/contributing.md

Add Test remotes section to Contributing

---

static/docs/tutorial/sharing-data.md

tutorial: change to new repo url of model

---

static/docs/commands-reference/pipeline_show.md

Related to https://github.com/iterative/dvc.org/issues/370

pipeline: show: dot: check that user doesn't accidentally write to dvc file

---

package.json
static/docs/commands-reference/commit.md
static/docs/commands-reference/config.md
static/docs/commands-reference/unprotect.md
static/docs/get-started/add-files.md
static/docs/get-started/example-pipeline.md
static/docs/get-started/example-versioning.md
static/docs/user-guide/analytics.md
static/docs/user-guide/cache-file-linking.md
static/docs/user-guide/contributing-documentation.md
static/docs/user-guide/dvc-files-and-directories.md

- Removes trailing white spaces per https://github.com/iterative/dvc.org/pull/345#pullrequestreview-239795703
- Updates `dvc unprotect` cmd ref.
Fixes #265

Completes optimization guide related updates.

---

static/docs/understanding-dvc/resources.md

embed the videos

---

src/Documentation/sidebar.json
static/docs/commands-reference/add.md
static/docs/commands-reference/checkout.md
static/docs/commands-reference/config.md
static/docs/commands-reference/diff.md
static/docs/commands-reference/fetch.md
static/docs/commands-reference/gc.md
static/docs/commands-reference/metrics_add.md
static/docs/commands-reference/move.md
static/docs/commands-reference/remote_add.md
static/docs/commands-reference/remove.md
static/docs/commands-reference/run.md
static/docs/get-started/add-files.md
static/docs/get-started/example-pipeline.md
static/docs/get-started/example-versioning.md
static/docs/get-started/experiments.md
static/docs/get-started/retrieve-data.md
static/docs/tutorial/define-ml-pipeline.md
static/docs/tutorial/reproducibility.md
static/docs/tutorial/sharing-data.md
static/docs/understanding-dvc/related-technologies.md
static/docs/use-cases/share-data-and-model-files.md
static/docs/user-guide/development.md
static/docs/user-guide/dvc-files-and-directories.md
static/docs/user-guide/dvcignore.md
static/docs/user-guide/external-dependencies.md
static/docs/user-guide/large-dataset-optimization.md
static/docs/user-guide/update-tracked-file.md

- Updates around new large dataset optimization guide
- Standardization in usage of "notes"
- Clarifies the relationship between external dependencies and DVC remotes

Assorted updates to docs

---

static/docs/user-guide/dvc-files-and-directories.md

Elaborate the `.dvc/cache` section to incorporate explanation of its structure.
Fixes #156

Write about the structure of cache directory

---

static/docs/commands-reference/add.md
static/docs/commands-reference/import.md
static/docs/commands-reference/run.md
static/docs/user-guide/dvc-file-format.md

Fixes #306 
meta entry updated and also mentioned that comments are persistent now.

#306 dvc-file-format updated

---

src/Documentation/Markdown/Markdown.js

Transform cursor to pointer when hovering over a collapsible

---

static/docs/commands-reference/version.md

Update `dvc version` command description

---

static/docs/tutorial/define-ml-pipeline.md

mention use of ls -i in tutorial

---

static/docs/commands-reference/remote_modify.md

See https://github.com/iterative/dvc/pull/2106

Documents dvc remote modify myremote sse for s3 remotes

---

static/docs/commands-reference/remote.md
static/docs/commands-reference/remote_add.md
static/docs/get-started/configure.md
static/docs/get-started/install.md
static/docs/user-guide/contributing.md

Modify installation command to make it work on zsh as well

---

static/docs/commands-reference/install.md

Fix #282  I have added documentation for ``pre-push``  git hook.

Fix #282 Added documentation for pre-push

---

static/docs/commands-reference/remote.md
static/docs/commands-reference/remote_add.md
static/docs/get-started/configure.md
static/docs/get-started/install.md
static/docs/user-guide/contributing.md

docs: fixed single quote issue for pip (windows)

---

static/docs/commands-reference/version.md

iterative/dvc#2126 changes updated in docs.
Fixes iterative/dvc#1783

Explain binary attribute in `dvc version` output

---

static/docs/commands-reference/destroy.md

https://github.com/iterative/dvc/pull/2164
bug.

docs: update destroy reference

---

static/docs/commands-reference/remote_modify.md

Fix #453: credentialpath option

---

static/docs/commands-reference/remote_add.md

added a note to create a bucket to commands-reference/remote_add.md

---

static/docs/use-cases/share-data-and-model-files.md

few improvements and remove `#` for right side menu

few improvements for use case

---

static/docs/commands-reference/install.md

Related to:
https://stackoverflow.com/questions/56818930/dvc-push-after-several-local-commits/56820897#comment100200632_56820897

include information about disabling git-hooks

---

static/docs/commands-reference/remote_add.md
static/docs/commands-reference/remote_modify.md

remote: azure storage connection string information

---

static/docs/tutorial/reproducibility.md

Added brief explanation of how to solve git merge conflicts. Provided external link as support. Added also caveat to remove all conflict markers.

Link how to solve git merge conflicts

---

src/Documentation/sidebar.json
static/docs/user-guide/running-dvc-on-windows.md

Fixes #395. This PR adds 'Caveats Running DVC on Windows' page to the `User Guide` of DVC.

Fix #395: Add 'Caveats Running DVC on Windows' page

---

static/docs/commands-reference/destroy.md

also did minor changes in the existing tutorial. As now DVC is removing all the files present in the current workspace.

destroy:behaviour when cache directory is changed introduced

---

static/docs/commands-reference/import-url.md

It never really worked and nobody cared.

Drop import-url --resume option

---

static/docs/commands-reference/remote_add.md

https://github.com/iterative/dvc/pull/2297#issuecomment-513512551

docs: remote-add: hdfs: add JAVA_HOME note

---

static/docs/commands-reference/version.md

Related to https://github.com/iterative/dvc/pull/2320
bug.

docs: command-reference: version: add a note about psutil

---

static/docs/get-started/install.md

Based on https://github.com/iterative/dvc/issues/120#issuecomment-516187067

dvc conda installation

---

static/docs/commands-reference/unprotect.md

changed `unlock` to `unprotect` in Synopsis

---

static/docs/commands-reference/pull.md
static/docs/commands-reference/push.md
static/docs/commands-reference/status.md

Documentation updated to Fix the issue in DVC:
https://github.com/iterative/dvc/pull/2331

remove show-checksums reference from doc

---

static/docs/get-started/install.md

https://github.com/iterative/dvc/issues/120#issuecomment-516815059
bug.

get-started: install: update conda notes

---

src/Documentation/glossary.js
static/docs/user-guide/dvcignore.md

[WIP] dvcignore: update description

---

static/docs/commands-reference/metrics_show.md

metrics show: add note about xpath overwriting xpath defined in stage file

---

pages/_document.js

Fixes #512 
I ran `npm run prettier-js`. These were the only changes `prettier` could detect.

Run prettier formatter on all JS files

---

static/docs/user-guide/external-dependencies.md

Fixes https://github.com/iterative/dvc.org/pull/530#pullrequestreview-272360547 and https://github.com/iterative/dvc.org/pull/530#pullrequestreview-272360593
> Related to #532

lint: fix prettier messup in YAML blocks

---

static/docs/commands-reference/cache/index.md
static/docs/commands-reference/metrics/index.md
static/docs/commands-reference/metrics/show.md
static/docs/commands-reference/pipeline/index.md
static/docs/commands-reference/pull.md
static/docs/commands-reference/push.md
static/docs/commands-reference/remote/add.md
static/docs/commands-reference/remote/default.md
static/docs/commands-reference/remote/index.md
static/docs/commands-reference/remote/list.md
static/docs/commands-reference/remote/modify.md
static/docs/commands-reference/remote/remove.md
static/docs/use-cases/share-data-and-model-files.md

Then I updated menu structure I didn't update links. This PR fixes it.

Fix links in md files

---

src/Documentation/SidebarMenu/SidebarMenu.js

Removes jQuery from SidebarMenu.js and replaces it with css animations. (Because css animations can only transition between 2 known numbers, I have to set element height then it is active).

Rewrite SidebarMenu from jquery to css transitions

---

static/docs/commands-reference/metrics/show.md

Close https://github.com/iterative/dvc/issues/1497

metrics: show support multiple targets

---

static/docs/get-started/configure.md

hotfix: broken details section in get-started/configure

---

static/docs/commands-reference/add.md

The command `dvc add` is not related somehow to a `Dvcfile`; that is only for stages.

Removed wrong statement

---

README.md
server.js
static/docs/commands-reference/import-url.md
static/docs/get-started/add-files.md
static/docs/get-started/connect-code-and-data.md
static/docs/get-started/example-pipeline.md
static/docs/get-started/example-versioning.md
static/docs/get-started/index.md
static/docs/tutorial/define-ml-pipeline.md
static/docs/tutorial/preparation.md
static/docs/tutorial/sharing-data.md
static/docs/user-guide/contributing.md
static/docs/user-guide/external-dependencies.md

server: update redirects (new bucket); corresponding doc updates

---

static/docs/commands-reference/remote/modify.md

docs for https://github.com/iterative/dvc/pull/2415

add s3 acl config docs

---

src/Tooltip/index.js
static/docs/commands-reference/status.md

Case insensitive matching with glossary terms

---

static/docs/commands-reference/remote/modify.md

Related to https://github.com/iterative/dvc/pull/2424
bug.

remote: modify: add note about gssapi

---

pages/_document.js
src/styles.js
static/fonts/fonts.css

Fixes font blinking in Chrome: https://github.com/styled-components/styled-components/issues/1593

Move @font-face rules to static css file in head

---

static/docs/get-started/add-files.md

fix: typo in add files get started

---

pages/doc.js

Don’t remove right colum on loading

---

static/docs/commands-reference/install.md

Merge after https://github.com/iterative/dvc/pull/2505

install: update description about behaviour on existing hook

---

static/docs/get-started/example-pipeline.md

example pipeline: add mkdir data instruction

---

static/docs/user-guide/dvcignore.md

Fix minor typo in dvcignore.md

---

src/Documentation/Markdown/Markdown.js
src/Tooltip/index.js

glossary: make tooltip IDs unique

---

static/docs/get-started/agenda.md

A minor fix for incorrect grammar ('to discourage') and contorted sentence structure.
It's the first page of the tutorial so worth fixing :-)

Improve the readability

---

static/docs/user-guide/contributing.md

https://github.com/iterative/dvc/issues/2181#issuecomment-537327653
[Contributing Documentation](https://dvc.org/doc/user-guide/contributing-docs)?
bug.

contributing: clarify test requirements

---

static/docs/command-reference/add.md
static/docs/command-reference/import-url.md
static/docs/command-reference/lock.md
static/docs/command-reference/repro.md
static/docs/command-reference/run.md
static/docs/command-reference/unlock.md
static/docs/command-reference/unprotect.md
static/docs/command-reference/update.md
static/docs/tutorials/deep/define-ml-pipeline.md

Refers to the changes in iterative/dvc/pull/2576

Update docs to reflect import output changes

---

server.js

Requested in a previous PR:
https://github.com/iterative/dvc.org/pull/666#pullrequestreview-297612264
https://github.com/iterative/dvc.org/pull/666#discussion_r331335740
https://github.com/iterative/dvc.org/pull/666#discussion_r331604349

Fix deep tutorial redirection

---

static/docs/command-reference/gc.md

Fixed some ambiguous and wrong phrasing for the dvc gc command reference.

cmd ref: fix some phrasing issues in gc

---

src/Layout/index.js
src/Modal/index.js
src/Tooltip/desktop-view.js
src/Tooltip/index.js
src/Tooltip/mobile-view.js

Add mobile view for tooltip

---

static/docs/use-cases/index.md

Fix broken link

---

static/docs/command-reference/init.md
static/docs/command-reference/repro.md
static/docs/get-started/initialize.md
static/docs/tutorials/deep/preparation.md
static/docs/tutorials/pipelines.md
static/docs/tutorials/versioning.md
static/docs/user-guide/dvc-file-format.md
static/docs/user-guide/large-dataset-optimization.md

some copy edits on the versioning tutorial. might be some weird formatting stuff going on?

versioning copy edits

---

static/docs/understanding-dvc/collaboration-issues.md
static/docs/understanding-dvc/core-features.md
static/docs/understanding-dvc/existing-tools.md
static/docs/understanding-dvc/how-it-works.md
static/docs/understanding-dvc/related-technologies.md
static/docs/understanding-dvc/resources.md
static/docs/understanding-dvc/what-is-dvc.md

Copy edits for the understanding DVC docs section

understanding-dvc: copy edits

---

static/docs/command-reference/get-url.md
static/docs/command-reference/get.md
static/docs/command-reference/import-url.md
static/docs/command-reference/import.md
static/docs/get-started/install.md

Related to iterative/dvc#2610
[Contributing Documentation](https://dvc.org/doc/user-guide/contributing-docs)?
description of the PR. This enables GitHub to link the PR to the corresponding
bug.

cmd ref: describe updated `--out` behavior in get/import/*-url

---

.eslintrc.json
src/Documentation/RightPanel/RightPanel.js
src/Documentation/SidebarMenu/SidebarMenu.js
src/Hamburger/index.js
src/PromoSection/index.js
src/Subscribe/index.js
src/TrySection/index.js
src/styles.js

Fix #706 
Removing tabs and adding new rule in .eslintrc.json to not allow tabs in the code.

Fix #706:  Exchanging tabs for spaces and adding lint rule

---

src/Tooltip/desktop-view.js

Fix positioning of tooltips

---

src/Documentation/sidebar.json

According to the discussions here:
- https://github.com/iterative/dvc.org/pull/734#issuecomment-546194830
- https://github.com/iterative/dvc.org/pull/734#issuecomment-546195619

Move installation page on top of the menu

---

static/docs/install/linux.md
static/docs/install/macos.md
static/docs/install/windows.md

Partially addressed #746
Used https://github.com/iterative/dvc.org/pull/690/files#diff-a5173e320dcf100fc3ff5b32ba2ea911 to find broken links

fix doc broken links to miniconda.html

---

static/docs/user-guide/contributing/core.md

from https://github.com/iterative/dvc/pull/2546#issuecomment-547026944

remove unneeded general commit component `dvc`

---

static/docs/tutorials/deep/preparation.md
static/docs/tutorials/pipelines.md
static/docs/tutorials/versioning.md

regular updates (early Nov)

---

static/docs/tutorials/versioning.md

See https://github.com/iterative/example-versioning/pull/5#issuecomment-548637438

tutorials: metrics.json -> metrics.csv

---

server.js

hotfix: server redirect of man.dvc.orl/import-url and

---

server.js

Actually fixes #768
(Finishes #769)

hotfix previous hotfix! (#769)

---

server.js

Let's try this @shcheklein ...

hotfix: rewrite man.dvc.org redirect logic without ternary op to see if it fixes #768

---

static/docs/use-cases/data-registry.md

Per https://github.com/iterative/dvc.org/pull/679#issuecomment-552621599

use-cases: data registry case - last details [WIP]

---

.circleci/config.yml
package.json
pages/_document.js
pages/doc.js
pages/features.js
pages/index.js
pages/support.js
src/Documentation/HeadInjector.js
src/Documentation/SidebarMenu/SidebarMenu.js
src/PromoSection/index.js
src/Subscribe/index.js
src/TrySection/index.js
yarn.lock

Reorganizes code in first pages and a few components so order makes more sense (e.g. imports used in order, general components before specific ones, etc), adds basic code documentation (not sure needed), and fixes #716.

Basic React code refactoring & linting

---

static/docs/command-reference/add.md
static/docs/command-reference/metrics/add.md
static/docs/command-reference/metrics/modify.md
static/docs/command-reference/metrics/remove.md
static/docs/command-reference/metrics/show.md
static/docs/command-reference/remote/add.md
static/docs/command-reference/repro.md
static/docs/command-reference/run.md
static/docs/user-guide/contributing/core.md
static/docs/user-guide/contributing/docs.md

and some improvements in the revised texts

Improve readability of multi-paragraph cmd options.

---

static/docs/install/linux.md

AUR package is not maintained.
- Have you followed the guidelines in
[Contributing Documentation](https://dvc.org/doc/user-guide/contributing/docs)?
description of the PR. This enables GitHub to link the PR to the corresponding
bug.

install: remove arch instructions

---

.github/PULL_REQUEST_TEMPLATE.md
static/docs/command-reference/import-url.md
static/docs/command-reference/import.md
static/docs/command-reference/update.md
static/docs/get-started/import-data.md
static/docs/user-guide/dvc-file-format.md
static/docs/user-guide/external-dependencies.md

and improve refs among this example and `dvc update` cmd ref.
Closes #796

Improve re-importing example in `dvc import`

---

static/docs/command-reference/remote/add.md

Fixes #781 
Fixes #802
- Have you followed the guidelines in
[Contributing Documentation](https://dvc.org/doc/user-guide/contributing/docs)?
description of the PR. This enables GitHub to link the PR to the corresponding
bug.

cmd ref: add a note about SSH/SFTP quirks in remote add

---

static/docs/command-reference/import-url.md
static/docs/command-reference/metrics/index.md
static/docs/command-reference/metrics/show.md
static/docs/command-reference/pull.md
static/docs/command-reference/push.md

mainly for get-started issues per #599

term: review usage of "experiment" (and remove "variant")

---

package.json
src/GithubLine/index.js
src/TrySection/index.js
yarn.lock

- Fixed error with TrySection on `/features` page.
- Fixed error with setState in GithubLine on the `/` page.
- Checked other pages for errors.

Fix #791: next: console  errors

---

static/docs/user-guide/contributing/core.md

Should be merged only after https://github.com/iterative/dvc/pull/2908 lands.

docs: add writing tests section to contributing guide

---

static/docs/command-reference/config.md

Added the definition of what a `section` is as it was a little confusing.

Update config.md for more clarity

---

static/docs/command-reference/remote/add.md

GDrive docs correction to address issue found by @shcheklein . Thank you for finding out this issue!

Google Project account can be different from user's Google Drive account.

---

static/docs/command-reference/get.md
static/docs/command-reference/import-url.md
static/docs/command-reference/import.md
static/docs/command-reference/update.md

Doc for recent change for local repo cache import fix iterative/dvc.org/pull/859
(for iterative/dvc/pull/2915).

Document for local repo cache import fix

---

static/docs/command-reference/config.md

config: add `hardlink_lock` description

---

static/docs/command-reference/get.md
static/docs/command-reference/import.md

This update reflects https://github.com/iterative/dvc/pull/2889
Fix #835

import: supports also non-output files/dirs

---

static/docs/use-cases/data-registries.md

Fix broken use-case link

---

server.js

prevent appending slash when redirecting error

---

public/static/docs/understanding-dvc/what-is-dvc.md

Fix markup of link to pipeline command

---

pages/doc.js
public/static/docs/user-guide/troubleshooting.md
src/Documentation/Markdown/Markdown.js

add custom anchor support for titles in md

---

public/static/docs/tutorials/deep/sharing-data.md

Revert "update target stage in pulling data from the cloud example"

---

public/static/docs/tutorials/deep/sharing-data.md

Revert "update pulling data from the cloud example"

---

public/static/docs/install/completion.md
public/static/docs/install/linux.md
public/static/docs/user-guide/contributing/docs.md

- fixes #918 document snap install option
- also slight tidy for contrib guide's explanation of folder layout

install: add snap instructions

---

public/static/docs/user-guide/contributing/docs.md

No ticket associated, just noticed that the Circle build is failing and am sending a fix.
------

style: run prettier

---

src/Documentation/SidebarMenu/SidebarMenu.js

sidebar: do not highlight links on hover

---

public/static/docs/command-reference/config.md
public/static/docs/use-cases/shared-development-server.md

Fixes #497
Please chose to
[allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
to edit your branch when creating the PR.

add cache.shared config reference and use case

---

redirects-list.json
scripts/exclude-links.txt
scripts/link-check.sh
server.js
src/utils/redirects.js
src/utils/redirects.test.js

Fixing some loose ends with #943, addressing @jorgeorpinel and @shcheklein's feedback. Also fixed the troubleshooting redirect URL which was missing the `/doc` prefix.
-------
Please chose to
[allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
to edit your branch when creating the PR. …

refactor: move some files around, fix loose ends and fix broken redirect

---

public/static/docs/use-cases/data-registries.md

fix typo in "Building registries" 1st code block

---

public/static/docs/command-reference/push.md

cmd ref: push: fix link

---

scripts/link-check-git-diff.sh

test: link-check against merge base

---

public/static/docs/command-reference/pull.md
public/static/docs/command-reference/push.md

cmd ref: push/pull: fix docs about recursive option

---

src/components/Documentation/SidebarMenu/styles.js

Tiny PR to adjust animation speed.

Reduce animation delay for side menu

---

public/static/docs/changelog/0.35.md
public/static/docs/command-reference/add.md
public/static/docs/command-reference/checkout.md
public/static/docs/command-reference/config.md
public/static/docs/command-reference/diff.md
public/static/docs/command-reference/fetch.md
public/static/docs/command-reference/import.md
public/static/docs/command-reference/init.md
public/static/docs/command-reference/install.md
public/static/docs/command-reference/push.md
public/static/docs/command-reference/remote/add.md
public/static/docs/command-reference/remove.md
public/static/docs/command-reference/run.md
public/static/docs/command-reference/unprotect.md
public/static/docs/get-started/add-files.md
public/static/docs/get-started/connect-code-and-data.md
public/static/docs/get-started/initialize.md
public/static/docs/get-started/older-versions.md
public/static/docs/tutorials/deep/define-ml-pipeline.md
public/static/docs/tutorials/deep/preparation.md
public/static/docs/tutorials/pipelines.md
public/static/docs/tutorials/versioning.md
public/static/docs/user-guide/dvcignore.md
public/static/docs/user-guide/large-dataset-optimization.md
public/static/docs/user-guide/updating-tracked-files.md

- Misc. stuff
- Closes #719 (core repo match: iterative/dvc/pull/3322)
- Reflect iterative/dvc/pull/3312

Regular updates (Feb 13)

---

public/static/docs/tutorials/deep/define-ml-pipeline.md

Fix typo and missing line in define-ml-pipeline.md

---

public/static/docs/command-reference/init.md
public/static/docs/command-reference/remote/add.md
public/static/docs/command-reference/run.md
public/static/docs/get-started/add-files.md
public/static/docs/tutorials/deep/define-ml-pipeline.md
public/static/docs/tutorials/pipelines.md
public/static/docs/tutorials/versioning.md
public/static/docs/understanding-dvc/how-it-works.md
public/static/docs/understanding-dvc/related-technologies.md
public/static/docs/use-cases/versioning-data-and-model-files.md

- Addresses https://github.com/iterative/dvc.org/pull/1003#pullrequestreview-359980907

Regular updates (2/17)

---

server.js
src/utils/redirects.js
src/utils/redirects.test.js

server: reformat/refactor around redirects (again)

---

package.json
src/components/Community/Events/index.js
src/components/Documentation/SidebarMenu/index.js
yarn.lock

Another Sentry error https://sentry.io/organizations/iterative/issues/1521458935/

Fix ie11 fill

---

public/static/docs/api-reference/read.md

[fix] add a comma

---

public/static/docs/command-reference/run.md

Used the **Edit on GitHub** button from dvc.org to improve a doc in place.

Typo fix: remove apostrophe from possessive "its".

---

public/static/docs/command-reference/install.md

Related to https://github.com/iterative/dvc/pull/3406 …

install: add pre-commit config

---

public/static/docs/command-reference/install.md

docs: fix formatting in `dvc install` cmd ref

---

scripts/link-check.sh

tests: links: treat 429 as success

---

scripts/exclude-links.txt
scripts/link-check-git-all.sh
scripts/link-check-git-diff.sh
scripts/link-check.sh

tests: links: add missing & sort

---

scripts/link-check-git-diff.sh

tests: links: exit 0 on empty diffs

---

gatsby-config.js
src/components/Documentation/Markdown/styles.js

Fix styles after migrating to Gatsby.js

---

content/docs/command-reference/add.md
content/docs/command-reference/cache/index.md
content/docs/command-reference/commit.md
content/docs/command-reference/install.md
content/docs/command-reference/repro.md
content/docs/command-reference/run.md
content/docs/command-reference/status.md
content/docs/user-guide/dvc-file-format.md

Addresses docs part of iterative/dvc/issues/3446

cmd ref: review commit explanations

---

content/docs/command-reference/fetch.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/status.md

docs: add `--all-commits` for push/pull/status/fetch/metrics show

---

README.md
content/docs/changelog/0.18.md
content/docs/changelog/0.35.md
content/docs/command-reference/checkout.md
content/docs/command-reference/commit.md
content/docs/command-reference/config.md
content/docs/command-reference/fetch.md
content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/index.md
content/docs/command-reference/metrics/remove.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/pull.md
content/docs/command-reference/remote/modify.md
content/docs/tutorials/deep/define-ml-pipeline.md
content/docs/tutorials/index.md
content/docs/tutorials/versioning.md
content/docs/use-cases/data-registries.md
content/docs/use-cases/sharing-data-and-model-files.md
content/docs/user-guide/contributing/core.md
content/docs/user-guide/contributing/docs.md
content/docs/user-guide/index.md
content/docs/user-guide/troubleshooting.md
package.json
scripts/link-check-git-all.sh

- link-check script fixes
- Review "section" term to match changes in #1074
- misc. stuff

Regular updates (Apr 8)

---

package.json
yarn.lock

Closes https://github.com/iterative/dvc.org/issues/1108

Return back old pre-commit behaviour when we can review formatting changes

---

.eslintignore
.eslintrc.json
README.md
content/docs/sidebar.json
content/docs/user-guide/contributing/blog.md
content/docs/user-guide/contributing/docs.md
gatsby-config.js
gatsby-ssr.js
package.json

README/contributing: update after migration to Gatsby

---

src/components/Link/index.tsx

Closes https://github.com/iterative/dvc.org/issues/1146

Make redirects in the Link component only for links in the current domain

---

src/components/Link/index.tsx

Closes https://github.com/iterative/dvc.org/issues/1146

Fix incorrect redirect after clicking on the links

---

content/blog/2020-04-06-april-20-dvc-heartbeat.md

change contributor of windows optimizations
Thank you for the contribution - we'll try to review it as soon as …

correct contributor name

---

content/docs/command-reference/params/diff.md
content/docs/command-reference/params/index.md

Params:
1. No dependencies to stage files anymore
2. `--all` option for diff
Per iterative/dvc/pull/3631

Params: remove stage deps and --all option

---

gatsby-config.js
src/templates/blog-post.tsx

I still need to do more to improve this, but this'll bring the feed back to life.
Partially addresses #1177

Fix feed titles (mostly)

---

scripts/exclude-links-check.sh
scripts/link-check-git-all.sh
scripts/link-check-git-diff.sh
scripts/link-check.sh
scripts/utils.sh

Puts all common link-check definitions into one place.
Due to https://github.com/iterative/dvc.org/pull/1193#issuecomment-620159356

test: abstract all helpers to utils.sh

---

content/docs/command-reference/status.md

Fixes https://github.com/iterative/dvc.org/issues/1217 …

docs: add `status -R` description

---

content/docs/command-reference/run.md

Per https://github.com/iterative/dvc/pull/3737 …

docs: run: remove -y|--yes

---

content/docs/user-guide/contributing/docs.md

Fixes https://github.com/iterative/dvc.org/pull/1226#issuecomment-624281043

[docs]: correct the Gitpod button's Url.

---

content/blog/2020-05-08-dvc-ambassador-program.md.md

Now the link leads to the beginning of the blogpost.

Updates mribeirodantas' blog post URL

---

content/docs/command-reference/update.md

docs: update: add -R|--recursive

---

content/docs/install/linux.md
content/docs/install/macos.md
content/docs/install/windows.md

[WIP] update supported Python versions (drop 3.5)

---

content/docs/command-reference/repro.md
content/docs/command-reference/run.md

Per https://github.com/iterative/dvc/pull/3788 …

docs: --ignore-build-cache -> --no-run-cache

---

redirects-list.json

add plurality redirect to plot documentation

---

content/blog/2020-05-08-dvc-ambassador-program-announcement.md

add "why become an ambassador" section

---

content/docs/command-reference/list.md

Changes pending to [iterative/dvc/pull/3797](https://github.com/iterative/dvc/pull/3797)
Fixes [iterative/dvc/issues/3589](https://github.com/iterative/dvc/issues/3589) …

Renamed --outs-only to --dvc-only

---

content/docs/install/completion.md

Tested on fresh ubuntu. This is what is in default FPATH env var.
Thank you for the contribution - we'll try …

docs: completion:  change zsh path

---

content/docs/install/linux.md

install: linux: snap: add `--beta`

---

content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/modify.md

- remove or fix WebDAV remote info (close #1355)
-

Regular updates (May 25)

---

content/docs/command-reference/add.md

Subtask : 
> Definitely in the description of https://dvc.org/doc/command-reference/add, and maybe add an > example (not sure) which could be copied from these.
of issue #1033 completed.

user-guide: add more links to the .dvcignore guide from other docs. Subtask one completed

---

content/docs/command-reference/import.md
content/docs/command-reference/metrics/index.md
content/docs/command-reference/metrics/show.md
content/docs/tutorials/versioning.md

get-started: fix broken links

---

content/docs/command-reference/import-url.md
content/docs/command-reference/import.md

docs: don't forget about import cmd ref

---

content/docs/command-reference/checkout.md

Small correction in checkout example

---

content/docs/command-reference/status.md

Per https://github.com/iterative/dvc/pull/3998 …

docs: status: add --show-json

---

content/docs/tutorials/get-started/index.md

Update index.md typo

---

content/docs/command-reference/metrics/diff.md

Per https://github.com/iterative/dvc/pull/4026 …

cmd ref: doc metrics diff --precision

---

content/blog/2020-06-08-june-20-dvc-heartbeat.md

fixing broken link and typo pointed out by Alexander

fix typo + broken link

---

content/docs/command-reference/plots/index.md

Per https://github.com/iterative/dvc/pull/4045 …

plots: mark template fields as required/optional

---

content/docs/tutorials/get-started/data-versioning.md

simplify and update get started data versioning

---

content/docs/command-reference/metrics/diff.md
content/docs/command-reference/metrics/show.md

This PR updates cmd ref according to https://github.com/iterative/dvc/pull/3963
* cmd ref: metrics diff: targets desc updated per https://github.com/iterative/dvc/pull/3963
* cmd ref: metrics show: targets desc updated per https://github.com/iterative/dvc/pull/3963
Part of #1414

cmd ref: metrics 1.0 update

---

content/docs/command-reference/plots/index.md

per https://github.com/iterative/dvc.org/pull/1436#pullrequestreview-432115021 …

cmd ref: copy edits on plots index

---

content/docs/user-guide/dvc-files-and-directories.md

user guide: fix existing dvc file anchors in files&dirs

---

content/docs/tutorials/get-started/data-versioning.md

I believe there is an error in the example code of making changes in get started. …

Docs: Fix Details of Making Changes in Get Started

---

config/prismjs/dvc-commands.js
content/docs/tutorials/get-started/data-pipelines.md
content/docs/tutorials/get-started/data-versioning.md
content/docs/tutorials/get-started/index.md

get started: prepare data pipelines for the 1.0

---

content/docs/command-reference/import-url.md

fix import url example with the latest changes to the get started repo

---

content/docs/command-reference/import-url.md

fix #1459
related to PR iterative/dvc#4075
Thank you for the contribution - we'll try to review it as soon as …

Update of import-url --no-exec flag

---

content/docs/tutorials/get-started/data-versioning.md

corrected mention of data.xml.dvc

---

content/docs/tutorials/get-started/data-versioning.md

get started: corrected terminal output

---

content/docs/command-reference/params/index.md

cmd ref: improvements to params and 1.0 update!

---

content/docs/install/completion.md

Better installation paths for MacOS and Ubuntu/Debian.

install: completion: fix/improve paths

---

content/docs/command-reference/fetch.md
content/docs/command-reference/pull.md

Continuation of https://github.com/iterative/dvc.org/pull/1481#pullrequestreview-435423999

cmd ref: complete --run-cache option

---

content/blog/2020-06-22-dvc-1-0-release.md

Fix example `dvc.yaml` on 1.0 release blogpost

---

content/docs/command-reference/run.md

Remove duplicate entry
--external is also described lower down on the list. …

Remove duplicate entry

---

content/docs/start/data-pipelines.md

Fix #issue small typo on data pipelines page

---

content/docs/command-reference/gc.md

Fixes #1075 
Changes as per observations in https://github.com/iterative/dvc.org/issues/1075#issuecomment-643669420

Added a note that gc might try to pull missing .dir cache files

---

content/docs/command-reference/import-url.md

per https://github.com/iterative/dvc.org/pull/1460#pullrequestreview-434468382

cmd: small update for import-url

---

content/docs/start/index.md

Fix broken and missing links in Getting Started

---

src/gatsby/utils/resolvers/index.js

This PR fixes an issue where the site wouldn't build if a blog post isn't given an image.

Fix support for image-less blog posts

---

content/docs/user-guide/dvcignore.md

A PR as an outcome of the dicsussion [here](https://github.com/iterative/dvc.org/pull/1378#issuecomment-653296608).

Updated pattern dir1/* to 'dir1/*' in dvcignore.md

---

content/blog/2020-06-26-scipy-2020-dvc-poster.md

SciPy is beginning and I wanted to add a few more links to the virtual poster

adding a few links to poster

---

content/blog/2020-06-26-scipy-2020-dvc-poster.md

one more link missing

---

content/docs/command-reference/run.md

cmd: rephrase intro of run (2)

---

content/docs/command-reference/plots/diff.md

cmd ref: doc plots diff --targets with revisions usage

---

content/docs/use-cases/shared-development-server.md

shared development server: migrate to 1.0

---

content/docs/user-guide/dvc-files-and-directories.md

per https://github.com/iterative/dvc.org/pull/1494#pullrequestreview-441361208 …

guide: update types of checksums in dvc.lock doc

---

content/docs/user-guide/dvc-files-and-directories.md

per https://github.com/iterative/dvc.org/pull/1527#pullrequestreview-445153044 …

guide: small corrections for dvc.lock fields

---

content/docs/command-reference/run.md

per https://github.com/iterative/dvc.org/pull/1537#discussion_r450714820 …

cmd: simplify info about when cmd are run

---

content/docs/install/completion.md

install: remove horizontal scroll bar from completion page

---

content/docs/start/index.md

Typo: Update index.md

---

gatsby-node.js
package.json
scripts/clear-cloudflare-cache.js
scripts/deploy-with-s3.js
src/gatsby/models/github/index.js

Reverts iterative/dvc.org#1587

Revert "Improve CloudFlare cache clear logging and GitHub Stars bugfix"

---

content/docs/command-reference/add.md
content/docs/command-reference/move.md
content/docs/command-reference/unprotect.md
content/docs/start/data-versioning.md
content/docs/use-cases/shared-development-server.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/use-cases/versioning-data-and-model-files/tutorial.md
content/docs/user-guide/dvc-files-and-directories.md
content/docs/user-guide/updating-tracked-files.md

Made changes to other instances of the `dvc add` command in the docs.
Per https://github.com/iterative/dvc.org/pull/1605#issuecomment-661584188

Review all dvc add examples throughout docs #1605

---

content/docs/command-reference/remote/modify.md

per https://github.com/iterative/dvc.org/pull/1603#pullrequestreview-452007291 …

cmd: update remote modify with --local as needed

---

content/docs/command-reference/push.md
content/docs/command-reference/remote/modify.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/user-guide/managing-external-data.md
content/docs/user-guide/updating-tracked-files.md

Extracted from other issues and PRs where these were out of scope

doc: misc. updates (late July)

---

content/docs/command-reference/dag.md

grammar fix(es)

---

content/docs/command-reference/params/index.md
content/docs/command-reference/run.md
content/docs/start/experiments.md
content/docs/user-guide/dvc-files-and-directories.md

Related to https://github.com/iterative/dvc/pull/4258

add params example with toml parameters file

---

content/docs/user-guide/external-dependencies.md

Since the change to v1 of DVC, the description of generating a separate DVC file is no longer true

Update external deps examples dvc run command

---

content/docs/command-reference/status.md

cmd ref: status: describe default -j value

---

content/docs/command-reference/check-ignore.md
content/docs/command-reference/get.md
content/docs/command-reference/import.md
content/docs/command-reference/init.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/modify.md
content/docs/user-guide/dvcignore.md

- Dvcignore (and check-ignore) related updates per https://github.com/iterative/dvc.org/pull/1629#pullrequestreview-463015446 et al.
- get/import -o description update
- more remote add/modify updates per [this chat](https://discord.com/channels/485586884165107732/485596304961962003/741357885052813313)

doc: misc. updates

---

content/docs/command-reference/config.md

Fixes: Add doc to changes for Issue https://github.com/iterative/dvc/issues/1894

core.check_update: Add config documentation for check_update core config

---

content/docs/api-reference/open.md
content/docs/api-reference/read.md
content/docs/command-reference/get-url.md
content/docs/command-reference/import-url.md
content/docs/command-reference/list.md
content/docs/command-reference/remote/index.md
content/docs/install/macos.md
content/docs/install/pre-release.md
content/docs/user-guide/contributing/core.md
content/docs/user-guide/contributing/docs.md
content/docs/user-guide/related-technologies.md
content/docs/user-guide/updating-tracked-files.md

per https://github.com/iterative/dvc.org/pull/1581#pullrequestreview-464616673 …

term: Github->GitHub

---

content/docs/user-guide/dvc-files-and-directories.md

doc: close abbr tags in params

---

content/blog/2017-05-15-how-a-data-scientist-can-improve-his-productivity.md

DS productivity title

---

content/docs/command-reference/metrics/index.md

Add -n flag to dvc run which is now required

---

content/docs/install/plugins.md
content/docs/user-guide/dvc-files-and-directories.md

Document about jsonschema for dvc.yaml

---

content/docs/user-guide/merge-conflicts.md

Minor typo fix

---

content/docs/command-reference/get-url.md
content/docs/command-reference/import-url.md
content/docs/command-reference/index.md
content/docs/command-reference/list.md
content/docs/command-reference/metrics/index.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/modify.md

- Review usage of term "tracking" (extracted from #1716)
- Close #1706 by reviewing WebDAV URLs

docs: misc updates +

---

content/docs/user-guide/troubleshooting.md

Per https://github.com/iterative/dvc/pull/4480 …

troubleshooting: add s3-related entries

---

content/docs/command-reference/config.md
content/docs/command-reference/install.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/default.md
content/docs/command-reference/remote/index.md

- 3 unrelated corrections in cmd ref explanations.
- Improvements to basic remote refs.

docs: misc. updates

---

content/docs/command-reference/remote/modify.md

documentation for #4547 and #4517

Update http remote documentation

---

content/docs/use-cases/data-registries.md

fix: typo in docs

---

content/docs/command-reference/diff.md

diff: document --hide-missing option

---

content/docs/command-reference/add.md
content/docs/command-reference/config.md

related to https://github.com/iterative/dvc/pull/4543 …

config: document new `core.autostage` setting

---

content/docs/command-reference/move.md
content/docs/command-reference/run.md
content/docs/user-guide/dvc-files-and-directories.md

- Update `move` ref.
- Review it's examples carefully
- Add note and example about renaming stages

cmd: move 1.x updates

---

.github/workflows/link-check-deploy.yml

I messed up a commit that removed the old config, and also was referencing the ref string improperly.

Fix master link check suppression

---

.github/workflows/link-check-deploy.yml

Suppressing the link check on master is eluding me, so I made this branch to help diagnose and solve the issue for good.

Prevent deployment check on master via deployment ref

---

content/docs/command-reference/config.md
content/docs/command-reference/run.md
content/docs/index.md
content/docs/use-cases/data-registries.md

docs: period after "etc.)"

---

content/docs/command-reference/index.md
content/docs/command-reference/repro.md

For https://github.com/iterative/dvc/pull/4566
I hope this isn't too obtrusive, but a blurb like this was the only way I could see to squeeze this in the heading.
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-fr …

cmd: doc root --cd flag

---

content/docs/user-guide/how-to/undo-adding-data.md

how-to: fix broken link

---

content/docs/command-reference/params/diff.md
content/docs/command-reference/params/index.md

Per https://github.com/iterative/dvc/pull/4655 …

docs: update params diff table

---

content/docs/command-reference/install.md

https://discordapp.com/channels/485586884165107732/563406153334128681/762305272512249856 …

docs: update pre-commit hook

---

content/docs/start/data-versioning.md
src/components/Home/UseCases/index.tsx

Based on discussion with @dmpetrov- changing the video embedded on the Use Cases section of the landing page for a more recent DVC video from our YouTube channel.

Front page video

---

content/docs/user-guide/troubleshooting.md

Rel https://github.com/iterative/dvc/issues/4325

Added troubleshooting section for lock issue on network fs

---

content/docs/command-reference/add.md
content/docs/command-reference/index.md
content/docs/command-reference/pull.md
content/docs/command-reference/run.md
content/docs/install/pre-release.md
content/docs/start/data-pipelines.md
content/docs/user-guide/index.md
content/docs/user-guide/merge-conflicts.md

- Misc. one-line copy edits
- Improve mention of `dvc --cd` (fixes #1853) and cmd ref index

misc. updates

---

content/authors/elle_obrien.md

Just updated a broken twitter link

Update twitter link from @andronovhopf to @DrElleOBrien

---

content/docs/command-reference/import-url.md
content/docs/user-guide/dvc-files-and-directories.md
content/docs/user-guide/external-dependencies.md

Replaced strong etags with HTTP ETags

---

content/docs/start/experiments.md

Removed a duplicated word in a docs page

---

config/prismjs/dvc-commands.js
content/docs/command-reference/doctor.md
content/docs/sidebar.json

Added documentation for the `doctor` alias of the `dvc version` command. The related code PR fixes issue #3185
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the …

added documentation for doctor command

---

content/docs/command-reference/remote/modify.md

adds example using digitalocean spaces tutorial

---

content/docs/command-reference/params/index.md

Micro typo fix

---

content/docs/command-reference/cache/dir.md
content/docs/command-reference/config.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/default.md
content/docs/command-reference/remote/list.md
content/docs/command-reference/remote/modify.md
content/docs/command-reference/remote/remove.md
content/docs/command-reference/remote/rename.md

Looks like an old leftover/misunderstanding.
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/770294056902852650

docs: /etc/dvc.config -> /etc/dvc/config

---

content/docs/command-reference/add.md
content/docs/user-guide/troubleshooting.md

add: document behavior for adding symlinked targets

---

content/docs/user-guide/troubleshooting.md

troubleshooting: add entry for "no possible cache types"

---

content/docs/command-reference/import-url.md
content/docs/command-reference/import.md

In line with https://github.com/iterative/dvc/pull/4817.

docs: add --no-exec param in 'import' command

---

content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/modify.md

Fix s3 remote commands in docs (remove url text placeholder)

---

content/docs/command-reference/fetch.md
content/docs/command-reference/get.md
content/docs/command-reference/pull.md

cmd: some example updates as per 1.x

---

content/docs/start/data-pipelines.md

YouTube link is added; will be live on Nov. 24 at 6 AM PST. Merge after that.

add video link to pipelines docs page

---

content/docs/user-guide/how-to/add-deps-or-outs-to-a-stage.md

ref https://github.com/iterative/dvc.org/pull/1976#issuecomment-735018384 …

hotfix: bad how-to frontmatter

---

content/docs/command-reference/add.md

hotfix: 404 in add cmd ref.

---

content/docs/start/experiments.md

Video goes live at 8 AM tomorrow morning- let's merge right after that.

add video link to experiments page

---

content/docs/command-reference/install.md

install: clarify usage with pre-commit tool

---

content/docs/command-reference/config.md

Add docs regarding config --list

---

content/blog/2020-03-24-march-20-community-gems.md
content/blog/2020-04-06-april-20-dvc-heartbeat.md
content/blog/2020-04-16-april-20-community-gems.md
content/blog/2020-05-08-dvc-ambassador-program-announcement.md
content/blog/2020-05-14-may-20-dvc-heartbeat.md
content/blog/2020-05-26-may-20-community-gems.md
content/blog/2020-06-08-june-20-dvc-heartbeat.md
content/blog/2020-06-26-scipy-2020-dvc-poster.md
content/blog/2020-07-10-july-20-dvc-heartbeat.md
content/blog/2020-07-16-devops-for-data-scientists.md
content/blog/2020-07-22-july-20-community-gems.md
content/blog/2020-07-24-first-mlops-tutorial.md
content/blog/2020-07-27-shtab-completion-release.md
content/blog/2020-08-07-cml-self-hosted-runners-on-demand-with-gpus.md
content/blog/2020-11-11-november-20-dvc-heartbeat.md
content/docs/command-reference/remove.md
content/docs/use-cases/versioning-data-and-model-files/index.md

The most important here- fixed two broken links in docs, please keep an eye on GH actions.
--------
Thank you …

fix linters: broken links, frontmatter style

---

content/docs/command-reference/config.md

Per https://github.com/iterative/dvc/pull/5090 …

docs: adjust help for config

---

content/docs/command-reference/dag.md

per https://github.com/iterative/dvc/pull/4739 …

cmd: add --outs option for dag

---

content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/repro.md
content/docs/command-reference/run.md
content/docs/user-guide/dvc-files-and-directories.md
content/docs/user-guide/external-dependencies.md

dvc.yaml: document `persist` field, et al.

---

content/docs/command-reference/get.md
content/docs/command-reference/import.md
content/docs/command-reference/list.md

cmd: finish list 1.0 update and clarify about local url

---

content/docs/command-reference/config.md

cmd: fix config file paths

---

content/docs/command-reference/remove.md

Updated remove.md in relation to iterative/dvc#5148 …

Updated remove.md

---

content/docs/command-reference/dag.md

per https://github.com/iterative/dvc/pull/4739
Additions based on the comment https://github.com/iterative/dvc.org/pull/1918#pullrequestreview-555107771
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) …

cmd: add example section for dag --outs option

---

content/docs/cml/index.md

Docs in cml.dev will reference this page. We need a backlink for these users. This is probably not the best backlink - please LMK if you have other ideas.

Add ref to cml.dev

---

content/docs/user-guide/dvc-files.md

A few last quick 2.0ish changes I wasn't able to push to #2062 before it was approved.
Partly per https://github.com/iterative/dvc.org/pull/2052#discussion_r549063671

guide: remove confusing language around DVC File defaults

---

content/docs/command-reference/remote/modify.md

Add S3 session-token configuration

---

content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/remote/modify.md

[v1] more 1.x updates... (import)

---

content/docs/command-reference/list.md

Fixed very minor typing error.

---

content/docs/install/macos.md

docs: add a note about brew install on M1 mac

---

content/linked-terms.js

Oops, this was missed/broken by #2098.

hotfix! correct DVC File autolinks

---

content/docs/install/macos.md

Dvc bottle should be available now https://github.com/Homebrew/homebrew-core/pull/69837 …

docs: remove m1 warning

---

content/docs/start/data-versioning.md

per https://discord.com/channels/485586884165107732/485596304961962003/804720632436490271 …

start: missing git add

---

content/docs/command-reference/fetch.md
content/docs/command-reference/get.md
content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/init.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/repro.md
content/docs/start/data-access.md
content/docs/use-cases/shared-development-server.md
content/docs/use-cases/sharing-data-and-model-files.md
content/docs/user-guide/external-dependencies.md

From my older git stash (done clearing!)
> PR into `v1` for visualization purposes for now.

[v1] last (old) misc updates

---

content/docs/cml/get-started.md

adjusted tabs to code and changed name to match cml website

---

content/docs/command-reference/fetch.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/status.md

per https://github.com/iterative/dvc.org/pull/2122#pullrequestreview-581733135
> Complements #2122

cmd: --jobs option desc in sync refs

---

content/docs/use-cases/shared-development-server.md
content/docs/use-cases/sharing-data-and-model-files.md

2.
Minor copy edits to use cases

Last (old) misc updates (2/4) from v1

---

content/docs/command-reference/diff.md

diff: document behavior for file renames

---

content/docs/cml/cml-with-npm.md
content/docs/cml/index.md
content/docs/cml/self-hosted-runners.md
content/docs/cml/start-github.md
content/docs/sidebar.json
content/docs/user-guide/contributing/docs.md

fix 118858c9582ef4d12865fb319b83396b99b82951 et al.

cml: doc titles [SEO] and other fixes

---

content/docs/command-reference/get-url.md
content/docs/command-reference/get.md
content/docs/command-reference/import.md

This reverts the irrelevant changes done in #2091

revert irrelevant changes from --to-remote

---

.restyled.yaml

updated restyled bot config to be the same as prettierrc config via command flags (Fix #2179)

---

config/prismjs/dvc-commands.js
content/docs/command-reference/stage/add.md
content/docs/command-reference/stage/index.md
content/docs/sidebar.json
content/docs/user-guide/basic-concepts/stage.md

Closes #2134 
Most of them are copied and pasted from `dvc run` command. I haven't added much information in `index.md` as I wasn't sure what to add there.

document stage:add

---

content/docs/command-reference/remote/modify.md
content/docs/user-guide/setup-google-drive-remote.md

gdrive: service-auth with json

---

content/docs/command-reference/update.md

cmd: explicitly mention update is forbidden for repo imports

---

content/blog/2021-02-18-dvc-2-0-pre-release.md

Minor fixes for the blog post announcing 2.0 prerelease. 
This does not close any issue.

Minor fixes and typo corrections for the blog post announcing 2.0 prerelease. 

---

content/docs/user-guide/managing-external-data.md

user-guide: drop google storage from external outputs list

---

content/docs/cml/cml-with-dvc.md
content/docs/cml/self-hosted-runners.md
content/docs/cml/start-github.md

For the upcoming CML 0.3.0 docs, we're going to need to add a few details to the docs on dvc.org/doc. Any edits are welcome.

CML 0.3.0 docs update

---

content/docs/install/linux.md

Part of https://github.com/iterative/dvc-s3-repo/issues/3 …

install: add signatures

---

content/blog/2021-03-03-dvc-2-0-release.md

We have been working on DVC for *almost* 4 years. …

fixed typo in blog

---

content/blog/2021-03-03-dvc-2-0-release.md

dvc 2.0 post - small fixes

---

content/docs/command-reference/exp/run.md

Fix usage bug in dvc exp run

---

content/docs/start/data-versioning.md

`dvc get` can create the folder if it does not exist already. …

getting-started: data versioning: remove mkdir when getting dataset

---

content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md

cmd: document -c/--checkpoints for `run` and `stage add`

---

content/docs/command-reference/plots/diff.md
content/docs/command-reference/plots/show.md

Implemented on https://github.com/iterative/dvc/pull/5584 …

document plots diff/show --open flag

---

content/docs/command-reference/config.md
content/docs/command-reference/destroy.md
content/docs/user-guide/managing-external-data.md

> Forced re-try of #2297
A bit less random than #2296 but still a continuation of the same process (cleaning up my git stash post 2.0 release)

More misc. updates

---

redirects-list.json
src/utils/shared/redirects.test.js

Preparation for serving signed exe packages. …

redirects: add dvc.org/exe

---

content/docs/command-reference/cache/dir.md

per https://github.com/iterative/dvc.org/pull/2311#pullrequestreview-615705927 …

ref: update system config paths

---

content/docs/install/linux.md
content/docs/install/macos.md
content/docs/install/windows.md

Fixes https://github.com/iterative/dvc/issues/4997 …

install: conda: add instructions on optional dependencies

---

content/docs/command-reference/import.md
content/docs/use-cases/data-registries.md

Fix some typos in data-registries.md and import.md

---

content/docs/command-reference/checkout.md
content/docs/command-reference/commit.md
content/docs/command-reference/exp/apply.md
content/docs/command-reference/exp/branch.md
content/docs/command-reference/exp/diff.md
content/docs/command-reference/exp/gc.md
content/docs/command-reference/exp/list.md
content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/command-reference/exp/run.md
content/docs/command-reference/exp/show.md
content/docs/command-reference/fetch.md
content/docs/command-reference/get.md
content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/install.md
content/docs/command-reference/metrics/index.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/pull.md
content/docs/index.md
content/docs/start/data-pipelines.md
content/docs/start/experiments.md
content/docs/start/metrics-parameters-plots.md
content/docs/use-cases/index.md
content/docs/use-cases/versioning-data-and-model-files/tutorial.md
content/docs/user-guide/large-dataset-optimization.md
content/docs/user-guide/project-structure/pipelines-files.md

This is self-approved maintenance work, but need a formal approval to merge.

link: fix old/bad Get Started links

---

content/docs/command-reference/add.md
content/docs/command-reference/import-url.md
content/docs/command-reference/init.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md

ref: avoid mkdir in examples

---

content/blog/2021-03-31-march-21-community-gems.md

above plus changing where the meetup info resides

revisions to experiments in directories question

---

content/blog/2019-03-05-march-19-dvc-heartbeat.md
content/blog/2019-04-18-april-19-dvc-heartbeat.md
content/blog/2019-09-26-september-19-dvc-heartbeat.md
content/blog/2020-03-24-march-20-community-gems.md
redirects-list.json

link checker: fix dvc file format links and redirects

---

config/link-check/excluded-links.yml
content/blog/2019-12-14-november-19-dvc-heartbeat.md
content/blog/2020-02-17-a-public-reddit-dataset.md
content/blog/2020-08-10-august-20-dvc-heartbeat.md

link check: fix more broken links

---

content/docs/user-guide/running-dvc-on-windows.md

guide: fix typos in win symlinks

---

content/docs/command-reference/exp/show.md

Docs for:
https://github.com/iterative/dvc/pull/5720

exp show: Add info about wildcard patterns

---

content/docs/command-reference/exp/run.md

exp run: update exp run --reset behavior

---

content/docs/command-reference/exp/gc.md
content/docs/command-reference/exp/show.md
content/docs/command-reference/fetch.md
content/docs/command-reference/gc.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/status.md

rel https://github.com/iterative/dvc.org/pull/2325#pullrequestreview-620832943

ref: rewrite scope options for sync/gc/exp commands (--all-commits, etc.)

---

.gitpod.yml
content/docs/command-reference/plots/diff.md
content/docs/command-reference/plots/show.md
content/docs/command-reference/repro.md

- term "file name" (2 words)
- remove .gitpod.yaml
-

Misc updates

---

content/docs/command-reference/remote/modify.md

Remote modify: Added kerb_ticket option for HDFS

---

content/docs/command-reference/exp/gc.md
content/docs/command-reference/fetch.md
content/docs/command-reference/gc.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/status.md

per https://github.com/iterative/dvc/pull/5783 …

ref: add `-A` to `--all-commits`

---

content/blog/2020-11-26-dvc-vs-rclone.md
content/docs/command-reference/config.md
content/docs/command-reference/remote/modify.md
content/docs/command-reference/version.md
content/docs/install/completion.md
content/docs/install/index.md
content/docs/install/macos.md
content/docs/sidebar.json
content/docs/user-guide/contributing/core.md
content/docs/user-guide/large-dataset-optimization.md
content/docs/user-guide/project-structure/dvcignore-files.md
content/docs/user-guide/troubleshooting.md
content/docs/user-guide/what-is-dvc.md
src/components/DownloadButton/index.tsx

Thanks @wbednarski for noticing this

fix Mac OS -> macOS

---

content/docs/command-reference/remote/modify.md

remote: fix confusing ssl option

---

content/docs/api-reference/make_checkpoint.md
content/docs/command-reference/exp/apply.md
content/docs/command-reference/exp/branch.md
content/docs/command-reference/exp/run.md
content/docs/user-guide/contributing/docs.md

- Addresses https://github.com/iterative/dvc.org/pull/2243#pullrequestreview-603422799 and https://github.com/iterative/dvc.org/pull/2286#pullrequestreview-615217332 (finally)
- And 1. from #2397 and close #2399 (inc. `make_checkpoint()` update)
- Other improvements and copy edits

ref: corrections to `exp run/apply/branch` +

---

content/docs/user-guide/experiment-management.md

per https://github.com/iterative/dvc.org/issues/2292#issuecomment-816849304

guide: link to sample checkpoints repo from Exps

---

content/docs/command-reference/exp/apply.md

per https://github.com/iterative/dvc.org/issues/2397#issuecomment-827547029 …

ref: correction about when `exp apply` can fail

---

content/docs/api-reference/open.md

docs: fix typo tied --> tried

---

content/docs/dvclive/usage.md

Fix typo in dvclive documentation

---

content/docs/command-reference/list.md

list: add --show-json option

---

content/docs/command-reference/repro.md

extracted from https://github.com/iterative/dvc.org/pull/2369#pullrequestreview-638147274 …

ref: update `repro targets` bullet list

---

content/docs/command-reference/params/diff.md

params diff: document --deps option

---

content/docs/command-reference/import.md
content/docs/use-cases/versioning-data-and-model-files/tutorial.md

per iterative/dataset-registry/pull/14

cases: update refs to data-registry/tutorials

---

content/docs/command-reference/import-url.md
content/docs/command-reference/plots/modify.md
content/docs/dvclive/usage.md
content/docs/start/data-and-model-access.md
content/docs/start/data-pipelines.md
content/docs/user-guide/experiment-management/checkpoints.md

Extracted from https://github.com/iterative/dvc.org/pull/2359#pullrequestreview-655879340

doc: review all diff and git code blocks

---

content/docs/command-reference/remote/modify.md
content/docs/user-guide/setup-google-drive-remote.md

`remote modify`: use `--local` where needed

---

content/docs/start/metrics-parameters-plots.md

Correct spelling error.

---

content/docs/command-reference/stage/add.md

cmd ref: rm 'Implies --no-exec' in stage add

---

content/blog/2020-12-30-december-20-community-gems.md
content/blog/2021-02-22-cml-runner-prerelease.md
content/docs/cml/self-hosted-runners.md
content/docs/cml/usage.md

docs: fix outdated CML links

---

content/docs/user-guide/how-to/update-tracked-data.md

doc: fix broken link

---

src/templates/blog-post.tsx

* Adds quality of 90 to blog-post picture query, stopping blog webp images from looking blurry

Update blog post image quality

---

content/blog/2021-06-02-introducing-dvc-studio.md
src/templates/blog-post.tsx

- Deduplicate and simplify text
- Move videos/images to the top - they are more important then text
- Add emojis, links, other formatting
- Merge master

Improve blog post
