src/Documentation/sidebar.json
static/docs/use-cases/how-to-store-files-in-dvc.md
static/docs/user-guide/dvc-file-format.md

Starting off with 'How to store files in dvc' and 'DVC file format'.
Signed-off-by: Ruslan Kuprieiev <kupruser@gmail.com>

docs: add 'User Guide' and 'Use Cases' sections

---

src/Documentation/sidebar.json
static/docs/use-cases/multiple-data-scientists-on-a-single-machine.md

docs: add 'Using Shared Server For The Team'

---

static/docs/commands-reference/metrics.md

(docs): Fix typo It's should -> It should

---

static/docs/tutorial/define-ml-pipeline.md

By using the -M parameter instead of the -o, it turns the evaluation file into a metric file,
that can be displayed with the command: `dvc metrics show` as highlighted later.

Use metrics instead of regular output

---

static/docs/tutorial/define-ml-pipeline.md

Clarify that the `.dvc` file is created within the current working directory, and add an example of changing the filename of the `.dvc` file using the `-f`` option.
Response to issue #188.

Clarify .dvc file creation location

---

static/docs/get-started/pipeline.md

Hello,
This is a proposed fix for the issue https://github.com/iterative/dvc.org/issues/220 i opened
This should fix the error message I get when running the training step command in the tutorial:
```
$ dvc run -d src/train.py -d data/features \
-o model.pkl \
python src/train.py -d data/features model.pkl 
Running command:
python src/train.py -d data/features model.pkl
Arguments error. Usage:
python train.py features model
Error: failed to run command - stage 'model.pkl.dvc' cmd python src/train.py -d data/features model.pkl failed
```

Fix training step command in tutorial

---

static/docs/get-started/metrics.md

Proposing a minor change here as following the initial docs I encountered an error down the line where I could not compare model metrics across. My understanding is it didn't work because I hadn't committed the `auc.metric` file because the docs explicitly indicate not to.
Please let me know if I missed something here or blatantly misunderstood how dvc works.
Also, super cool tool thanks for all the hard work 😄

docs: get-started metrics correction

---

static/docs/commands-reference/pipeline:show.md

Document `--locked` option on `pipeline show`. re dvc#1864

pipeline: document --locked option

---

static/docs/commands-reference/checkout.md
static/docs/commands-reference/commit.md
static/docs/commands-reference/import.md
static/docs/commands-reference/install.md

This commit is only the dvc install documentation.  The dvc import documentation is still to come.

Update dvc install and dvc import documentation

---

src/Documentation/SidebarMenu/SidebarMenu.js

The height of the each section sets strongly in pixels. While opening the root section the height was figured according to a formula (quantity of child elements * 31 px), herewith the quantity of elements of the active child section wasn’t considered. Now it’s corrected.

Fix GitHub Issue #273

---

src/Footer/index.js

Fixes #266. From Google - their search engine can independently assign a title for the site, for example, if the title in the <title> tag does not match the page content. Given that the string "DVC" in search results is uppercase, Google took it from the 'alt' attribute of the logo in footer. After the changes on the site, you need to make a request for re-indexing, the instruction is here https://support.google.com/webmasters/answer/6065812/?hl=ru, the indexing tool itself is https://search.google.com/search-console/welcome, http://joxi.ru/gmv4VBOtqnyN5A. Because of the difference in time zones, I don’t know when the next PR will be accepted for merging, so I didn’t request indexing myself, this requires making changes to the site without leaving the search-console page.

Fixes #266

---

src/Documentation/Markdown/lang/dvc.js
src/Documentation/Markdown/lang/usage.js
src/Documentation/sidebar.json
static/docs/commands-reference/version.md

Fixes #307 
These changes add the documentation for the command `dvc version` which was added in [iterative/dvc#1963](https://github.com/iterative/dvc/pull/1963).
I had one doubt though.
This is how the usage appears. The name of the command here is black in color but for rest of the command it is blue in color. Why is that so?

Add documentation for `dvc version` command

---

package-lock.json
package.json

-  `prettier` is now upgraded to `1.17.0`. This is done so that it matches the version in `pre-commit-config.yaml` and there is no contradiction in formatting styles when running `npm run prettier-js` or committing changes.
-  `npm run prettier-src` is now split into two commands:
+ `npm run prettier-js`: This will format all JavaScript files.
+ `npm run prettier-md`: This will format all Markdown files. Here is [the guide](https://github.com/prettier/prettier/pull/2943#issue-144033529) according to which markdown will be formatted. The comment says all the configurations are enforced so I don't think that an option will be there to alter these.

Upgrade prettier and add command for formatting markdown files

---

src/Documentation/Markdown/Markdown.js
static/docs/get-started/add-files.md
static/docs/get-started/compare-experiments.md
static/docs/get-started/configure.md
static/docs/get-started/connect-code-and-data.md
static/docs/get-started/example-pipeline.md
static/docs/get-started/example-versioning.md
static/docs/get-started/experiments.md
static/docs/get-started/initialize.md
static/docs/get-started/install.md
static/docs/get-started/metrics.md
static/docs/get-started/older-versions.md
static/docs/get-started/pipeline.md
static/docs/get-started/reproduce.md
static/docs/get-started/retrieve-data.md
static/docs/get-started/share-data.md
static/docs/get-started/visualize.md

@ivan I have been thinking about using css padding by calling a html element like this:
```
<div class="intent">
$ sudo yum update
$ sudo wget https://dvc.org/rpm/dvc.repo -O /etc/yum.repos.d/dvc.repo
$ sudo yum install dvc
$ sudo yum update
$ sudo yum install dvc
</div>
```
with .intent having property padding-left:4em as css attribute.
I am not familiar with React, so I am not sure, what is correct change to be done there. Yet I hope this approach work, as its done for tag <detail> in docs.
Thanks

[WIP] Fix #313

---

static/docs/user-guide/contributing-documentation.md

Add instructions to setup pre-commit hook as added in [this](https://github.com/iterative/dvc.org/pull/324) pull request.

Add pre-commit hook instructions to contribution documentation guide

---

static/docs/commands-reference/version.md

The output of command `dvc version` displays DVC version differently depending upon the way of installing. These changes are made to explain the difference in output.
Fixes #335

Write info about the detail of DVC version

---

src/Documentation/sidebar.json
static/docs/commands-reference/add.md
static/docs/commands-reference/cache.md
static/docs/commands-reference/checkout.md
static/docs/commands-reference/config.md
static/docs/commands-reference/status.md
static/docs/get-started/add-files.md
static/docs/get-started/example-pipeline.md
static/docs/get-started/example-versioning.md
static/docs/tutorial/define-ml-pipeline.md
static/docs/understanding-dvc/related-technologies.md
static/docs/use-cases/share-data-and-model-files.md
static/docs/user-guide/analytics.md
static/docs/user-guide/cache-file-linking.md
static/docs/user-guide/dvc-files-and-directories.md
static/docs/user-guide/update-tracked-file.md

New cache file linking guide and related updates to existing docs

---

.pre-commit-config.yaml
package.json
requirements.txt
static/docs/user-guide/contributing-documentation.md

Husky and pretty quick is used as a pre-commit hook.
- `--staged` flag ensures that `pretty-quick` runs `prettier` only on staged files.
- `--bail` flag ensures that committing is prevented even if the files are fixed.
Fixes #372

Add configuration for husky pre-commit hook

---

static/docs/get-started/connect-code-and-data.md

As I'm not a Python expert but I'm digging into the Data/ML space, I spent a few minutes trying to understand what was `virtualenv` and how could I get it. 
Of course, doing a quick search on the internet solved my problem, but why not adding a link reference directly to the docs to accelerate people like that are going through the tutorials? :)

connect-code-and-data - Adding link reference to virtualenv

---

static/docs/get-started/add-files.md

According to a [conversation](https://discordapp.com/channels/485586884165107732/485596304961962003/583712131619487744) I had with Ruslan on Discord, we agreed to change the title and description of this collapsed help text to make it more visible for people on Windows who are already using Terminals like `Cmder`, `WSL` or even the new `Windows Terminal` but are still facing issues using wget.
The issue seems to be related to SSL certificates.
- https://github.com/ContinuumIO/anaconda-issues/issues/10709
But I don't think that fixing this certificate issue is on the scope of this repo, so it makes more sense to generalize the docs.

Add-file - adjusting help title to get the data.xml file from a browser

---

.circleci/config.yml

- There is no `yarn.lock` file since we don't use yarn so `yarn install` will fail. `npm install` will work.
- Since there are no tests, `npm run test`/`yarn test` would fail.

Fix configuration in ci tests

---

static/docs/user-guide/development.md

For naming convention, a link is added to `dvc version` command.

link to dvc version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Fix #146 
@shcheklein you must need to activate ISSUE Templates in the repository as mentioned [here](https://help.github.com/en/articles/about-issue-and-pull-request-templates)
Do check this also: https://help.github.com/en/articles/creating-issue-templates-for-your-repository

Fix#146:add issues and PR template

---

package.json

Add [`--no-restage`](https://github.com/azz/pretty-quick#--no-restage-only-git) flag to prevent restaging.
Fixes #372

Prevent restaging after pre commit formatting

---

static/docs/commands-reference/cache_dir.md
static/docs/commands-reference/config.md
static/docs/commands-reference/remote_add.md
static/docs/commands-reference/remote_default.md
static/docs/commands-reference/remote_modify.md
static/docs/commands-reference/remote_remove.md

Extracted from changes in #417 (unrelated to `pkg`)

regular update to docs (early June)

---

static/docs/commands-reference/repro.md

These changes show the working of command `dvc repro --downstream`
Fixes #271

Elaborate working of downstream flag in command `dvc repro`

---

static/docs/commands-reference/root.md

Fixes #404 to refactor `root` command reference guide and improve its style to be aligned with other commands.

Fix #404: Refactor root and improve its style.

---

static/docs/commands-reference/add.md
static/docs/commands-reference/checkout.md
static/docs/commands-reference/destroy.md
static/docs/commands-reference/fetch.md
static/docs/commands-reference/import.md
static/docs/commands-reference/lock.md
static/docs/commands-reference/metrics_add.md
static/docs/commands-reference/metrics_modify.md
static/docs/commands-reference/pipeline_show.md
static/docs/commands-reference/repro.md
static/docs/commands-reference/run.md
static/docs/get-started/add-files.md
static/docs/get-started/example-pipeline.md
static/docs/get-started/example-versioning.md
static/docs/get-started/initialize.md
static/docs/get-started/older-versions.md
static/docs/get-started/reproduce.md
static/docs/get-started/retrieve-data.md
static/docs/get-started/share-data.md
static/docs/tutorial/define-ml-pipeline.md
static/docs/tutorial/preparation.md
static/docs/understanding-dvc/how-it-works.md
static/docs/understanding-dvc/related-technologies.md
static/docs/understanding-dvc/what-is-dvc.md
static/docs/use-cases/data-and-model-files-versioning.md
static/docs/use-cases/share-data-and-model-files.md
static/docs/user-guide/contributing-documentation.md
static/docs/user-guide/dvc-file-format.md
static/docs/user-guide/dvc-files-and-directories.md
static/docs/user-guide/external-outputs.md

Continuation of #422 
Fixes #321

term: standard way to refer to DVC-files (2)

---

static/docs/commands-reference/checkout.md
static/docs/commands-reference/pull.md

This PR reorders command flags to make similar flags `-d` and `-R` together.

Reorder command options (flags) in the command reference guide

---

static/docs/commands-reference/config.md
static/docs/commands-reference/remote.md

Fix #415 
I just added the information to create a bucket with the links to it in commands-reference/config and commands-reference/remote .

Creating a bucket is necessary before adding it to remote storage

---

static/docs/commands-reference/add.md
static/docs/commands-reference/checkout.md
static/docs/commands-reference/commit.md
static/docs/commands-reference/fetch.md
static/docs/commands-reference/lock.md
static/docs/commands-reference/metrics_show.md
static/docs/commands-reference/pipeline.md
static/docs/commands-reference/pipeline_list.md
static/docs/commands-reference/pipeline_show.md
static/docs/commands-reference/pull.md
static/docs/commands-reference/push.md
static/docs/commands-reference/remote_add.md
static/docs/commands-reference/remove.md
static/docs/commands-reference/repro.md
static/docs/commands-reference/run.md
static/docs/commands-reference/status.md
static/docs/commands-reference/unlock.md
static/docs/commands-reference/unprotect.md
static/docs/get-started/index.md
static/docs/get-started/pipeline.md
static/docs/user-guide/external-outputs.md
static/docs/user-guide/large-dataset-optimization.md

Misc. needed updates/improvements to several docs.

docs: regular update (late June) [WIP]

---

static/docs/commands-reference/remote_modify.md

Fix #469 Recommend --local for remote modify connection_string
- Modified code example to include `--local` for recommended behaviour
- Added a note explaining why `--local` is safer to use

Fix #469: Recommend --local for remote modify connection_string

---

static/docs/commands-reference/push.md
static/docs/get-started/share-data.md

added git-push in docs

---

static/docs/commands-reference/config.md

Documents the `core.checksum_jobs` config option added by https://github.com/iterative/dvc/pull/2197.

config: add core.checksum_jobs config option

---

pages/doc.js

If `docsearch` triggers `ReferenceError`, `this.state.search` wil be set to `false` which in turn will not render the search bar.

Handle reference error if docsearch is not imported

---

static/docs/commands-reference/run.md

https://stackoverflow.com/questions/57132106/expanding-environment-variables-in-the-command-part-of-a-dvc-run?noredirect=1#comment100795441_57132106
bug.

run: mention single-quotes

---

static/docs/commands-reference/commit.md
static/docs/commands-reference/import-url.md
static/docs/commands-reference/install.md
static/docs/commands-reference/push.md
static/docs/commands-reference/repro.md
static/docs/commands-reference/status.md
static/docs/user-guide/dvcignore.md

Modifies commands-reference and user-guide docs to reflect the changes made to solve issue #2346 of the dvc repo
bug.

Modifies commands-reference and user-guide docs

---

src/Documentation/Markdown/Markdown.js
src/Documentation/Markdown/utils/remark-linker.js

- Chech if page exists and only create link it if it exists
- If subcommand page exists – link to page, if not, create anchor

Update links to subcommands

---

static/docs/user-guide/autocomplete.md

Instructions for fixing bash autocomplete on debian/ubuntu. Fix #525

Fix: #525: How to fix autocomplete on debian/ubuntu

---

static/docs/get-started/agenda.md
static/docs/get-started/example-pipeline.md

hotfix: wrong links in get-started/example-pipeline

---

src/Documentation/SidebarMenu/helper.js

If item has children – last child should be next prevRef value.

Fixes #559: Child order in prev/next

---

static/docs/commands-reference/pipeline/index.md

"show" and "list" links are directing to a non existent page (404 not found error is returned). 
I fix the link with the appropriate url.
This is a minor change.

Fix broken link "show" and "list"

---

static/docs/commands-reference/remote/modify.md

Fix [#2327](https://github.com/iterative/dvc/issues/2327).  Add documentation of the `gss_auth` option for ssh remotes.
I am having difficulty with...
> Content must be properly formatted at 80 symbols width
...since the Wikipedia link I included has a long uninterrupted portion.  Feel free to remove or change this link, however, I recommend keeping the mention of kerberos in this section (sense the majority of GSS authentication is through kerberos).

Fix #2327: add gss_auth option for ssh

---

package.json
yarn.lock

They are already installed via submodules of other dependencies so there is no practical problems, but to prevent bugs in the future it is better to add them explicitly.

Explictly add prop-types and @babel/core to package.json

---

src/Tooltip/index.js

Fixes #518 
To test these changes, please edit the `add.md` file as follows

Trim newline characters in tooltip texts

---

src/Documentation/SidebarMenu/SidebarMenu.js

Problem with the current version is an incorrect calculation of opened item height (we need to supply height to make animations work). Right now height is calculated without considering height of opened children. This PR fix it.
P. S. Old branch had name with `$` symbol which prevented circle.ci from working. I recreated PR with correct name.

Fix #598: Hidden items in sidebar if submenu is opened

---

static/docs/commands-reference/run.md
static/docs/commands-reference/status.md
static/docs/user-guide/dvc-file-format.md

As per https://github.com/iterative/dvc/pull/2479

docs: run: add --always-changed flag

---

static/docs/understanding-dvc/related-technologies.md

Currently pipeline isn't rendered as a link..because a typo: an extra ]
Yes, it's a small change

fix: pipeline not showed as link in related tech

---

static/docs/get-started/metrics.md

In get started > metrics.
Says:
using the `-R` option of `dvc run`.
when there isn't any -R option. So maybe ir refers to the -M option.
Yes, it's a small one

Fix: typo dvc run -R to -M

---

static/docs/commands-reference/config.md

Fix #627: clarify which option is used by default for 'dvc config'

---

src/styles.js
static/docs/tutorials/versioning.md

Fixes #685 
```
```
This generates:
```
<p>
<em>Dataset to classify cats and dogs</em>
</p>
```
Now I styled the element using `img + em` selector.
- `margin-top` is given as `-6px` so that there is `2px` space between the image and the caption. It is not noticeable here since the background colour of image is white.
- The colour is the same as the one used in quotes.

Add styles to render captions for images

---

static/docs/get-started/agenda.md

get-started: agenda copy edits

---

static/docs/command-reference/add.md
static/docs/command-reference/lock.md
static/docs/command-reference/run.md
static/docs/command-reference/unlock.md
static/docs/command-reference/unprotect.md
static/docs/tutorials/deep/define-ml-pipeline.md

With reference to iterative/dvc#2607
In static/docs/command-reference/run.md,
I changed `'a'` to `'1'` because it was a typographical error.
In static/docs/tutorials/deep/define-ml-pipeline.md,
I experimented with add zip files which showed that it also creates a directory where extracted files are put.

add: update output samples per decreased verbosity

---

src/Tooltip/desktop-view.js

Hovering over keywords inside blockquotes took their text colour. These changes are introduced to fix that.

Darken the color in tooltips

---

static/docs/command-reference/add.md
static/docs/command-reference/checkout.md
static/docs/command-reference/fetch.md
static/docs/command-reference/import-url.md
static/docs/command-reference/install.md
static/docs/command-reference/pull.md
static/docs/command-reference/push.md
static/docs/command-reference/status.md
static/docs/command-reference/unprotect.md
static/docs/tutorials/deep/sharing-data.md
static/docs/use-cases/share-data-and-model-files.md
static/docs/user-guide/external-dependencies.md

This removes the loading bar from the READMEs described in
Fix #707

Fix #707: remove all loading bars in the readme docs

---

pages/doc.js

Fixes #681 
So I couldn't debug why `element.scrollIntoView()` wasn't working so I came up with an alternate solution.
1. It finds the location of the anchored header using `element.getBoundingClientRect().top` which is with respect to the topmost point in the window.
2. Now we scroll to this position but subtract the `headerHeight` because it is scrolling with respect to the `bodybag` container (it starts below the header) since it has the `overflow-y` property set.

Fix scrolling behaviour for anchored headers

---

consts/index.js
pages/doc.js
src/Documentation/Markdown/Markdown.js
src/Documentation/RightPanel/RightPanel.js
src/Tooltip/desktop-view.js
src/TopMenu/index.js

Fixes #681 
Partially addresses #714

Use a unique `id` to access the app header and content body instead of a `className`

---

static/docs/user-guide/contributing/core.md

The command which was already written
```
$ python -m tests tests/func/test_metrics.py::TestCachedMetrics
```
ran a test case of one or more functions.
These changes instruct to run a single test function.
Should I also add running a single test function inside a single test case? It will be something like this.
```
$ python -m tests tests/unit/utils/test_fs.py::TestContainsLink::test_should_return_true_on_symlink_in_path
```

Write command for running a single test function

---

static/docs/tutorials/versioning.md

Per https://discordapp.com/channels/485586884165107732/485596304961962003/639182858426122251

tutorials: address errors in versioning tut code samples

---

static/docs/get-started/visualize.md

The last stage value was showing "model.pkl.dvc" instead of "train.dvc"
https://dvc.org/doc/get-started/visualize
Stages > dvc pipeline show --ascii train.dvc

Updated the last stage

---

static/docs/command-reference/version.md

- Have you followed the guidelines in
[Contributing Documentation](https://dvc.org/doc/user-guide/contributing/docs)?
description of the PR. This enables GitHub to link the PR to the corresponding
bug.

version CR: add package manage name field

---

static/docs/get-started/retrieve-data.md

The `Retrieve Data` section already has a code snippet to delete `data/data.xml`, but the notice seems to have remained from the old days when there didn't use to be deletion code snippet. I found this very confusing, and maybe others did as well. Again, this is redundant, anyway.

Remove confusing deletion instruction on get-started

---

static/docs/command-reference/init.md
static/docs/get-started/add-files.md
static/docs/get-started/initialize.md
static/docs/tutorials/deep/preparation.md
static/docs/tutorials/pipelines.md
static/docs/tutorials/versioning.md

docs: update notes about cache dir

---

static/docs/command-reference/import.md
static/docs/get-started/initialize.md

External-dependencies is quite advanced concept that is necessary only in rear optimization cases. It is better not to use and reference to external-dependencies if there is no real need.

Get rid of links to external dependencies in import command

---

static/docs/get-started/index.md

get started: update index page

---

src/Documentation/Markdown/Markdown.js
static/img/external-link.svg

Added custom renderer for links that will add target="_blank" to external links and show icon after them

Fix #729: Open external domain links in a new tab

---

package.json
pages/api/comments.js
server.js
src/consts.js
yarn.lock

API handle to return comments count to use in blog.dvc.org (see iterative/blog#8).

api: Discourse API "proxy" endpoint at /api/comments

---

pages/features.js
src/Diagram/index.js
static/docs/command-reference/get-url.md
static/docs/command-reference/import-url.md
static/docs/command-reference/remote/add.md
static/docs/command-reference/remote/index.md
static/docs/command-reference/remote/modify.md
static/docs/get-started/configure.md
static/docs/install/linux.md
static/docs/install/macos.md
static/docs/install/windows.md
static/docs/understanding-dvc/core-features.md
static/docs/understanding-dvc/how-it-works.md
static/docs/use-cases/sharing-data-and-model-files.md
static/docs/use-cases/versioning-data-and-model-files.md
static/docs/user-guide/contributing/core.md

Fix #381
- List of supported remotes is extended with Google Drive (`gdrive`).
- Step by step guide to create and configure Google Project to access user's Google Drive.
- Description of `client id` and `client secret` config options for `gdrive` remote.

gdrive support

---

src/Documentation/Tutorials.js

Katacoda button text is wrapped to the second line in FF and Edge. This PR fixes it.

Fix Katacoda button line-break

---

static/docs/command-reference/get.md

Per iterative/dvc/pull/2837 (from iterative/dvc/issues/2515)

get: add example on downloading normal git files

---

pages/doc.js
src/Documentation/Markdown/Markdown.js

Fix for 404 errors in #849. Error was with our custom 404 page logic - we was checking if the page exists by matching it's url with the sidebar.json content without removing the hash.

Fix client navigation for links with hashes

---

static/docs/command-reference/pipeline/show.md
static/docs/user-guide/running-dvc-on-windows.md

Add docs about pager in the pipeline command

---

static/docs/command-reference/remote/modify.md

Update documentation about new S3 remote options in [DVC PR#2931](https://github.com/iterative/dvc/pull/2931) and [DVC Issue#2930](https://github.com/iterative/dvc/issues/2930)
- `grant_read`
- `grant_read_acp`
- `grant_write_acp`
- `grant_full_control`

Docs about extended S3 remote support for custom ACL

---

static/docs/command-reference/run.md

Fixes https://github.com/iterative/dvc/issues/2843
Disregard the recommendations below if you use **Edit on Github** button to improve the docs in place.

run: add a clarification about --always-changed and "callback" DVC-files

---

public/static/docs/command-reference/repro.md
public/static/docs/user-guide/dvc-files-and-directories.md

docs: locking-related updates

---

public/static/docs/command-reference/remote/index.md

User complained that local one has `-d` but s3 doesn't.

remote: use `-d` in s3 example

---

src/Tooltip/index.js
src/styles.js

This fixes the problem with Tooltips being misplaced on Chrome when the text which shows the Tooltip is on the left hand side of a `<p>`.
This also fixes the annoying warnings from React that a `<div>` is being placed inside of a `<p>`, because now it's a `<span>`.
Note: Currently, if the tooltip is too long, it won't line-break. This PR does not change this, and It's probably a non-issue for now.
Fix #870

tooltip: do not use a div container for tooltips

---

public/static/docs/command-reference/remote/add.md

Related to https://github.com/iterative/dvc/pull/3016

gdrive: Shared drives support

---

public/static/docs/command-reference/get.md

Sorry for polluting with a branch, didn't notice before. It's a simple fix of fixing the repo `url` for `dvc get` example.

Fix `dvc get` example

---

public/static/docs/tutorials/deep/sharing-data.md

update pulling data from the cloud example by setting new target repository

update pulling data from the cloud example

---

public/static/docs/tutorials/deep/sharing-data.md

change target stage from default (Dvcfile) to evaluate.dvc due to repository change in example

update target stage in pulling data from the cloud example

---

public/static/docs/command-reference/remote/add.md
public/static/docs/command-reference/remote/modify.md

----------
related to https://github.com/iterative/dvc/pull/3200

remote: add description for verify option

---

public/static/docs/command-reference/add.md
public/static/docs/command-reference/fetch.md
public/static/docs/command-reference/get.md
public/static/docs/command-reference/import.md
public/static/docs/command-reference/metrics/show.md
public/static/docs/command-reference/pull.md
public/static/docs/command-reference/push.md
public/static/docs/command-reference/repro.md
public/static/docs/command-reference/run.md

cmd ref: get: document --show-url flag

---

yarn.lock

<s>The errors about the client pinging but the page not existing can only occur on the dev server. It shouldn't be running since `npm start` is setting the NODE_ENV to production, but still I added the NODE_ENV environment variable to app.json just to make sure heroku isn't running server.js raw.</s>
Updated yarn.lock
----------
🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This enables GitHub to link the PR to the corresponding bug and close it …

app: address some console errors

---

public/static/docs/command-reference/remote/add.md

Azure connection_string should be placed between (single) quotes to avoid command misprocessing.
Fix: #950

Update add.ml - add note for Azure connection-string

---

public/static/docs/command-reference/push.md

Noticed a missing space while reading the docs.
[used edit on github]

push: add missing space

---

next.config.js
package.json
pages/_app.js
pages/_document.js
yarn.lock

Test integration with Sentry. To make it work we need to add env variable `SENTRY_DSN` to Heroku.

Add sentry

---

next.config.js
package.json
pages/_app.js
pages/_document.js
yarn.lock

First attempt was reverted because of the bug, so this a new one for testing and debug.

Revert "Revert "Add sentry""

---

src/components/Documentation/SidebarMenu/index.js
src/components/Documentation/SidebarMenu/styles.js

As part of community page I updated `react-collapse` to version 5.0 and it so happens this version can be also used in side menu and is fixing some of our existing issues.
Fix #856 
Fix #724

Replace custom collapse in sidemenu

---

pages/community.js
src/components/Community/Learn/index.js
src/components/Community/Meet/index.js
src/components/Community/index.js
src/utils/api.js

Right now on community we fetch data from APIs inside `getInitialProps` it locks page render until we get all responses and also prevents us from caching renders results for this page as static html.
This PR moves these requests to the client side.

Move API calls on community page to client side

---

scripts/exclude-links.txt
src/utils/redirects.js
src/utils/redirects.test.js

This prevents an HTTPS redirect while testing with `yarn build && yarn start` on localhost.

redirects: do not redirect to HTTPS on localhost

---

public/static/docs/command-reference/gc.md
public/static/docs/user-guide/managing-external-data.md
src/components/Community/Contribute/index.js
src/components/Community/data.json

Regular updates (Feb 20)

---

public/static/docs/command-reference/remote/add.md
public/static/docs/command-reference/remote/modify.md
scripts/exclude-links.txt

remote: Document HTTP remote push changes

---

public/static/fonts/fonts.css

Since the font-size changed depending on the container, this is probably the text inflation algorithm.
Added a prefixed version because iOS needs it. The unprefixed version is there to avoid the text inflation algorithm on other browsers, and future versions of iOS.
Closes #125

fonts: prevent browser from changing font-size

---

public/static/docs/command-reference/add.md
public/static/docs/command-reference/checkout.md
public/static/docs/command-reference/commit.md
public/static/docs/command-reference/config.md
public/static/docs/command-reference/fetch.md
public/static/docs/command-reference/gc.md
public/static/docs/command-reference/get.md
public/static/docs/command-reference/import-url.md
public/static/docs/command-reference/import.md
public/static/docs/command-reference/metrics/diff.md
public/static/docs/command-reference/metrics/show.md
public/static/docs/command-reference/pull.md
public/static/docs/command-reference/push.md
public/static/docs/command-reference/remote/add.md
public/static/docs/command-reference/remove.md
public/static/docs/command-reference/repro.md
public/static/docs/command-reference/run.md
public/static/docs/command-reference/status.md

> Extracted from https://github.com/iterative/dvc.org/pull/908#pullrequestreview-356423629
> and https://github.com/iterative/dvc.org/pull/908#pullrequestreview-356423672

cmd ref: review option defaults and sentence priority per API params

---

src/components/Documentation/SidebarMenu/index.js

We were trying to update Perfect Scrollbar after 400ms timeout. If the was user already left the page it caused an error. Now we only update it if the ref to perfect scrollbar is sill present on page after timeout.
See:
https://sentry.io/organizations/iterative/issues/1529236771/
https://sentry.io/organizations/iterative/issues/1525523962/
And others like that.

Fix for 'update' of null error in Sentry

---

public/static/docs/command-reference/import.md
public/static/docs/command-reference/update.md
public/static/docs/use-cases/data-registries.md

cmd-ref: document --rev option on update

---

public/static/docs/api-reference/get_url.md

suggest some minor things to API

---

package.json
scripts/clear-cloudflare-cache.js
scripts/exclude-links.txt
server.js

Set some cache headers in dvc.org, such that we can set cloudflare to respect the headers it gets.
These headers are for instant invalidation, making the client validate against cloudflare, but preventing cloudflare from validating against the server. After each deploy, the cache is cleared.

deployment: set cache headers

---

public/static/docs/api-reference/index.md
public/static/docs/api-reference/open.md
public/static/docs/api-reference/read.md

> Extracted from https://github.com/iterative/dvc.org/pull/908#pullrequestreview-369254697
> super relevant example would to show SAX or StAX parser instead of a DOM one - that's where it shines. Or we can make CSV example the main one and show how we process it in steam fashion (e.g. calculating sum or avg) - it would show the "streaming" aspect of the open() way better.

api ref: better explanation on disc and memory usage for read/open

---

public/static/docs/command-reference/config.md
public/static/docs/command-reference/init.md

init: add subdir description

---

public/static/docs/command-reference/get.md
public/static/docs/command-reference/import.md
public/static/docs/command-reference/list.md
public/static/docs/sidebar.json

Follows https://github.com/iterative/dvc.org/pull/967
Relates:
- [Pull#2346](https://github.com/iterative/dvc/pull/3246)
- [Issue#2509](https://github.com/iterative/dvc/issues/2509)
<hr/> …

cmd ref: add list command

---

public/static/docs/command-reference/remote/modify.md

This commit adds some additional instructions to successfully set up a service account and configure a DVC command line remote that is pointing to a GCS bucket to use said service account. 
Its unclear to me if the remote setup needs the separate `GOOGLE_APPLICATION_CREDENTIALS` env call - but it worked here.
Fix #3005 …

Add service account information for GCloud

---

scripts/clear-cloudflare-cache.js

This ensures the CF tokens are available in production, otherwise the deployment fails.
closes #1048

deployment: require CF tokens

---

public/static/docs/command-reference/config.md
public/static/docs/command-reference/unprotect.md
public/static/docs/user-guide/large-dataset-optimization.md

https://github.com/iterative/dvc/pull/3472
Thank you for the contribution - we'll try to review it as soon as …

docs: protected mode is now enabled by-default

---

scripts/exclude-links.txt
scripts/link-check-git-all.sh
scripts/link-check-git-diff.sh
scripts/link-check.sh

tests: links: misc fixes

---

gatsby-config.js
gatsby-node.js
middleware/notFound/index.js
package.json
server.js
src/components/DocLayout/SidebarMenu/index.js
src/components/DocLayout/index.js
src/components/DocLayout/styles.js
src/components/Documentation/Markdown/index.js
src/components/Documentation/Markdown/styles.js
src/components/Documentation/RightPanel/index.js
src/components/Layout/index.js
src/components/SEO/index.js
src/components/SearchForm/index.js
src/components/SearchForm/styles.js
src/html.js
src/styles.js
src/utils/images.js
src/utils/resources.js
yarn.lock

Fixes related to issues that we got after migrating to Gatsby.js in [this PR](https://github.com/iterative/dvc.org/pull/1025)

[WIP] Gatsby migration fixes

---

src/components/Footer/index.js

Now discord link in the footer doesn't work. It happens because Gatsby.js don't know anything about `/chat` redirect in the server.js. I suggest open these links in the new tab as it is for the same links in the header.
But also I think that we should duplicate redirects on front side and I have plan to do this in the merging PR.

Open footer social links in the new tab

---

content/docs/command-reference/gc.md
content/docs/command-reference/install.md
content/docs/command-reference/metrics/add.md
content/docs/command-reference/metrics/remove.md
content/docs/command-reference/remove.md
content/docs/command-reference/root.md
content/docs/install/linux.md
content/docs/install/macos.md
content/docs/install/windows.md
content/docs/user-guide/contributing/docs.md
content/docs/user-guide/running-dvc-on-windows.md

- Address https://github.com/iterative/dvc/pull/3471#pullrequestreview-377170844
- Misc stuff

Regular updates (March 18)

---

content/docs/command-reference/version.md

`dvc version` output was adjusted for urgent debugging purposes and I didn't
send a doc update because it is terribly ugly right now anyway. Instead, I've
created https://github.com/iterative/dvc/issues/3499 to tackle that, but
@shcheklein reasonably requested a temporary doc update just for the
sake of it, so here we go.
🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is …

docs: version: update output

---

gatsby-node.js

On Windows it returns paths with backslashes https://github.com/iterative/dvc.org/pull/1109/commits/36ead01363386b7e9c9f204bc4a4c9483a3c61e3#diff-fda05457e393bada716f508859bfc604R57
But `node.fileAbsolutePath` contains path with normal slashes.

Fix build on Windows

---

content/docs/command-reference/import.md
content/docs/command-reference/update.md

cmd-ref: make changes related to update --rev

---

content/docs/command-reference/metrics/add.md
content/docs/command-reference/metrics/diff.md
content/docs/command-reference/metrics/index.md
content/docs/command-reference/metrics/modify.md
content/docs/command-reference/metrics/remove.md
content/docs/command-reference/metrics/show.md

Getting rid of TSV/CSV metrics formats. Part of https://github.com/iterative/dvc/issues/3409#issuecomment-605444643:
> 1. CSV/TSV types are specific to continuous metrics. There is no need to keep them in current, scalar ones. Let's get rid of CSV/TSV/HCSV/HTSV metrics format.

Get rid of CSV/TSV metrics

---

content/docs/command-reference/import.md
content/docs/command-reference/push.md
content/docs/command-reference/update.md
content/docs/command-reference/version.md
content/docs/sidebar.json
content/docs/use-cases/shared-development-server.md
content/docs/user-guide/managing-external-data.md

- Address https://github.com/iterative/dvc/pull/3566#pullrequestreview-388346381
- Address https://github.com/iterative/dvc.org/pull/1096#pullrequestreview-387865301 about `remote add -d`
- Review external data user guide and shared dev server use case to clarify shared/external cache concept
- Complement https://github.com/iterative/dvc.org/pull/1090#pullrequestreview-386203081 (import/update --rev changes)
- Misc. stuff

Regular updates (Apr 6)

---

content/docs/user-guide/setup-google-drive-remote.md

There was double remote name, so it didn't work.

Removed repeating 'myremote' remote name

---

content/docs/command-reference/run.md

docs: remove deprecated `--remove-outs`

---

scripts/deploy-with-s3.js
scripts/page-data-utils.js

This PR-for-a-PR does a few things for this branch
- Fixes a breaking issue where `path.join` was being called with `path`
- Runs S3 downloads and uploads in parallel
- Changes some grammar in the console logs to read more smoothly (I'm open to reverting this if I'm misunderstanding)

Rebuilds caching improvements

---

src/components/Documentation/Layout/SidebarMenu/styles.module.css

Fix #1143 
Ensure the icon for the sidebar links is rotated for active links
I traced the issue back to the the CSS modules migration https://github.com/iterative/dvc.org/pull/1106
Solution:
Nest the icon rotate CSS rule under the `.active` class, for it to take effect when the `.active` class is added
Before (all icons face down)
After (active icons face right)

Ensure icon on sidebar bullets is rotated when link is active

---

src/components/SubscribeSection/Form/index.tsx

[accessibility] add label to the subscribe from and hide it visually.

---

src/components/HamburgerMenu/styles.module.css

Fixes the following from  #1149

[accessibility] hide the mobile menu on desktop from keyboard users.

---

content/docs/command-reference/checkout.md
content/docs/command-reference/metrics/add.md
content/docs/command-reference/metrics/diff.md
content/docs/command-reference/metrics/modify.md
content/docs/command-reference/metrics/show.md
content/docs/user-guide/contributing/docs.md

- Address https://github.com/iterative/dvc.org/issues/1123#issuecomment-614929585
- Complete #1097 by removing mentions of `raw` metrics type
- Add --summary option to checkout cmd ref.

Regular updates (Apr 16)

---

src/templates/blog-post.tsx

I overlooked re-adding the page slug when the schema changed in the Models update. It's being destructured and defined, it just wasn't imported in GraphQL.
Fixes  #1178

Fix share buttons by importing slug via GraphQL

---

config/postcss/mixins.js
src/components/Blog/Feed/Item/styles.module.css
src/components/Blog/Post/Markdown/styles.module.css
src/components/Blog/Post/Share/styles.module.css
src/components/Community/styles.module.css
src/components/Documentation/Layout/SidebarMenu/index.tsx
src/components/Documentation/RightPanel/index.tsx
src/components/Documentation/styles.module.css
src/components/DownloadButton/index.tsx
src/components/Home/LandingHero/index.tsx
src/components/Home/LearnMore/index.tsx
src/components/LayoutHeader/Nav/index.tsx
src/components/LayoutHeader/Nav/styles.module.css
src/components/MainLayout/index.tsx
src/components/Page/base.css
src/components/Paginator/index.tsx
src/components/PromoSection/styles.module.css
src/components/PseudoButton/styles.module.css
src/components/SubscribeSection/Form/index.tsx
src/components/SubscribeSection/Form/styles.module.css
src/components/Support/styles.module.css
src/utils/front/accessibility.ts

This Pr addresses the following from #1149 
This is how it looks with the changes in place.
The dotted outline does not look pretty and provides no benefits to users that are using a mouse. So I have made sure that: 
- it only appears when the user is navigating via a keyboard.
- and if in the middle of Navigation let say the user swaps from using a keyboard to a mouse or vice versa for navigation then the handlers will be injected or ejected accordingly.

accessibility: add focus state styles to interactive elements

---

scripts/exclude-links-check.sh
scripts/exclude-links.txt
scripts/link-check-git-all.sh

```
ERROR:404:https://dvc.org/img/<filename>.gif
ERROR:404:https://dvc.org/uploads/images/2020-02-10/image.png
```
- ~~consider adding these (warnings) to exclusions?~~
```
WARNING:000:http://0.0.0.0:$
WARNING:000:http://$
```
- related #1189, #1169
Tip: run full test locally using `yarn link-check >> /dev/null` to only see errors (takes a few min, runs using 8 processes).

link-check: fix exclusions

---

scripts/link-check-git-all.sh

link-check: fix CI daily

---

content/docs/command-reference/remote/modify.md
content/docs/user-guide/setup-google-drive-remote.md

Corresponding core DVC PR https://github.com/iterative/dvc/pull/3686
-------- …

gdrive: add gdrive_user_credentials_file description

---

content/docs/command-reference/config.md

Fixes #1199. `core.loglevel` was removed from the available config options in https://github.com/iterative/dvc/pull/3321. This PR updates the documentation to remove any references to the deprecated configuration setting.

Remove reference to core.loglevel in docs

---

package.json

Fulfilling a simple request from #1084, up to the team whether to accept it or not.
I think this also finally fixes #1084, as Models seems to have enabled the sidebar to hot reload.
The last bit about clearing the cache comes from an understandable misconception, I believe. Clearing Gatsby's cache all the time would mean we need to spend ~10m transforming images each build- any HMR issues within Gatsby should be able to be solved without blowing away cache all the time when properly implemented.

Add a script in package.json enabling "yarn run dev"

---

package.json

Adding node_modules to cacheDirectories seems to download a more complete cache than the default behavior, despite the node buildpack docs saying node_modules are cached by default.
While out of the scope of a git PR, another part of reducing rebuild time on Heroku is setting the environment variable YARN_PRODUCTION to false so Heroku doesn't waste over a minute pruning devDependencies.
I tried just moving the Gatsby packages from devDependencies to dependencies, but it takes nearly as long to prune a minimal set of devDependencies as it does with all of them.
Even without pruning devDependencies we're way below the slug max, and I don't see it growing a few hundred MB any time soon. This will be even less of a problem once images are removed from the source repo, though if the images do …

Explicitly add node_modules to cacheDirectories for Heroku

---

src/components/Link/index.tsx

Basically, Gatsby Link is only for regular links within the site. We currently have a wrapper that chooses whether to use it or a raw `a` tag depending on if the link is within the site or not. This change adds a step to that check that filters out links that start with `mailto:`, making them work properly wherever this wrapper component is used, like the support page.
Fixes #1201

Make Link component recognize mailto links

---

src/gatsby/prune-cache.js
src/utils/shared/crawlPageData.js

I had some testing behavior in the cache pruner that logged file removals without
actually doing them using `&&` (`console.log` returns falsy). This would be fine if 
I had marked it in a TODO or any comment whatsoever.
Anyway, this commit fixes that.
I also changed the logic to use regular `fs` and `Promise.new` instead of
`fs.promises` to avoid the experimental warning. `upath` is used because
I believe that without it cache pruning won't work on Windows.

Fix and improve cache pruning

---

package.json
src/gatsby/utils/resolvers/index.js
yarn.lock

Ever since Models dropped, we use `path.join` to resolve links between files at build time (e.g. Blog Posts and Authors). I believe this is what's breaking Windows development, so I used a small module called `upath` that wraps the path API with cross-platform safe versions of functions like `join`.
`upath` is already installed by another module as you can see in `yarn.lock`, but the other package specifies an earlier version. The minimal size difference at build time and completely unchanged bundle size make it not worth pinning our usage to the same version, in my opinion.
Fixes #1204, or at least I think it does. It will before merging, at least.

Fix Windows development

---

content/docs/user-guide/dvc-files-and-directories.md

Per https://github.com/iterative/dvc/pull/3725 …

docs: update files/dirs for 1.0 release

---

scripts/utils.sh

- fixes https://github.com/iterative/dvc.org/pull/1226#issuecomment-623717893

link-check: ignore URLs preceded by `#`

---

.gitpod.yml
README.md
content/docs/user-guide/contributing/docs.md

Hi :slightly_smiling_face:
This Pr simplifies code contributions by fully automating the dev setup with Gitpod(a full-featured online cloud IDE) which is free for OSS. With a single click, it'll launch a workspace and automatically:
- clone the dvc.org repo.
- install the dependencies.
- run `yarn build`.
- start the webserver via `yarn start`.
so that anyone interested in contributing can start straight away without any friction.
this is how it looks:
You can give it a try on my fork of the repo via the following link:
https://gitpod.io/#https://github.com/nisarhassan12/dvc.org
A lot of popular OSS projects out there are already using Gitpod to streamline the experience for their contributors and maintainers, some of them are: 
- https://github.com/freeCodeCamp/freeCodeCamp
- …

simplify code contributions + reviews by fully automating the dev setup.

---

content/blog/2020-05-04-dvc-3-years-and-1-0-release.md

pip won't automatically upgrade …

blog: use pip install --upgrade for installing pre-release 1.0

---

content/docs/command-reference/run.md

Per https://github.com/iterative/dvc/pull/3729 …

docs: run: update --no-exec description

---

src/server/middleware/api/comments.js

I'm not certain that we should do this, but this is the fix for #1232. 
The cache could be at 15 minutes currently for a good reason (does @fabiosantoscode know?), but I'm not aware of any discourse cache limits, and we don't have an API key here so I can't see how it would track usage to do any throttling.
I personally think the comment count being delayed on the website isn't much of an issue that actually impacts users, but that's not for me to decide and this looks like a simple fix.
If somehow cache is living past the specified TTL, this deploy preview can still be useful considering its TTL is one minute as opposed to master's 15. I'm not familiar with Discourse and how to use it so I haven't run a test yet, but I can try it.

Change comment proxy cache TTL to 1 minute

---

content/blog/2020-05-04-dvc-3-years-and-1-0-release.md

- copy edits
- address https://github.com/iterative/dvc.org/pull/1213#pullrequestreview-405203972
- other misc. stuff

blog: improvements to 1.0 announcement

---

content/docs/user-guide/contributing/docs.md

This is a workaround to skip the automatic "external" icon appended to normal links in docs MD.
Fixes? #1246

Change gitpod button to HTML link

---

content/docs/command-reference/remote/add.md

When `dvc remote modify --local` is executed after `dvc remote add`, it shows the error `ERROR: configuration error - config file error: remote 'myremote' doesn't exists.`
This seems to be caused because the given `add` command writes to `.dvc/config` while the given `modify` command attempts to modify the remote in `.dvc/config.local`. 
This PR adds the missing `--local` option to the `add` command

Add missing --local option in Azure instructions

---

content/blog/2020-04-30-gsod-ideas-2020.md
content/docs/sidebar.json
redirects-list.json
src/components/Link/index.tsx
src/gatsby/models/docs/onCreateMarkdownContentNode.js
src/utils/shared/sidebar.js

Address #1073 partially
With some minor changes that allow a blank string slug in sidebar.json, this can be done without making the docs homepage a special exemption.
The existing redirect from /docs to /docs/home also had to be reversed.

Change "docs/home" to "docs"

---

content/blog/2020-04-06-april-20-dvc-heartbeat.md
src/components/Blog/Post/index.tsx
src/gatsby/models/blog/createPages.js

Also change existing links to tag pages to use this new format
Fixes #1222, disregarding the question about RSS because we don't currently use tags in the RSS feed. We could add them somehow, but that's another issue.

Change tag page paths to be under /blog

---

src/components/Link/index.tsx

Fixes #1140 as I understand it, but somebody please do check for possible regressions.
I can successfully do the following behavior:
> Click one the links from the right side content bar.
> 
> Click back in your browser.
> 
> The same should work and return to the exact link in the document you got the section.
I can't think of any behavior this change would break, as both the previous and current behavior only apply to fragment links within the same page (with the `href`'s first character being `#`), and other fragment links are left alone.
One thing to check, though, is the previous behavior of combining existing `rel` props with `noopener noreferrer` on all external links. The behavior I replaced it with only does so if the link is external and doesn't already specify a rel, as I …

Change how relative fragments are handled.

---

content/docs/command-reference/remote/modify.md

This is a leftover from old docs. We no longer recommend such URL format anywhere else (e.g. `dvc remote add`) …

docs: remote: azure: don't use obsoleted url format

---

src/utils/shared/sidebar.js

There was a hard-coded `/doc/` prepended to every path before, but now we start
with `/doc` and add a second slash only if something comes after.
This is a quick fix, but this problem stems from the `sidebar.json` setup still having influence in many places of the site. Ideally it should be _just_ be the canonical ToC and have nothing to do with link generation, but that's a problem for another time.
fixes #1264

Fix sidebar support for empty links (/doc/ trailing slash issue)

---

content/docs/command-reference/remote/modify.md

Add documentation for remote s3 sse_kms_key_id parameter

---

content/docs/command-reference/diff.md
content/docs/command-reference/metrics/diff.md
content/docs/command-reference/params/diff.md

doc: show-md on params/metrics diff

---

src/components/Documentation/Layout/SidebarMenu/index.tsx
src/components/Documentation/Layout/SidebarMenu/styles.module.css
src/components/Documentation/Layout/index.tsx

Fixes #808
There is some conflict in the mobile doc sidebar. Some root sidebar items have their own articles. When the user clicks to that item two things happen:
1. article opens
2. submenu in the sidebar collapsed
On mobile this cause problem because both logic can't be visible at the same time. I think a better way to solve the issue is to separate 1 and 2 logic to different clicks (ie need special UI element to collapse submenu). To do it need some other design for a mobile sidebar.
As a quick fix, I implement the following logic: the mobile doc sidebar doesn't close on navigating until leaf item is selected.

Fix mobile doc sidebar

---

content/docs/command-reference/install.md

As mentioned elsewhere in the page, the pre-push hook executes dvc push before git push. …

Correct dvc push and git push order

---

content/docs/command-reference/status.md

This PR updates `\static\docs\commands-reference\status.md` with `update available` output for import stages to fix #477.

cmd ref: describe `update available` output (for import stages) in `status` #477

---

.github/PULL_REQUEST_TEMPLATE.md

Changed <s>chose</s> to choose
I didn't open an issue since it's a minor change. 
You can see the mistake below in this template too.
Please chose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your …

Minor grammatical update in PULL_REQUEST_TEMPLATE

---

.gitignore
content/docs/api-reference/read.md
content/docs/command-reference/list.md
content/docs/install/index.md
content/docs/use-cases/data-registries.md
content/docs/user-guide/contributing/docs.md
package.json
plugins/gatsby-remark-dvc-linker/apiLinker.js
plugins/gatsby-remark-dvc-linker/commandLinker.js
plugins/gatsby-remark-dvc-linker/helpers.js
plugins/gatsby-remark-dvc-linker/index.js
plugins/gatsby-remark-dvc-linker/index.test.js
yarn.lock

docs: API auto-mentioning in docs (#910)

---

src/components/Documentation/Layout/index.tsx
src/components/Page/index.tsx
src/utils/shared/sidebar.js

This is partway through my work adding custom icons to the sidebar-
I noticed that the docs home currently doesn't have its entry highlighted when on the page. This branch fixes that, and is what I'll be building on top of in the `docs-sidebar-bullets` branch that tackles that issue. This branch is in case we want to fix this small issue now before I finish sidebar icons. Not that I expect it to take too long, but the changes may need more review than this logical midpoint.

Fix docs sidebar home highlight

---

src/components/Documentation/Layout/index.tsx
src/components/Page/index.tsx
src/utils/shared/sidebar.js

Fixes #1323 
I jumped the gun on switching from `props.location`, that's the right place to source path at build time.
I think we just had the `location` global somewhere on accident.

Fix docs sidebar highlight regression

---

content/docs/command-reference/init.md

A small fix for a broken link.  
Also, it must be pointed out that while [Issue#540](https://github.com/iterative/dvc.org/issues/540#issue-479205049) says:
> Git is the only SCM supported on DVC and probably will be for a long time. also, most of the docs use likely Git-specific language such as "tags" and "branches", as well as git ... commands in sample code blocks.
The command-reference says:
> Even though there are DVC features that require DVC to be run in the Git repo, DVC can work well with other version control systems.
Although the `--no-scm` usage is stated, it must be made clear that that particular non-Git repository should be a DVC repo. (Based on my understanding from the docs)
Something along these lines must be pointed out explicitly in within the [init section of …

'Installing DVC without Git' link fixed

---

src/components/Documentation/RightPanel/index.tsx
src/components/Documentation/RightPanel/styles.module.css

doc engine: fix scroll bar for the content sidebar

---

src/utils/shared/sidebar.js

Adds the new "style" and "icon" props to the example comment at the top of sidebar.js
Addresses comment from @jorgeorpinel [here](https://github.com/iterative/dvc.org/pull/1322/files/4a2083980d7aaa9ec4d31cda32f8842041a33185#r428951151)

Update inline comment doc on sidebar.js

---

content/docs/command-reference/import-url.md
content/docs/user-guide/external-dependencies.md

- Add a table entry for the URL format to make use of `dvc import-url` with Microsoft Azure Blob Storage.
- Add example for usage of Microsoft Azure Blob Storage with external dependencies.
> > You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.
> 
> ❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.
> 
> 🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.
> 
> Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing …

Add description for Azure url format

---

content/authors/dmitry_petrov.md
content/authors/elle_obrien.md
content/authors/george_vyshnya.md
content/authors/jorge_orpinel.md
content/authors/marcel_rd.md
content/authors/marija_ilic.md
content/authors/svetlana_grinchenko.md
content/docs/user-guide/contributing/blog.md
src/components/Blog/FeedMeta/index.tsx
src/components/Blog/Post/index.tsx
src/gatsby/models/authors/createSchemaCustomization.js
src/gatsby/models/authors/onCreateMarkdownContentNode.js
src/templates/blog-post.tsx

This is a quick addition to allow for optionally linking arbitrary pages to authors, making them clickable on Blog Posts.
Fixes #1161, and is an interim fix while we make something more elaborate in #1120
Just add `link: https://mysocialmedia.com/profile` to an author's Markdown frontmatter and that Author's name will become a link in Blog posts! I haven't committed any content changes yet, so we'll have to do that to have an example on display.
We'll probably need to add docs for this somewhere as well.

Add optional link field to authors

---

content/docs/command-reference/checkout.md

This PR updates `\content\docs\commands-reference\checkout.md` and `\content\docs\commands-reference\pull.md` to fix #528.
`checkout` example is simplified by using 'dvc fetch`. 
---
Some specific subtasks:
> dvc fetch could be hidden in the "Click and expand to setup the project"...
> fetch -aT is not currently used in the expandable section. The suggestion is to add it there so it can be removed from the block further down. There's an explanation about it under that block too, which would probably need to go away (moved into the expandable section too).
> However the fetch + checkout parenthesis would have to go away too (not moved, just gone). Instead maybe we can just link "fetch" and "checkout" in `We can now just run dvc pull that will fetch and checkout the...`

use example-get-started repo in pull examples 

---

content/docs/command-reference/import-url.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/index.md
content/docs/command-reference/remote/list.md
content/docs/tutorials/get-started/add-files.md
content/docs/tutorials/get-started/configure.md
content/docs/tutorials/pipelines.md
content/docs/tutorials/versioning.md
content/docs/user-guide/basic-concepts/dvc-project.md

Having `abbr`s in `details` used to break them, leading to #510. 
At some point since then, the issue was fixed and `abbr` works within `details` with no problem, even in quotes.
This branch re-adds the `abbr`s removed in #510.
I think this also fixes #510, unless I missed something from the list or there are other docs to re-introduce this to.
Uses the list from [this comment](https://github.com/iterative/dvc.org/issues/510#issuecomment-520898641)

Re-add abbrs within details

---

content/docs/command-reference/import.md

Additional, final fix #898  
Specific addition: [#898(comment)](https://github.com/iterative/dvc.org/issues/898#issuecomment-632894650)
Please check the link of the non-DVC git repository. I couldn't find any non-DVC repo in iterative that could provide for a dataset file. In case of any modifications, I would be happy to make changes to the link.  

cmd ref: import - support for non-DVC repos

---

gatsby-config.js
package.json
scripts/deploy-with-s3.js
scripts/exclude-links.txt
scripts/s3-utils.js
src/components/Home/LandingHero/GithubLine/index.tsx
src/gatsby/hooks/stars.ts
src/gatsby/models.js
src/gatsby/models/authors/onCreateMarkdownContentNode.js
src/gatsby/models/github/index.js
src/server/index.js
src/server/middleware/api/github.js
src/server/middleware/api/index.js
src/utils/front/api.ts
yarn.lock

- Uses `gatsby-source-github-api` to get GitHub data at build time
- Splits the GitHub Issues proxy API into one for Issues and Stars, sharing the
query data. The new endpoint is `/api/github/stars`.
- Updates the GithubLine component to display the build-time value at first, then update
via the proxy as soon as possible to reflect any changes. If the value hasn't 
changed or there was an error, the component keeps the static value.
Fixes #1019

Overhaul how GitHub stars are handled

---

content/docs/command-reference/commit.md

Fixes this:
> From https://dvc.org/doc/command-reference/commit …

hotfix: fix commit desc (broken tooltip)

---

content/docs/install/completion.md

install: completion: update to new method

---

content/blog/2020-06-22-dvc-1-0-release.md

Reading through and noticed a few minor typos in the 1.0 blog post.
[Diff ignoring whitespace](https://github.com/iterative/dvc.org/pull/1477/files?w=1)

blog: 1.0 copyediting

---

content/docs/command-reference/run.md

Per https://github.com/iterative/dvc/pull/4086 …

docs: run: remove --file

---

content/docs/command-reference/fetch.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md

Related to https://github.com/iterative/dvc.org/issues/1289
Per https://github.com/iterative/dvc/pull/4087 …

docs: add --run-cache for fetch/pull/push

---

content/docs/command-reference/freeze.md

freeze: convert to 1.0

---

content/docs/command-reference/dag.md
content/docs/command-reference/push.md
content/docs/user-guide/running-dvc-on-windows.md
redirects-list.json

cmd ref: more updates on new dag command

---

content/docs/command-reference/remove.md

Fixes #1490 
* `dvc remove` description updated according to implementation (see https://github.com/iterative/dvc/issues/4094 for context)
* `--outs` description updated according to implementation.
* `.gitignore` described in examples.
* Removed extra params: `-p`, `-f`.
* Removed shorthand for `--outs` (i.e. `-o`).
* Updated command description.

remove: updated to match with core repo

---

src/components/Community/Section/index.tsx
src/components/Documentation/Layout/SidebarMenu/index.tsx
src/components/Home/UseCases/CollapsibleText/index.tsx

Fix #1240 
Currently, there is no way to implement it efficiently without a wrapper (https://github.com/nkbt/react-collapse/issues/255). There is an ancient pending PR (https://github.com/nkbt/react-collapse/pull/262) that tries to fix it, but it is about the `aria-hidden` attribute, so the tab navigation would be still broken even (if?) after the merge. I suggest living with this wrapper approach.

docs: skipping hidden sidebar items

---

content/docs/command-reference/remove.md

per https://github.com/iterative/dvc.org/pull/1497#issuecomment-650111941 …

cmd: add stage example to remove

---

content/docs/use-cases/versioning-data-and-model-files/tutorial.md

The following PR completes the below subtask from #1445. 
> versioning use case tutorial

term : remove "Dvcfile" from versioning use case tutorial

---

src/components/LayoutHeader/index.tsx
src/components/LayoutHeader/styles.module.css

I'm sure we'll want changes to the text and color, but here's the implementation!
The current implementation is a simple div placed above the header, which collapses to zero height whenever the header collapses. This behavior can also be changed, especially if it has problems on corner cases.

Add an alert box above the header to advertise CML

---

content/docs/start/data-pipelines.md

Hello!
[edited]
This pull request changes the virtual virtual environment link from [python tutorials](https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments) to [python docs](https://python.readthedocs.io/en/stable/library/venv.html). 
The tutorials page has some text before getting to the command itself, the docs page is more straightforward so the user can paste the code get back to DVC guides :)

docs: add intruction to create virtualenv

---

content/docs/command-reference/commit.md
content/docs/command-reference/import-url.md
content/docs/command-reference/install.md
content/docs/install/linux.md
content/docs/install/macos.md
content/docs/install/pre-release.md
content/docs/use-cases/versioning-data-and-model-files/tutorial.md
content/docs/user-guide/contributing/core.md

per https://github.com/iterative/dvc.org/pull/1553#pullrequestreview-446606985 …

docs: update virtualenv links

---

gatsby-node.js
src/gatsby/models.js
src/gatsby/models/prune-cache/index.js

Fixes #1405, which I've confirmed is a cache issue with local testing.
We totally have a tool that prunes cache to solve that, I must have accidentally broken the invocation earlier before starting work on the CML site.
This PR turns the weird function-but-not-model pruner into a model like the other pieces of `gatsby-node` logic we use, both cleaning it up and fixing the invocation.

Fix cache pruning

---

content/docs/command-reference/plots/diff.md

Fixes #1425 
Continuation of #1544 
@jorgeorpinel @pared I have included possible uses cases in the note

Adding a note on dvc plots diff --targets with revisions usage

---

content/docs/command-reference/plots/diff.md

Changes as described in https://github.com/iterative/dvc.org/pull/1549#discussion_r453220288 and https://github.com/iterative/dvc.org/pull/1549#discussion_r453220364

Modifying note on dvc plots diff --targets with revisions usage

---

content/docs/command-reference/remove.md

cmd ref: remove: mention removing of dvc.yaml and dvc.lock

---

content/docs/command-reference/list.md
content/docs/command-reference/params/index.md

Fixes wrong code blocks.
UPDATE: A remaining code block fix will be done in #1384

cmd: hotfix fetch and params

---

gatsby-node.js
package.json
scripts/clear-cloudflare-cache.js
scripts/deploy-with-s3.js
src/gatsby/models/github/index.js

This PR was made to help diagnose the CloudFlare cache purge issue we've been having, though Review Apps don't actually have CloudFlare credentials.
The changes of this PR move the CloudFlare cache cleaning logic into a regular Node module instead of a CLI-invoked script. This module is then used at the end of the deploy script. Effectively, this moves the CloudFlare cache clean to "the end of the deploy phase" as opposed to "the start of the runtime process".
As I understand it, this effectively doesn't change anything except for logs. The log changes, however, mean that the CloudFlare script outputs in the build logs instead of the runtime logs- this is good because runtime logs expire without add-ons, but build-time logs last forever by default.
You can see in the Deploy Preview for …

Improve CloudFlare cache clear logging and GitHub Stars bugfix

---

gatsby-node.js
package.json
scripts/clear-cloudflare-cache.js
scripts/deploy-with-s3.js
src/gatsby/models/github/index.js

This is the same PR as before, but with a slight change to fix the server invocation.
This time I'll confirm the review app before I suggest a merge.

Improve CloudFlare cache cleaner logging + Stars bugfix (second attempt)

---

content/docs/command-reference/remote/modify.md

https://github.com/iterative/dvc/pull/4224

S3 access_key_id & secret_access_key args

---

content/docs/command-reference/add.md
content/docs/command-reference/unprotect.md

#1255: Reviewed all the dvc add examples throughout docs. This issue is mentioned under **Next priorities** on GitHub.

Review all dvc add examples throughout docs #1255

---

src/components/Documentation/Markdown/styles.module.css

In this PR, external links (ones with `_target="blank"` specifically) have `white-space: nowrap` applied to them such that the link itself will not break on a line, including the external link icon. This fixes #1593.
Also, image links in docs no longer display the external link icon to fix #1594.

External link icon fixes

---

src/components/Blog/Post/styles.module.css

Most noticeable in [this blog post](https://dvc.org/blog/shtab-completion-release), `descriptionLong` doesn't have any styles for `code` blocks. However, the `code` blocks are still present, so we just need to style them.
This PR does that. See how it looks in the [deploy preview](https://dvc-landing-description-ae1pr8.herokuapp.com/blog/shtab-completion-release)!
I don't know if we already have an issue for this, feel free to let me know and I'll link it.
Since the style is a simple CSS rule, it can be changed to anything if we think another style would look better here. Currently, I just copy the rule used in docs.

Add style for descriptionLong code blocks.

---

src/components/Blog/Post/Markdown/styles.module.css

This PR makes it so that plain `img` elements with captions are properly styled, as the previous rules only applied to images wrapped with `gatsby-image`, which are divs with a specific class.
I just took the relevant bits from the current selector and moved them into a new one that selects both `img` and the `gatsby-image` divs.
Example of the issue in the last few images of [this post](https://dvc.org/blog/shtab-completion-release).
[Here's the same blog post, but on this PR's preview](https://dvc-landing-img-caption-zfazra.herokuapp.com/blog/shtab-completion-release)

Make image caption styling apply to plain `img`s

---

content/docs/command-reference/commit.md
content/docs/command-reference/fetch.md
content/docs/command-reference/freeze.md
content/docs/command-reference/import-url.md
content/docs/command-reference/index.md
content/docs/command-reference/install.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/repro.md
content/docs/command-reference/run.md
content/docs/command-reference/status.md
content/docs/use-cases/shared-development-server.md
content/docs/use-cases/versioning-data-and-model-files/tutorial.md
content/docs/user-guide/dvcignore.md
content/docs/user-guide/what-is-dvc/collaboration-issues.md
content/docs/user-guide/what-is-dvc/core-features.md
content/docs/user-guide/what-is-dvc/index.md

---
- Continuation of https://github.com/iterative/dvc.org/pull/1383#issuecomment-648363086
- One of the *Next Priorities* in DVC 1.x discrepancies #1255:
~~Line 169 in `repro.md` links to `/doc/tutorial/dags` and previously linked to `/doc/tutorial/pipelines`. Both these links just redirect to `doc/start`. Maybe they should have a different link (`/doc/start/data-pipelines`)?~~

pipeline: links and examples update for 1.x

---

content/docs/command-reference/push.md

Close #1445 by addressing the last pending checkbox:

cmd: update push deps example

---

content/docs/command-reference/root.md

Updates motivation and examples. See issue #404.

Update dvc root command reference motivation and examples

---

src/components/ThankYou/index.tsx
src/components/ThankYou/styles.module.css
src/pages/subscriber-thank-you.tsx

This PR adds a simple "Thank You" page for MailChimp to redirect to upon a successful subscription.
Hosting this page ourselves gives us more control over the page in general, but a specific issue brought this up:
Having one Audience for CML and DVC is easier to manage, but there can only be one embedded form per Audience. This is fine for the most part, except that the "return to website" button on the "Thank you" page "returns" to dvc.org even if you got there via cml.dev! Even worse, we can't just remove the thank you button in MailChimp's provided editor!
Thankfully, we *can* redirect to a custom page, which is where this PR comes in.
I fully expect the text to be changed, and maybe we want return links to both DVC and CML to make up for the fact that the page can't change between …

Add a "Thank You" page for MailChimp subscribers

---

content/docs/use-cases/versioning-data-and-model-files/tutorial.md

Re-close #1615 
Specifically https://github.com/iterative/dvc.org/issues/1507#issuecomment-662913116:
> Removing the model.h5.dvc file and re-running the updated tutorial runs successfully! ...
Perhaps it would be clearer if the documentation re-stated this before the Automating capturing section.

[hotfix] cases: fix Automating capturing section of versioning tutorial

---

content/docs/command-reference/import.md

import: clarify -o behavior for subdirectories

---

content/docs/command-reference/get.md
content/docs/command-reference/import.md
content/docs/command-reference/init.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/modify.md
content/docs/user-guide/dvcignore.md

- Copy edits in most files (including around init --subdir, from #1664)
- Fix up remote add/modify terminology and code block examples (rel #1617)

docs: misc updates

---

content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/modify.md

This adds the documentation of configuration parameters for my proposed addition of WebDAV remotes.
Relates to iterative/dvc#1153, https://github.com/iterative/dvc/pull/4256
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch …

cmd: add parameters for configuration of WebDAV remotes

---

content/docs/user-guide/troubleshooting.md

Here is a draft to document a common issue, with the goal to link here from an error message (https://github.com/iterative/dvc/pull/4339) Any feedback is appreciated.
Fixes #1660
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-b …

troubleshooting: mention missing files

---

content/blog/2017-07-27-data-version-control-in-analytics-devops-paradigm.md
content/blog/2017-08-23-ml-model-ensembling-with-fast-iterations.md

In line with @dmpetrov's PR to make a page title gender neutral, I made a quick search on the repository and found "his/her", which should be changed to "they" to be more inclusive.
----
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-r …

use gender-neutral they instead of his/her

---

content/docs/start/data-versioning.md

Create "data" folder, otherwise `dvc get` throws an error

docs: create data folder before running "dvc get" command

---

content/docs/user-guide/external-dependencies.md

Copy and paste files without the addition of the backslash on first line. …

Adding missing backslash in `dvc run` commands

---

content/docs/command-reference/status.md

Fix #1701 and minor formatting changes for `dvc status` command reference. …

cmd: missing state

---

content/docs/user-guide/external-dependencies.md
plugins/gatsby-remark-dvc-linker/simpleLinker.js
src/components/Documentation/Markdown/index.tsx
src/gatsby/models/github/index.js

Before, as pointed out [here](https://github.com/iterative/dvc.org/pull/1735#discussion_r479549491) by @jorgeorpinel, any markup like code quotes would break a header as only the first child
had its text extracted. Now, the `Collapsible` uses the whole `children` value of the
header it's made from as the `trigger` text, so anything that can go in a heading can go in a `details` `trigger`.
`simpleLinker` is also changed to not apply to code quotes within headings, partially because of this and also because auto-links in headers feels like it clutters the UX a bit since the same contents will very likely be linked in the following paragraph. I can re-enable this behavior if we find it desirable.

Fix details triggers that contain markup

---

.eslintrc.json

This effectively makes commits with an unused variable blocked, fixes #1291

Rule change for ESLint to error on unused variables.

---

content/docs/api-reference/read.md

(rant starts)
Feels like the `dvc.api` could be better overall (it's written in a man-page style instead of easy to use, gets-out-of-way reference.
The block that tries to show the function signature is split into multiple lines and has a `def` in front of them.
Formatting is also broken in many places and seems that there's too much information than there should be for what's it meant to be very simple APIs.
Another issue, I noticed is that we have too many exceptions for `dvc.api`. Not a documentation issue, but docs do reflect the issue on the core side.
(rant ends)
Just fixing a typo/mistake on `dvc.api.read()`. :slightly_smiling_face:

s/open/read in dvc.api.read reference

---

content/docs/user-guide/troubleshooting.md

Updated according to suggestion in following pull request: https://github.com/iterative/dvc/pull/4479
Added section on case when dvc unable to detect cache type.
Fixes: https://github.com/iterative/dvc/pull/4479
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/all …

troubleshooting: add cache types entries

---

scripts/clear-cloudflare-cache.js

I noticed [this prod build](https://dashboard.heroku.com/apps/dvc-org/activity/builds/adcf40cc-7eaa-44cc-8d2e-ba8327fef2a3) that failed on the CloudFlare clear yesterday, seemingly on a non-JSON response. My hypothesis is that CloudFlare returns some errors like Auth as plain HTTP codes while others are encoded in the `errors` property of a json blob in the body.
This PR allows us to recognize and throw on the former before attempting a JSON conversion, and thus providing more info on the error.

Handle non-JSON non-ok responses from CloudFlare cache clear

---

content/docs/command-reference/remote/modify.md

Concerns:
https://github.com/iterative/dvc/pull/4553 …

describe the HTTP method config

---

content/docs/command-reference/dag.md
content/docs/command-reference/freeze.md
content/docs/command-reference/install.md
content/docs/command-reference/unfreeze.md
content/docs/install/completion.md

Found in review for #1743. Replaced out-of-date `dvc repro` stage file example with `dvc plots` completion example.

docs: replace stage file example in /install/completion, fix typos found in review

---

content/docs/start/data-pipelines.md

The `diff` notation breaks the tree visualization in this quote block.

docs: fix non-intuitive diff offset formatting in start/data-pipelines.md

---

content/docs/api-reference/get_url.md
content/docs/api-reference/open.md
content/docs/api-reference/read.md

We added support for subrepos in https://github.com/iterative/dvc/pull/4465, due to which it made `UrlNotDvcRepoError` invalid and imprecise. So, we made a _breaking change_ for the exceptions raised.
There's a lot of things that are wrong with exceptions for `dvc.api`, which I don't want to fix them here but on the core side (raise `ApiError` everywhere, perhaps?).
🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub …

Remove UrlNotDvcRepoError from exc for dvc.api

---

.github/workflows/link-check-deploy.yml

It will never check any links because we're comparing to master.
Also, this change provides a convenient excuse to test the deploy check on a new PR!

Skip running deploy check on master.

---

.github/workflows/link-check-deploy.yml

Turns out `branches-ignore` syntax didn't work on `deployment_status`, as seen [here](https://github.com/iterative/dvc.org/actions/runs/266344304)

No deploy check on master

---

README.md

I didn't think the long workflow name would also reflect in the badge. We may want to rename the workflow to make the badge look better, as it doesn't seem to be configurable otherwise.
We can also use this branch for fixes for existing links, as adding the badge while failing may not be a good look.
Check out how it looks [on this branch's README](https://github.com/iterative/dvc.org/tree/link-check-status-badge#readme)

Add Link Check status badge to README

---

README.md

This PR simply adds a link around the Link Check badge in the README to the GitHub Action results of the action it's related to.

Add href to Link Check action results on README badge

---

content/docs/command-reference/import.md

This is documentation update for https://github.com/iterative/dvc/pull/4622. …

import: add '--file' option

---

content/docs/command-reference/remove.md
content/docs/command-reference/unprotect.md
content/docs/user-guide/large-dataset-optimization.md

per https://github.com/iterative/dvc.org/runs/1179565776

docs: update bad undo-add links

---

.github/workflows/link-check-all.yml
.github/workflows/link-check-deploy.yml
config/link-check/config.yml
package.json
yarn.lock

Bump link check version to 0.7, with changes to the GET->HEAD retry system such that any failure on HEAD is retried with GET (previously this only happened on 405)
Also, this PR changes the GitHub link settings pattern to include the apex domain (github.com as opposed to www.github.com or api.github.com).

Link check upgrade

---

content/docs/command-reference/remote/modify.md

This parameter was created per iterative/dvc/issues/4186 (for https://github.com/iterative/dvc/issues/4186)

remote modify [ssh]: Add doc about the parameter 'allow_agent'

---

content/docs/command-reference/repro.md

Per https://github.com/iterative/dvc/pull/4538 …

docs: repro: add --pull

---

content/docs/command-reference/params/index.md
content/docs/command-reference/run.md
content/docs/start/experiments.md
content/docs/user-guide/basic-concepts/parameter.md
content/docs/user-guide/dvc-files-and-directories.md

Related to https://github.com/iterative/dvc/pull/4456

add example with python parameters file

---

content/docs/sidebar.json
package.json
src/utils/shared/sidebar.js
yarn.lock

Before, we used lodash startCase which simply made every word have its first
letter capitalized. This new function does title case (leaving 'and', 'or', etc.
uncapitalized) and also capitalizes "dvc"
Initially mentioned [here](https://github.com/iterative/dvc.org/pull/1840#discussion_r500466702)

Use modified Title Case for slug -> label conversion.

---

content/docs/use-cases/index.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/use-cases/versioning-data-and-model-files/tutorial.md
content/docs/user-guide/setup-google-drive-remote.md
content/docs/user-guide/what-is-dvc.md

Based on existing search results, I expanded the use case intro docs with data and model versioning references. The tutorial received similar changes — pending review with @jorgeorpinel.
Merged PR #1805 (meant to separate commits but I messed it up 😒).
**/docs/user-guide/what-is-dvc.md**
Add explicit "machine learning" references including "version machine learning experiments"
**/docs/use-cases/index.md**
Add "data science use cases", "tools" and "best practices"
**/docs/use-cases/versioning-data-and-model-files/index.md**
Add "data and model versioning", "versioning (large) data files", and "model versions"
**/docs/use-cases/versioning-data-and-model-files/tutorial.md**
Add "ML model versions", "dataset versioning", "model and large dataset versioning", "machine learning models", …

docs: add key terms to use case intros/tutorial and what is dvc? docs [SEO]

---

redirects-list.json

As discussed with @jorgeorpinel to address the redirect problem in #1823 and #1705.
If this redirect is applied soon, the existing index ranking for the old URL should be transferred to the new one, even though the change was made some time ago. This is the [existing index listing for the old URL](https://www.google.com/search?client=safari&rls=en&sxsrf=ALeKk01Bsc_mAQ8KJircq8gRouuCtIqMFg%3A1602146894471&ei=TtJ-X4uaHKqorgTdxqiQCA&q=info%3Ahttps%3A%2F%2Fdvc.org%2Fdoc%2Fuser-guide%2Fupdating-tracked-files&oq=info%3Ahttps%3A%2F%2Fdvc.org%2Fdoc%2Fuser-guide%2Fupdating-tracked-files&gs_lcp=CgZwc3ktYWIQAzoECAAQR1DhEVjaEmDXFWgAcAJ4AIABlgGIAYcCkgEDMC4ymAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwiL-ZakzqTsAhUqlIsKHV0jCoIQ4dUDCAw&uact=5).
When this PR is merged, I'll reindex the old URL …

docs: add redirect for How To: Update Tracked Files

---

content/docs/start/index.md
src/gatsby/models/docs/createSchemaCustomization.js
src/gatsby/models/docs/onCreateMarkdownContentNode.js
src/templates/doc.tsx

This PR adds the ability to use `description` and `title` frontmatter fields to override the SEO description and title of any docs page, in the same way as the Blog pages.
Since the Blog and Docs use the same SEO component, all the same SEO tags are used. If either is not provided, the page will fall back on the same SEO title and description it had before.
Fixes #1785 
Can be verified on the deploy preview with test data [here](https://dvc-landing-docs-descri-ytzq28.herokuapp.com/doc/start). I'll remove it before merge.

Add ability to override SEO description in docs pages

---

content/docs/command-reference/version.md

Fixes #1635 
- Updates `version` ref.

cmd: update version ref.

---

content/docs/start/index.md

**Meta description**
Added a custom meta description to the front matter. This doc commonly appears in results next to the Tutorial (shown below in results for "dvc tutorial"). In addition to normal benefits, a custom description will help users differentiate between the two (hopefully reducing bounces for both).
**Key term**
Added "machine learning" in two usages: one as "machine learning model" and another as "git for machine learning".
**Typos**
Fixed two typos that I came across incidentally.

start: add meta description, 'machine learning' term (index) [SEO]

---

content/docs/command-reference/plots/diff.md
content/docs/command-reference/plots/show.md

plots and metrics: update new targets rules

---

content/docs/use-cases/versioning-data-and-model-files/tutorial.md

The data versioning tutorial has good placement in [search results](https://www.google.com/search?q=dataset+versioning) for key terms like "versioning data" and "dataset versioning". The results for this page typically show the default dvc.org meta description, and the title is limited to "Tutorial".
A unique description that matches the page content can increase clickthrough and reduce bounce (leading to better search ranking). Pages that include the search terms in their title typically rank better on those terms.
This PR adds a custom meta description and expands the meta title to "Tutorial: Data & Model Versioning".

cases: add custom meta title and meta description to (data versioning tutorial) [SEO]

---

content/docs/command-reference/cache/dir.md

Updated doc for 'dvc cache dir' according to pull request [#4613](https://github.com/iterative/dvc/pull/4613)
- Updated the help section of `dvc cache dir` command.
- Added an example to print the current cache directory path with `dvc cache dir` command. (This may need modification).
Signed-off-by: Girish Joshi <girish946@gmail.com>
🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when …

Updated doc for 'dvc cache dir' according to pull request #4613

---

content/docs/start/data-pipelines.md

**Meta title**
Added a custom title to prefix title with "Get Started:" in search result. Edited page H1 to match. Suggest using this pattern for all Get Started items and Tutorial. Adding prefixes like this should improve clickthrough and reduce bounce by clearly showing the result is a "Get Started" article (or Tutorial, in that case) as opposed to command reference, etc. 
**Meta description**
Added a custom meta description to the front matter with overview and key terms. 
**Key term**
Added second paragraph to expand on use cases and add "machine learning pipelines".
This page doesn't rank on the first page for either "data pipelines" or "machine learning pipelines". The intent of these changes is to improve placement for "machine learning pipelines". Current results for that term …

start: add meta title, description and key term (data pipelines) [SEO]

---

content/docs/use-cases/versioning-data-and-model-files/tutorial.md

Reapplies "Tutorial:" prefix to meta title and H1, as discussed in #1856.
Also fixes typo: "...reading **the** François' tutorial itself." -> "...reading François' tutorial itself."

cases: reapply custom meta title and h1 format (data versioning tutorial) [SEO]

---

src/components/Documentation/Markdown/styles.module.css

This fixes #1910, but I'm not sure what this rule was created for so it may have caused an issue with something else. That said, we have a selector specifically for images so we can be sure that isn't the case.

Remove CSS line break on em in p following highlights

---

content/docs/command-reference/metrics/index.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/params/diff.md

Updates metrics show and Plots diff example as per 1.0

---

content/docs/command-reference/repro.md

Fixes link position and formatting left over from #1915.

docs: move getting started link to top of examples section, make md blockquote

---

content/docs/command-reference/config.md
content/docs/command-reference/fetch.md
content/docs/command-reference/gc.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/remote/modify.md
content/docs/command-reference/status.md

Per iterative/dvc/pull/4872 (rel iterative/dvc/issues/4504) …

4504: Existence of the configuration option explained

---

content/docs/user-guide/dvc-files-and-directories.md

From https://github.com/iterative/dvc.org/pull/1907 …

docs: missed adjustments for size/nfiles fields

---

content/docs/command-reference/config.md
content/docs/user-guide/managing-external-data.md

~~Related to iterative/dvc#4878~~
Closes #1934 - We never supported external outputs for Azure.
The supported remotes can be derived from current state of [outs](https://github.com/iterative/dvc/tree/1.9.1/dvc/output).

external outs: remove azure support

---

content/docs/command-reference/diff.md

Updates examples that were out of date with latest DVC version and example repo. Also fixed a typo `a_ref` -> `a_rev`. Addresses this cmd for #1743.

cmd: update diff examples for dvc 1.0

---

content/docs/command-reference/add.md
content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/run.md
content/docs/user-guide/dvc-files-and-directories.md

Per https://github.com/iterative/dvc/pull/4901 …

docs: add desc field

---

content/docs/sidebar.json
content/docs/user-guide/how-to/add-deps-or-outs-to-a-stage.md
content/docs/user-guide/how-to/merge-conflicts.md
content/docs/user-guide/how-to/stop-tracking-data.md
content/docs/user-guide/how-to/update-tracked-data.md
redirects-list.json

> Continues https://github.com/iterative/dvc.org/pull/1914#pullrequestreview-540149852
- Put Merge Conflicts in
- Rename Update Tracked Files->Data
- Update SEO info.
- Add corresponding redirects
- Minor copy edits

how-to: further improvements

---

content/docs/command-reference/plots/diff.md
content/docs/command-reference/plots/index.md

Per https://github.com/iterative/dvc.org/issues/1414#issuecomment-730093511:
> Update the description of <DVC_METRIC_Y> to specify only the first row matters
> Update the text in the plots index description 
Per https://github.com/iterative/dvc.org/issues/1414#issuecomment-731027131
> let's just double check that all other metrics and plots usage blocks correspond to the -h help output of the commands on the latest DVC version (1.9.1)

cmd: Updating description of <DVC_METRIC_Y> in plots

---

content/docs/command-reference/params/diff.md

Related to iterative/dvc#4446 and iterative/dvc#5122.
Introduce description for new `params` option: `--targets`.

params: document --targets option

---

content/docs/user-guide/dvc-files-and-directories.md

Per https://github.com/iterative/dvc/pull/5061 …

[2.0] dvc.yaml: doc isexec field

---

content/blog/2019-04-23-dvc-project-ideas-for-google-summer-of-docs-2019.md
content/blog/2019-11-05-october-19-dvc-heartbeat.md
content/blog/2020-04-16-april-20-community-gems.md
content/blog/2020-05-26-may-20-community-gems.md
content/blog/2020-06-29-june-20-community-gems.md
content/blog/2020-11-25-november-20-community-gems.md
content/docs/api-reference/get_url.md
content/docs/command-reference/add.md
content/docs/command-reference/cache/dir.md
content/docs/command-reference/cache/index.md
content/docs/command-reference/config.md
content/docs/command-reference/fetch.md
content/docs/command-reference/gc.md
content/docs/command-reference/init.md
content/docs/command-reference/push.md
content/docs/command-reference/run.md
content/docs/sidebar.json
content/docs/start/index.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/user-guide/basic-concepts/dvc-cache.md
content/docs/user-guide/dvc-files.md
content/docs/user-guide/dvc-internals.md
content/docs/user-guide/dvcignore.md
content/linked-terms.js
redirects-list.json

Also includes
- Separate **Outputs** and **Dependencies** sections in **DVC Files** guide
Next up:
- Review "metafile" terminology.
- Introduce basics from https://github.com/iterative/dvc/wiki/Parametrization to the **DVC Files** guide
- Further split **DVC Files** into separate pages?

guide: split DVC Files/Internals (prep for dvc.yaml 2.0 updates)

---

content/blog/2020-04-16-april-20-community-gems.md
content/docs/command-reference/config.md
content/docs/command-reference/destroy.md
content/docs/command-reference/init.md
content/docs/command-reference/install.md
content/docs/command-reference/list.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/remote/modify.md
content/docs/command-reference/status.md
content/docs/install/plugins.md
content/docs/start/data-versioning.md
content/docs/use-cases/data-registries.md
content/docs/use-cases/sharing-data-and-model-files.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/use-cases/versioning-data-and-model-files/tutorial.md
content/docs/user-guide/basic-concepts/dvc-project.md
content/docs/user-guide/contributing/docs.md
content/docs/user-guide/dvc-files.md
content/docs/user-guide/how-to/merge-conflicts.md
content/docs/user-guide/large-dataset-optimization.md
content/docs/user-guide/related-technologies.md
content/docs/user-guide/what-is-dvc.md

> Continues #2043
- Review all existing links to these guides
- Review all instanced of "metafile" term: only left in key places
- Remove some old instances of "DVC-file" along the way
^ Finishing that requires a separate PR (per #1366).

guide: update old links to DVC Files and review related terms (prep for dvc.yaml 2.0)

---

content/blog/2020-04-16-april-20-community-gems.md
content/blog/2020-06-22-dvc-1-0-release.md
content/blog/2020-07-22-july-20-community-gems.md
content/docs/command-reference/config.md
content/docs/command-reference/destroy.md
content/docs/command-reference/import.md
content/docs/command-reference/init.md
content/docs/command-reference/install.md
content/docs/command-reference/list.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/remote/modify.md
content/docs/command-reference/status.md
content/docs/command-reference/update.md
content/docs/install/plugins.md
content/docs/start/data-pipelines.md
content/docs/start/data-versioning.md
content/docs/use-cases/data-registries.md
content/docs/use-cases/sharing-data-and-model-files.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/use-cases/versioning-data-and-model-files/tutorial.md
content/docs/user-guide/basic-concepts/dvc-project.md
content/docs/user-guide/contributing/docs.md
content/docs/user-guide/dvc-files.md
content/docs/user-guide/how-to/merge-conflicts.md
content/docs/user-guide/large-dataset-optimization.md
content/docs/user-guide/related-technologies.md
content/docs/user-guide/what-is-dvc.md

> Continues #2047. Also preps. for 2.0 dvc.yaml changes
> - [x] Change base here to `master` when that one is merged.
Last **needed** prep for 2.0 dvc.yaml changes
- ~~"DVC-file" (with dash)~~ This will need yet another PR. Too many files here already.
- \+ similar update to core repo? Maybe just open an issue there...
Per #1366

term: remove "stage files" (except from old blogs)

---

content/docs/command-reference/repro.md

Per https://github.com/iterative/dvc/pull/5194 …

repro: document multiline string

---

content/docs/command-reference/commit.md
content/docs/command-reference/config.md
content/docs/command-reference/import.md
content/docs/command-reference/install.md
content/docs/command-reference/plots/modify.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/start/data-pipelines.md
content/docs/use-cases/sharing-data-and-model-files.md

dvc: still pending 1.x updates (1)

---

content/docs/command-reference/add.md
content/docs/command-reference/cache/index.md
content/docs/command-reference/config.md
content/docs/command-reference/list.md
content/docs/command-reference/metrics/show.md
content/docs/command-reference/params/index.md
content/docs/command-reference/repro.md
content/docs/command-reference/root.md
content/docs/command-reference/run.md
content/docs/start/data-pipelines.md
content/docs/use-cases/shared-development-server.md
content/docs/user-guide/basic-concepts/dvc-cache.md
content/docs/user-guide/dvc-files-and-directories.md
content/docs/user-guide/how-to/add-deps-or-outs-to-a-stage.md
content/docs/user-guide/large-dataset-optimization.md

> Continues #2074
Per #2026
---

dvc: still pending 1.x updates (2)

---

content/docs/command-reference/install.md

The `pre-commit install` command has been modified to also install the `pre-commit` hook. `pre-commit` is the default hook which gets installed but if `hook-types` are specified, _all_ relevant `hook-types` must be specified, including `pre-commit`.

Update pre-commit install commands

---

content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/remote/modify.md

- A typo fix
- Review of `import[-url]` triggered by https://github.com/iterative/dvc/issues/4520#issuecomment-759617964

[v1] more 1.x updates... (import)

---

content/linked-terms.js

I just realized that all `dvc.yaml` and `dvc.lock` auto-links are broken 😱 
E.g. in https://dvc.org/doc/user-guide/dvc-files:
> Should be https://dvc.org/doc/user-guide/dvc-files/dvc-yaml

hotfix: fix automatic dvc.yaml/lock links

---

content/docs/user-guide/managing-external-data.md

People find this article quite often and tend to misuse it. Added a simple disclaimer to try to redirect them.
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the …

docs: external: add a disclaimer

---

content/blog/2021-01-26-january-21-community-gems.md

removed the ssl_verify flag mention as well
From https://github.com/iterative/dvc.org/pull/2116#discussion_r567695284

clarify use of env vars for self-signed certs in http remotes

---

content/docs/command-reference/remote/modify.md

config: add docs for s3.configpath

---

content/docs/command-reference/fetch.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/repro.md
content/docs/command-reference/run.md
content/docs/user-guide/basic-concepts/run-cache.md
content/docs/user-guide/project-structure/internal-files.md

Closes #1289
- New tooltip
- Update internal files guide (cache structure section)
- Link from `--run-cache` command options
- + correct `repro --pull` desc.
> This is needed for/ related to #1926

run-cache: basic docs

---

content/docs/command-reference/config.md

Support the --show-origin option for config, which, similar to git,
prefixes each config option with the source file it originated from.
Per iterative/dvc#5119
Matches iterative/dvc#5126
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-r …

cli: config: add docs for --show-origin

---

content/docs/user-guide/basic-concepts/dependency.md
content/docs/user-guide/basic-concepts/dvc-cache.md
content/docs/user-guide/basic-concepts/dvc-files.md
content/docs/user-guide/basic-concepts/dvc-project.md
content/docs/user-guide/basic-concepts/external-dependency.md
content/docs/user-guide/basic-concepts/import-stage.md
content/docs/user-guide/basic-concepts/output.md
content/docs/user-guide/basic-concepts/parameter.md
content/docs/user-guide/basic-concepts/run-cache.md
content/docs/user-guide/basic-concepts/workspace.md
package.json
src/gatsby/models/glossary/index.js
src/utils/front/glossary.ts
yarn.lock

configured tooltips to be defined in frontmatter and moved tooltip content to frontmatter

---

src/components/Documentation/Layout/SidebarMenu/index.tsx
src/components/Documentation/Layout/SidebarMenu/styles.module.css

I've fixed the drop down issue with sub-pages in documentation (closes #1427).
This changes improves the user experience when user tries to navigate quickly. Currently, the user has to scroll all the way down. 
I have used React state to handle the toggle based on the `activePaths`. The demo is attached below.

feat: sidebar dropdown toggle with subpages #1427

---

content/docs/command-reference/update.md

cmd: add dvc update --to-remote docs

---

content/docs/index.md
content/docs/sidebar.json
content/docs/start/experiments.md
content/docs/user-guide/basic-concepts/experiment.md
content/docs/user-guide/basic-concepts/run-cache.md
content/docs/user-guide/experiment-management.md
content/docs/user-guide/project-structure/internal-files.md
content/docs/user-guide/project-structure/pipelines-files.md
content/docs/user-guide/related-technologies.md
content/docs/user-guide/what-is-dvc.md

To support the new 2.0 features (`dvc exp`) per #2026. Closes #816
- New guide doc (main file to review): [content/docs/user-guide/experiment-management.md](https://github.com/iterative/dvc.org/pull/2146/files#diff-be6aa503d0cf32633b8a90ecca42b73c0059fd54c83ea20dc55406a9e549aaa8)
- Relevant links to ^ from existing docs
- Intros "experiment" tooltip
- Add `checkpoint` field to dvc.yaml outputs spec
- Update "run-cache" tooltip + some copy edits on that topic
---
Based on https://github.com/iterative/dvc/wiki/Experiments#usage, et al.
> May reuse some stuff from https://github.com/iterative/dvc.org/pull/828/files

guide: Experiment Management

---

content/docs/user-guide/basic-concepts/dvc-project.md
package.json

Previously #2194 was merged to update restylebot configuration. However prettier still seems to behave differently when it comes to trailing commas as can be seen in #2224. I made some tests and prettier version in `package.json` seems to be old and new version adheres the configuration in `.prettierrc`.

upgrades prettier to 2.2.1 to fix the bug causing trailingComma config to be ignored

---

yarn.lock

This fixes broken deployments caused by #2225. 
Upgrades `yarn.lock` for prettier 2.2.1

yarn.lock file updated for prettier upgrade

---

content/docs/command-reference/config.md

This is a cleaned up version of #2196. 
Fixes #2153. 
I kept `the` ➡️ `a` changes by @jorgeorpinel in the previous branch. I think these two should be `the` (as the original). We may revert those.

This fixes #2153 by removing the incorrect permissions.

---

content/docs/command-reference/add.md

cmd: add to-cache docs

---

plugins/external-link-plugin/index.js

Fixes #2294 
I assume since it's called `external-link`, we want the attrs for external links on all instances of this custom component and there's no need to check for internal links conditionally.

Add target="_blank" rel="noopener noreferrer" to external-link

---

content/docs/command-reference/params/index.md

The last example in 
https://dvc.org/doc/command-reference/params
has shows parameter tracking for custom filenames. But the supplied `dvc.yaml` and `dvc.lock` files don't contain any custom filename. 
This PR fixes that.

cmd: fix params example for using custom params file

---

content/docs/command-reference/cache/dir.md

The updated path for the system config file matches the path that is listed in https://dvc.org/doc/command-reference/config

Documentation: Update path to system config file

---

content/docs/api-reference/make_checkpoint.md

The path to the checkpoint signal file in the docs is missing `.dvc` after `$DVC_ROOT`. See https://github.com/iterative/dvc-checkpoints-mnist/tree/signal_file for an example.

fix path to checkpoint signal file

---

content/docs/command-reference/add.md

This is probably something leftover from the time that I changed order regarding to-cache/to-remote. `import-url` doesn't offer an alternative to to-cache but offers an alternative to `to-remote` so this patch moves the comment to the to-remote's segm

cmd: move import-url --to-remote ref from to-cache to to-remote

---

config/prismjs/dvc-commands.js
content/docs/command-reference/stage/list.md
content/docs/sidebar.json

Adding docs for `stage:list`. Implemented on https://github.com/iterative/dvc/pull/5498 and updated on https://github.com/iterative/dvc/pull/5499.
Pending issue: https://github.com/iterative/dvc/issues/5390, unlikely to change in a short term window.

document stage list

---

content/docs/sidebar.json

This PR adds Katacoda link to GS:Experiments page and fixes two other links that wasn't pointing the exact scenarios. 
Closes #2358

Added Katacoda experiments scenario link and fixed two other links

---

content/docs/user-guide/project-structure/pipelines-files.md

The document mentions `dvc run` as a way to create and run stages. Changed this to `dvc stage`.

Remove `dvc run` reference

---

content/docs/command-reference/exp/run.md

Document `exp run` behavior for https://github.com/iterative/dvc/pull/5029
Will close https://github.com/iterative/dvc.org/issues/2374

ref: document `exp run` behavior for untracked files

---

package.json

Before, `>=12` resolved to 16, but anything above 15 breaks older `sharp` versions
This should fix #2411

Pin Node to version 15

---

content/docs/user-guide/project-structure/pipelines-files.md

The `dvc.lock` reported as an illustration does not match the content of the `dvc.yaml` file.
I have made a test using a `clean.py` as follows:
```python
from pathlib import Path
import sys
with open(Path(sys.argv[1]).with_suffix(".cln"), "w") as file:
file.write("cleaned\n")
```
Please choose to [allow …

Fix dvc.lock file example for `foreach`

---

content/docs/command-reference/stage/index.md

Closes #2215 by reverting it's workaround, as it's no longer an issue 🤷

ref: remove extra space

---

content/docs/start/data-and-model-access.md
content/docs/start/data-and-model-versioning.md
content/docs/start/data-pipelines.md
content/docs/start/experiments.md
content/docs/start/index.md
content/docs/start/metrics-parameters-plots.md
content/docs/user-guide/basic-concepts/dependency.md
content/docs/user-guide/basic-concepts/dvc-cache.md
content/docs/user-guide/basic-concepts/experiment.md
content/docs/user-guide/basic-concepts/file-link.md
content/docs/user-guide/basic-concepts/parameter.md
content/docs/user-guide/basic-concepts/pipeline.md
content/docs/user-guide/basic-concepts/run-cache.md
content/docs/user-guide/contributing/docs.md

- misc copyediting mainly of `/doc/start/`
- add/update/use some `<abbr>`s
- fixes #1761

docs: misc content & guide updates

---

content/docs/use-cases/shared-development-server.md

Closes #429
See https://dvc-org-cases-shared-de-2cu4a8.herokuapp.com/doc/use-cases/shared-development-server#configure-the-external-shared-cache

cases: enable file links for shared dev config (external cache)

---

content/docs/install/plugins.md

This adds a blurb for how to get Doom Emacs to recognize the `dvc.lock` and `.dvc` files as YAML files, similar to the Vim blurb. Thanks so much!

Add configuration information for Doom Emacs.

---

content/docs/command-reference/remote/add.md

The link to Azure default credential was pointing to AWS instead of azure ;-) …

fix link to azure default credential in add.md

---

content/blog/2020-02-04-gsoc-ideas-2020.md
content/blog/2020-02-19-february-20-community-gems.md
content/blog/2020-03-11-march-20-dvc-heartbeat.md
content/blog/2020-03-24-march-20-community-gems.md
content/blog/2020-05-14-may-20-dvc-heartbeat.md
content/blog/2020-07-07-cml-release.md
content/blog/2020-07-10-july-20-dvc-heartbeat.md
content/blog/2020-08-07-cml-self-hosted-runners-on-demand-with-gpus.md
content/blog/2020-10-12-october-20-dvc-heartbeat.md
content/blog/2020-12-30-december-20-community-gems.md
content/docs/command-reference/add.md
content/docs/command-reference/checkout.md
content/docs/command-reference/commit.md
content/docs/command-reference/diff.md
content/docs/command-reference/fetch.md
content/docs/command-reference/import-url.md
content/docs/command-reference/install.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/index.md
content/docs/command-reference/remote/modify.md
content/docs/start/data-and-model-versioning.md
content/docs/start/experiments.md
content/docs/start/metrics-parameters-plots.md

This fixes various small typos across the blog and docs.
We, [Ritza](https://ritza.co), are a team of technical writers, editors, engineers, and quality assurance specialists. We create new technical content, such as developer tutorials, for highly technical products, and help improve and maintain existing developer documentation sites.

fix various small typos

---

gatsby-config.js

* added a quality of 90 to lower any possible image blurring

Add a quality key to gatsby-remark-images options

---

content/docs/sidebar.json
content/docs/start/index.md
content/docs/studio/create-view.md
content/docs/studio/get-started.md
content/docs/studio/index.md
content/docs/studio/run-experiments.md
content/docs/studio/teams.md
content/docs/studio/view-settings.md
content/docs/studio/visualize-experiments.md
src/components/LayoutHeader/alert.tsx

studio: further enhancements

---

content/docs/command-reference/remote/modify.md

https://github.com/iterative/dvc/pull/6018 implements the ability to set `ssl_verify` in the S3 remote config to a path to a custom CA bundle file in addition to setting `true`/`false`. It also makes the default the same as the `botocore` default, which is to read the CA bundle path from the AWS config. This updates the docs to reflect those changes.
🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it …

Updated S3 ssl_verify documentation

---

content/docs/command-reference/plots/index.md

Fix the naming of the <DVC_METRIC_X_LABEL> and <DVC_METRIC_Y_LABEL> template anchors.

Fix the naming of the label template anchors

---

content/docs/command-reference/remote/modify.md

Adding `ssl_verify` to http and webdav remotes. See https://github.com/iterative/dvc/pull/6142

document ssl_verify for http/webdav remotes

---

src/components/Documentation/Layout/styles.module.css
src/components/HamburgerMenu/index.tsx
src/components/HamburgerMenu/styles.module.css
src/components/LayoutHeader/Nav/LinkItems/styles.module.css
src/components/LayoutHeader/Nav/styles.module.css

* adds "Other Tools" to `HamburgerMenu`
* lowers font-size/font-weight to `16px` and 400 in nav bar links
* I also noticed that the `top` in the documentation side bar was off due to the nav bar height changing in the last nav iteration
Fixes #2543

Next header iteration

---

content/docs/command-reference/get-url.md
content/docs/command-reference/get.md
content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/list.md
content/docs/start/data-and-model-versioning.md
content/docs/user-guide/contributing/docs.md

1. `path` arg usage (`list/get/import`)
2. A typo
3. Docs contrib guide update
4. `get/import-url` don't support `remote://` URLs

misc. updates

---

content/docs/command-reference/remote/modify.md

Related to: https://github.com/iterative/dvc.org/issues/2593

Google Drive remote: add note on required authorization when impersonating users with service account

---

.github/workflows/update.yaml

This will check dvc releases once a day and will automatically create a PR with updates to download links for dvc. E.g. https://github.com/iterative/dvc-s3-repo/pull/15

gha: add dvc autoupdater

---

content/docs/cml/cml-with-dvc.md
content/docs/cml/start-github.md
content/docs/use-cases/shared-development-server.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/user-guide/setup-google-drive-remote.md
gatsby-config.js

* adds the same image processing that we use for the blog to the documentation images as well
* edits markdown for smaller images, giving them the same appearance as before(Our `resize-image-plugin` shrinks images that have a certain size, shrinking about 10 of our docs images. For now, to keep all images looking like they had before, I updating the markdown images, keeping the same width as the other images.)
* documentation images now have:
1. loading animation
2. webp formats
3. resizing
Fixes #2469

Add image processing to docs

---

content/docs/cml/cml-with-dvc.md
content/docs/cml/start-github.md
content/docs/use-cases/shared-development-server.md
content/docs/use-cases/versioning-data-and-model-files/index.md
content/docs/user-guide/setup-google-drive-remote.md

* Takes off `=700` off of several documentation images, allowing our `resize-image-plugin` to resize them to a smaller size
* Example: https://dvc-org-take-off-doc-im-curosi.herokuapp.com/doc/cml/start-github

Take `'=700'` off of documentation images markdown

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/link-check-all.yml
.github/workflows/link-check-deploy.yml
.prettierignore
.restyled.yaml

Lint all `*.js,json,md,yaml,yml`.
From https://github.com/iterative/cml-website/pull/60#pullrequestreview-703592675

format: lint all files

---

src/components/DownloadButton/index.tsx
src/components/DownloadButton/styles.module.css

* Originally, our `DownloadButton` dropdown was hidden by taking it out of the HTML with JS. This stops the dropdown links from being read with a link checker and stops the links from being read by a screen reader.

Hide DownloadButton dropdown with CSS instead of JS

---

content/docs/command-reference/exp/index.md
content/docs/start/experiments.md
content/docs/user-guide/basic-concepts/experiment.md
content/docs/user-guide/experiment-management/index.md
content/docs/user-guide/project-structure/pipelines-files.md

Follow up to https://github.com/iterative/dvc.org/pull/2663 (copy edit)
"Since" typically refers to a specific time. Reads a but strange for a version number, I think.

docs: copy edit DVC 2.0 notes

---

content/docs/user-guide/contributing/docs.md

* Updates our contributing docs, adding our custom language `dvctable` to our possible syntax highlighting options.
* See update at https://dvc-org-update-contribu-w0g4ji.herokuapp.com/doc/user-guide/contributing/docs

Update contributing docs to include `dvctable`

---

src/components/Documentation/Layout/index.tsx
src/utils/front/focusElementWithHotkey.ts

Adds a reusable `focusElementWithHotkey` function to listen for the `keydown` event on a particular key and respond by setting focus on the specified element. Implementing this with the "/" key and "#doc-search" element will fix #722.
Note to reviewer: This PR adds the `useEffect` for initializing this event listener to the main Layout component, but I am open to feedback on whether there is an alternate location that would be more appropriate.

feat: focus search box on forward slash keydown

---

content/docs/start/metrics-parameters-plots.md

In this one that was previously merged, the video was at the bottom.  Moving it towards the top like the others to be consistent.

moving video up page in metrics doc

---

src/components/DownloadButton/index.tsx
src/components/Link/index.tsx

* adds `optOutPredirect` prop to `Link`, stopping links from being pre redirected if desired
* ~~have Link render on mount, stopping any href changes due to hydration(fixes "CML" link shows 404 page bug mentioned in #2659)~~
* converts DownloadButton download absolute links to relative links
Fixes #2668

Update Link and DownloadButton components

---

gatsby-config.js

* adds an `excludePattern` to `gatsby-plugin-catch-links`, stopping our Doc "CML" link from showing a 404 page(mentioned in #2659)

Add excludePattern to `gatsby-plugin-catch-links` config

---

redirects-list.json
src/components/DownloadButton/index.tsx

* simplify download links to `/download/{OS}/dvc-{VERSION}`
* if you have an idea on a better format for the download links, please let me know!
Fixes #2691

Update dvc download link href

---

content/docs/command-reference/remote/modify.md

Some examples use the command `dvc remote push` which, if executed, results into an error.
Most probably, the correct command should be: `dvc push`.

Fix syntax error on `dvc push`

---

content/docs/dvclive/api-reference/init.md
content/docs/dvclive/api-reference/log.md

Replace `dvclive.error.DvcLiveError` with `dvclive.error.InvalidMetricTypeError`.
Per https://github.com/iterative/dvclive/pull/135

Add InvalidMetricTypeError exception

---

content/docs/user-guide/analytics.md

Per https://github.com/iterative/dvc/pull/6448 …

docs: analytics: add DVC_NO_ANALYTICS mention

---

content/docs/user-guide/experiment-management/checkpoints.md

Per https://github.com/iterative/dvc/pull/6332

Add checkpoint backup

---

redirects-list.json
src/utils/shared/redirects.js
src/utils/shared/redirects.test.js

Fixes #2749 
This PR tweaks our "trim trailing slashes" redirect entry to not apply to root-relative links that start with two slashes, which should close the open redirect bug since single slashes should only redirect to our site.

Close open redirect

---

content/docs/command-reference/exp/remove.md

per https://github.com/iterative/dvc/pull/6394

Remove all experiments

---

content/docs/user-guide/contributing/docs.md

dvc.org is a yarn project, so this line is incorrect as far as I can tell
The run of `yarn` on the previous line should do what this line is suggesting, so we can just completely remove the section and the instructions still hold true.

Remove `npm install` from contributing docs

---

content/docs/command-reference/remote/add.md

In the section https://dvc.org/doc/command-reference/remote/add#supported-storage-types, there is a broken link on "Click for Microsoft Azure Blob Storage". The link should point to: https://dvc.org/doc/command-reference/remote/modify#example-some-azure-authentication-methods.

Fix broken link to Azure authentication examples

---

content/docs/command-reference/remote/index.md

The order of arguments for `dvc remote rename` is reversed in the old version. 
According to the page @ `dvc remote rename -h`, the old remote `name` comes first followed by the `new` remote name argument.
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing- …

fix: correct argument order

---

content/docs/user-guide/experiment-management/sharing-experiments.md

Rename all references to `get-started-experiments` to `example-dvc-experiments`

---

content/docs/command-reference/exp/show.md

Add --show-csv flag to dvc exp show

---

content/docs/command-reference/list.md

Per https://github.com/iterative/dvc/pull/6683 (added alias to `dvc list` as `dvc ls` to fix https://github.com/iterative/dvc/issues/6651)

ref: alias `ls` for `list`

---

content/docs/command-reference/exp/show.md

docs updates for https://github.com/iterative/dvc/pull/6867
Not sure if this will actually get merged before #2862 but seems relevant to eventually include the option in the guide.

ref: `exp show --only-changed`

---

content/docs/command-reference/metrics/diff.md

https://github.com/iterative/dvc.org/pull/2988#issuecomment-961253726

Removed non existing `dvc metrics diff --old` option

---

content/docs/user-guide/experiment-management/comparing-experiments.md

Rel. https://github.com/iterative/dvc.org/issues/2995
> - [x] Needs detailed copy editing. E.g. [missing "the"](https://github.com/iterative/dvc.org/pull/2862#pullrequestreview-783752862), disjointed paragraphs, unnecessary scrolling blocks, etc.
> - [x] `--sort/order-by/no-timestamp` sections may be too detailed. Hide or just mention + link to ref.
> - [x] Merge JSON and CSV sections somehow
> - [x] Shorten JSON/CSV output sample blocks and remove corresponding schema descriptions (comprehensive examples are enough).
> - [x] Clarify `exp diff` sections to separate cases: workspace vs. `HEAD`, rev A vs rev B, etc.

guide: copy edit Comparing Exps

---

content/docs/command-reference/exp/diff.md
content/docs/user-guide/experiment-management/comparing-experiments.md

P.R. for https://github.com/iterative/dvc/pull/6888

Updated exp diff tables

---

config/prismjs/dvc-commands.js
content/docs/command-reference/exp/index.md
content/docs/install/index.md
content/docs/user-guide/experiment-management/index.md
content/docs/user-guide/project-structure/pipelines-files.md
content/linked-terms.js
plugins/gatsby-remark-dvc-linker/package.json
redirects-list.json

per https://github.com/iterative/dvc.org/issues/2989
> - [x] There are no links to either one (`version/doctor`) from any other docs.
> - [ ] `ls` not existing seems like a bug ATM (quite inconsisntent)
> - [x] `experments` not existing is a bug -- as it used to be the path, it should be redirecting to `exp`.
> - [x] Also, the now `exp` page says it's "aliased to `exp`" which no longer makes sense.
Also
Finally

ref: fix aliasing bugs

---

content/docs/command-reference/exp/run.md
content/docs/user-guide/experiment-management/experiments-overview.md

> Per https://github.com/iterative/dvc.org/pull/2909#discussion_r743028065

[NESTED] guide: Exp implementation details, naming into Overview

---

content/docs/command-reference/add.md

Replaces all `dvc run` examples / mentions with `dvc stage add` in `dvc add` command reference page. 
Closes #3023

ref: replaced all `dvc run` references with `dvc stage add` in `dvc add`

---

src/components/Community/Events/index.tsx

* Event dates are one day off due to how `new Date()` [creates dates in production](https://dev.to/zachgoll/a-complete-guide-to-javascript-dates-and-why-your-date-is-off-by-1-day-fi1).

Fix incorrect `/community` events dates

---

content/docs/user-guide/contributing/docs.md
package.json

`yarn` started failing for me today. It wanted node 14+ I think (I closed the terminal, oops).

guide: update Node version (docs contrib)

---

content/community.json

The url in our `/community` hero is leading to "Page Not Found":
I updated it to the notion page link that we use for iterative.ai

Update community.json, fixing broken hero url

---

src/components/Community/Hero/styles.module.css

Part of #3084. Forgot that safari (unlike chrome) automatically applies `align-items: stretch` onto flex items.

Fix broken community hero image in safari

---

content/docs/command-reference/freeze.md
content/docs/command-reference/unfreeze.md

This one replace `dvc run` references in `dvc freeze` and `unfreeze` command ref. 
Closes #3070

ref: Replace `dvc run` refs in `dvc freeze` and `dvc unfreeze`

---

content/docs/command-reference/import.md

From https://discord.com/channels/485586884165107732/485596304961962003/918463103560196116
> Question: I'm reading the documentation and how to use dvc import properly ... under [Importing and updating fixed revisions](https://dvc.org/doc/command-reference/import#example-importing-and-updating-fixed-revisions) that when you have used `dvc import --rev` with a git hash and we want to force-update it to a different commit, we might use `dvc update --rev`, and the example given is: `dvc update --rev cats-dogs-v2`.
Should it not be `dvc update --rev cats-dogs-v2 <stage>.dvc`, though?
> seems like you found a bug in our docs. You are correct that there should be <stage>.dvc in the end of this line.

updated syntax for dvc import example

---

src/components/Link/index.tsx
src/components/Page/utils.ts
src/utils/front/safeQuerySelector.ts

* stop code from running `querySelector` on invalid id strings
Fixes #2395

Fix site crashing with certain anchor links

---

src/components/DownloadButton/index.tsx
src/utils/front/plausible.ts

* Stops calling the `plausible` function with a second falsy argument
* Renames one of the `Download Button` items from `...` to `unknown`

Fix bugs in analytics

---

content/docs/command-reference/config.md

config: reorder and summarize sections (in ref.)

---

config/prismjs/dvctable.js
src/components/Documentation/Markdown/Main/styles.module.css

We're [still discussing](https://github.com/iterative/dvc.org/issues/3102) if we want to use this design for our tables, but I went ahead and opened a pull request with the new configuration for code reviews. 
`dvctablehorizontals` markdown:
```
─────────────────────────────────────────────────────────────────────────────────────────────
white:**Experiment**                white:**Created**           yellow:**loss**      yellow:**acc**   blue:**train.epochs**   blue:**model.conv_units**
─────────────────────────────────────────────────────────────────────────────────────────────
workspace                 -              0.24057   0.9157   10             16
baseline-experiment       Dec 05, 2021   0.24057   0.9157   10             16
└── 67d5a70 [exp-c4f81]   Dec 23, 2021   0.24057   0.9157 …
```

Add `prismjs` `dvctablehorizontals`

---

src/components/Documentation/Layout/SidebarMenu/index.tsx
src/components/Documentation/Layout/SidebarMenu/styles.module.css

* Turn the menu's dropdown bullet points into buttons, allowing keyboard users to tab over them (if you try to tab through a docs page inside dvc.org, you'll get stuck on a dropdown)
Part of #1149

Fix broken tab order on docs sidebar menu

---

content/docs/start/experiments.md

This one removes "If you used DVC repro before" hidden section from the Getting
Started: Experiments document. As we'll introduce `dvc exp init`, dvc repro
becomes less useful and from the input we got so far, this section is
confusing. 
Related #3051

start: remove "if you used dvc repro before" hidden section from start

---

redirects-list.json

Fixes 404 on https://man.dvc.org/completion

redirects: add man.dvc.org/completion

---

content/docs/command-reference/remove.md

Replaces reference to `dvc run` in `dvc remove` ref.
Closes #3103

ref: Replace `dvc run` reference in `dvc remove`

---

content/docs/start/experiments.md

This one adds a hidden section to explain parameters in more detail. 
The final goal of this series is to merge "Params/Metrics/Plots" into the experiments trail. 
Related #3051

start: Add a parameters hidden section to experiments to merge params/metrics into experiments

---

content/docs/command-reference/exp/index.md
content/docs/command-reference/list.md

For consistency and readability.

ref: move Alias notes before cmd def.

---

content/docs/command-reference/exp/list.md

added `--names-only` description

ref: add `--names-only` option description to `dvc exp list`

---

content/docs/user-guide/project-structure/internal-files.md

In user-guide/project-structure/internal-files. I think the content no longer exists

Remove broken `note` links

---

config/prismjs/dvctable.js
src/components/Documentation/Markdown/Main/styles.module.css

dvctable: Add `violet` for `dep` columns.

---

content/docs/command-reference/freeze.md
content/docs/command-reference/import-url.md
content/docs/command-reference/index.md
content/docs/command-reference/plots/modify.md
content/docs/user-guide/experiment-management/index.md

Per https://github.com/iterative/dvc.org/pull/3223#pullrequestreview-865256066

ref: misc. improvements around "stage" concept

---

src/components/LayoutHeader/Nav/styles.module.css

* hides the nav's list item markers
* fixes the last bug mentioned in #2794
Fixes #2794

Stop list item markers from appearing in Google Chrome's auto dark mode

---

content/docs/command-reference/exp/remove.md

It is not true that `--all` includes `--queue`. Options need to be combined in order to effectively remove all ran and queued experiments

`exp remove`: Update help for `--all` flag

---

plugins/gatsby-theme-iterative-docs/src/constants.ts

* fix typo in `gatsby-theme-iterative-docs/src/constants`

Fix broken "Edit on Github" links

---

config/gatsby-remark-embedder/custom-yt-embedder.js
gatsby-config.js
plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Main/index.tsx
plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Main/styles.module.css
plugins/gatsby-theme-iterative-docs/src/utils/front/setUpCustomYtEmbeds.ts
plugins/gatsby-theme-iterative-docs/src/utils/front/useCustomYtEmbeds.ts
src/components/Blog/Post/Markdown/styles.module.css
src/components/Blog/Post/index.tsx
src/components/Home/UseCases/Video/index.tsx
src/components/Home/UseCases/Video/styles.module.css

* adds a message about youtube's policys when a user hovers over a youtube embed. 
* For our video component, I just added  a message below our overlay button. For our markdown, this is done by using a custom `gatsby-remark-embed` transformer and inserting a js script that handles taking off the message when the user has clicked. 
**To Do**

Make YouTube Embeds GDPR compliant

---

plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/index.tsx

This will be a simple addition to the current toggle tab on markdown.
We can set a height through a `height` prop on the `toggle` component `<toggle height="300px">` which will set height for all the tabs.
Ported from [pull cml#193](https://github.com/iterative/cml.dev/pull/193)
This is added to the `gatsby-plugin-iterative-docs` plugin.
Solves #3179

added height prop to toggle tag

---

content/docs/start/data-and-model-versioning.md

Received and error while removing the data file. 
Remove-Item : Parameter cannot be processed because the parameter name 'f' is ambiguous. Possible
matches include: -Filter -Force. 
I used Force command to make it work.

start: use tabs for a Windows command

---

.github/workflows/merge-schedule.yaml

* As shown by #3215, the merge-schedule workflow only runs for prs that aren't from forks and will fail if it runs on a forked pr.

Only run merge-scheduler workflow if it's not a fork

---

content/docs/command-reference/exp/run.md
content/docs/command-reference/gc.md
content/docs/user-guide/experiment-management/running-experiments.md

and other misc edits to Running Exps, and to the `gc` ref.
To close #2418

guide: note that `exp run` commits data

---

content/docs/start/experiments.md

This one adds a brief hidden section about metrics to https://dvc.org/start/experiments/
Related #3051

start: add a section about metrics to experiments

---

content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/command-reference/fetch.md
content/docs/command-reference/gc.md
content/docs/command-reference/get-url.md
content/docs/command-reference/get.md
content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/remote/modify.md
content/docs/command-reference/status.md
content/docs/command-reference/update.md

The default to `4` is no longer True.
Per https://github.com/iterative/dvc/pull/7339

ref: Remove outdated SSH default jobs.

---

.github/workflows/merge-schedule.yaml

* updates `if` statement in action to check for event type

Fix broken merge-schedule gh action

---

src/components/LayoutHeader/Nav/LinkItems/index.tsx
src/utils/onSelectKey.ts

>I just realized that by using onPointerUp, keyboard users are not able to click on the dropdown. 
Added keyboard support for the dropdown. Update on #3317

Fix: keyboard interaction for dropdown

---

content/docs/command-reference/remote/modify.md

GCP Cloud shouldn't really link to Google Drive setup.
See https://github.com/iterative/terraform-provider-iterative/pull/402#discussion_r810441655.

better GCP service account links

---

content/docs/command-reference/exp/run.md
content/docs/user-guide/experiment-management/checkpoints.md
content/docs/user-guide/experiment-management/running-experiments.md

Minor stuff I hit while glossing over some docs...
Some other thing that bothered me a bit (made me stop and re-read a few times) is the compound noun "pipeline_**s**_ file(s)" instead of "pipeline file(s)" (pipelines plural), but I ... guess it's valid...? 🤔

Minor fixes

---

content/docs/command-reference/exp/show.md

It was referencing `dvc dag` for paging info. Now it's self contained and added an example to use `cat` as a pager. 
Closes #3217

`ref`: Duplicated paging info to `exp show` 

---

src/templates/blog-post.tsx

* takes off "html" from the page query, as it is not being used anywhere

Update blog post graphql query

---

content/blog/2020-07-07-cml-release.md
content/blog/2020-07-16-devops-for-data-scientists.md
content/blog/2020-08-07-cml-self-hosted-runners-on-demand-with-gpus.md
content/blog/2020-11-25-november-20-community-gems.md
content/blog/2021-03-03-dvc-2-0-release.md

Closes #3373. Doesn't include references to the [current container image documentation](https://cml.dev/doc/self-hosted-runners#docker-images) because it's (potentially) going to be moved to a separate section as per https://github.com/iterative/cml.dev/issues/102.

Update stale CML container images

---

package.json
plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Main/styles.module.css
plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/index.tsx
yarn.lock

Made the `<details>` block linkable and will auto expand when the link is opened through the hashed links.
Some considerations and possible issues:
- I have used the details `title` for the `id` attribute which seems to be a good solution until there are [some pages that have the same titles in multiple places](https://dvc.org/doc/start/data-and-model-versioning) particularly ` Expand to see what happens under the hood.`
Fix for #3314

`<details>` blocks linkable

---

content/docs/command-reference/install.md

If installing the `pre-commit` hook following the guide (using `rev: main` revision for the hook), the following warning is printed
whenever running `git commit`
> [WARNING] The 'rev' field of repo 'https://github.com/iterative/dvc' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.

add note regarding hook revision to install section

---

content/docs/use-cases/data-registries.md

I assume in this example it should say `songs` instead of `images`.

Fix typo in data-registries.md

---

content/blog/2020-07-07-cml-release.md
content/blog/2020-07-16-devops-for-data-scientists.md
content/blog/2020-08-07-cml-self-hosted-runners-on-demand-with-gpus.md
content/blog/2020-08-27-august-20-community-gems.md
content/blog/2020-10-26-october-20-community-gems.md
content/blog/2020-12-30-december-20-community-gems.md
content/blog/2021-02-22-cml-runner-prerelease.md
content/blog/2021-02-26-february-21-community-gems.md
content/blog/2021-03-03-dvc-2-0-release.md
content/blog/2021-07-27-july-21-dvc-community-gems.md
content/blog/2021-08-31-august-21-community-gems.md

- `p0`: fix tutorials (part of iterative/cml.dev#211)
- `p2`: update hyphenation/spacing

blog/cml: fix tutorials

---

content/docs/command-reference/get-url.md
content/docs/command-reference/remote/add.md
content/docs/command-reference/remote/modify.md
content/docs/user-guide/contributing/core.md
content/docs/user-guide/external-dependencies.md
content/docs/user-guide/managing-external-data.md

Details blocks are `#id` linkable now (#3329) so should have [URL-friendly names](https://github.com/iterative/dvc.org/pull/3299#issuecomment-1048325250)

cleanup remote block headings

---

content/docs/start/data-pipelines.md

This replaces `dvc run` examples in `data-pipelines`. 
Related #3309

start: Replace `dvc run` references in data-pipelines

---

content/docs/index.md
plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Admonition/index.tsx
plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Admonition/styles.module.css

* makes title optional, taking it off by default
Code Example:
```
<admon>
I don't need a title since I'm just a block of text.
</admon>
<admon title="Custom Title" type="tip">
I need a custom title for some reason
</admon>
```
Result:
Fixes #3381

Update admonitions, making `title` optional

---

content/docs/command-reference/config.md

per https://github.com/iterative/dvc.org/issues/1368#issuecomment-634456922

ref: `config` reads from all config files combined

---

package.json
src/components/DocumentationLayout/index.tsx
src/components/DocumentationLayout/styles.module.css
src/components/LayoutHeader/alert.tsx
src/components/MainLayout/index.tsx
src/components/MainLayout/styles.module.css
yarn.lock

Added hidden `skip to content`, that can be used by keyboard users for directly navigating to main content. 
Since the `docs` have side navigation as well, I thought it would be better to skip that as well. 
There seems some interference with how we currently handle the scrolling hash link.
Related to #3154

Added hidden `skip to content` for keyboard navigation

---

content/docs/command-reference/metrics/index.md
content/docs/command-reference/metrics/show.md

Per https://github.com/iterative/dvc/pull/5339
Closes: #1909

metrics: info on non-output usage

---

content/docs/command-reference/diff.md
content/docs/install/linux.md
content/docs/install/macos.md
content/docs/install/windows.md
content/docs/start/data-and-model-versioning.md
content/docs/start/data-pipelines.md
content/docs/user-guide/external-dependencies.md
plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/index.tsx
plugins/gatsby-theme-iterative-docs/src/utils/front/Slugger.ts

Fixes #3383 
The comments from previous pr https://github.com/iterative/dvc.org/pull/3352#issuecomment-1068236555 and issue https://github.com/iterative/dvc.org/issues/3383#issuecomment-1085153649 are taken into consideration.
So by default, the anchor id will be generated based on the title. And, if there are duplicate titles inside the same page(path) then a run time error popup will appear on the page.
We can set the unique id using the `id` as props on the `<details>` tag, this will clear the above error if the id is unique.
Currently, if the `<details>` block misses the header element as first-child an error popup is thrown. It will be similar to that.
We need to display the error popup in order to make sure the id either passed as props or generated from the title is unique.
PS: …

Added id as props for unique anchor

---

src/components/Page/DefaultSEO/index.tsx
src/consts.js
src/server/index.js
src/server/middleware/api/index.js
src/server/middleware/api/plausible.js

Fixes https://github.com/iterative/iterative.ai/issues/423
Created proxy API for plausible basically to handle these two requests
```
pl/js/script.js -> https://plausible.io/js/script.js
pl/event    -> https://plausible.io/api/event
```
Todo: 
**Update**: 
Script: https://dvc-org-proxy-plausible-cd4crn.herokuapp.com/api/pl/js/script.js
Event API: https://dvc-org-proxy-plausible-cd4crn.herokuapp.com/api/pl/event

Added proxy api for Plausible on current express server

---

plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Main/styles.module.css

Fixes permanently visible icons in the lists:
There is one more bug I haven't had time to fix - there is some space in between this link icon and the bullet point when hover is not active.
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull …

doc eng fix: hide anchor icons by default in lists

---

content/docs/user-guide/setup-google-drive-remote.md

For service accounts it is also an option to pass keys via an env variable. …

gdrive remote service accounts can use env var

---

content/docs/user-guide/setup-google-drive-remote.md

Noticed the description on how to create a service account was somewhat outdated. The flow is now somewhat different on GCP; updated the docs to reflect that.

Update service account creation flow

---

plugins/gatsby-theme-iterative-docs/src/components/Documentation/Markdown/Admonition/index.tsx

* Currently the admonitions `icon` prop defaults to type. This can [cause confusion](https://github.com/iterative/cml.dev/pull/210#issuecomment-1118010521) and [cause admonitions to be used incorrectly](https://github.com/iterative/dvc.org/pull/3411/files#r862385328). 
* To make things easier, I've stopped `icon` from defaulting to `type`

Enhance Admonitions

---

content/docs/command-reference/exp/init.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md
content/docs/dvclive/api-reference/live/index.md
content/docs/dvclive/api-reference/live/make_report.md
content/docs/dvclive/api-reference/live/next_step.md
content/docs/dvclive/api-reference/live/set_step.md
content/docs/dvclive/dvclive-with-dvc.md
content/docs/dvclive/get-started.md
content/docs/sidebar.json
content/docs/user-guide/experiment-management/checkpoints.md
content/docs/user-guide/project-structure/pipelines-files.md

In favor of reusing `metrics` and `plots`.
Closes https://github.com/iterative/dvclive/issues/77
Closes https://github.com/iterative/dvclive/issues/229
Closes https://github.com/iterative/dvclive/issues/230

DVCLive: Deprecate `live` section of `dvc.yaml`.

---

content/docs/command-reference/exp/list.md
content/docs/command-reference/stage/list.md
content/docs/user-guide/experiment-management/comparing-experiments.md
content/docs/user-guide/how-to/share-many-experiments.md

See https://github.com/iterative/dvc/pull/7598.
I'll suggest not merging this PR for a few months :). Until we are confident that a lot of users have that alias support, otherwise may result in a confusion.

doc: use `--name-only` alias instead in exp/stage list

---

content/docs/command-reference/params/index.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md

See https://github.com/iterative/dvc/issues/5971
adds note to parameter values section metioning scientific notation for SEO
use ruamel.yaml in example instead of PyYAML and add note
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-reque …

docs: update docs for YAML 1.2 compatibility mitigation

---

content/docs/sidebar.json
plugins/gatsby-theme-iterative-docs/src/utils/shared/sidebar.js

Let sidebar uppercase more than `dvc` in labels made from slugs

---

content/docs/command-reference/exp/list.md
content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/user-guide/experiment-management/cleaning-experiments.md

`dvc exp list --all` has been replaced by `dvc exp list --all-commits` (the former still works but is an undocumented alias).

replace exp list --all with --all-commits

---

content/docs/user-guide/troubleshooting.md

Closes https://github.com/iterative/dvc.org/issues/3416 (via this https://github.com/iterative/dvc.org/issues/3416#issuecomment-1089866190).
In review app: https://dvcorg-troubleshootingshallow.gtsb.io/doc/user-guide/troubleshooting#git-shallow

user-guide: add troubleshooting entry for dvc-exp in shallow clones

---

.husky/pre-commit
package.json
src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/Nav/Popup/index.tsx
src/@dvcorg/gatsby-theme-iterative/components/MainLayout/index.tsx
src/@dvcorg/gatsby-theme-iterative/components/data/styles.module.css
src/components/SubscribeSection/Form/index.tsx
src/components/Support/Popover/index.tsx
src/templates/doc-jsx.tsx
tsconfig.json
yarn.lock

Not sure when everything started breaking. Husky probably broke when #3396 was merged since that was when husky was upgraded. Maybe the CSS lint and TS lint broke at that time as well since we did upgrade a lot of different packages 🤔 Have to run some tests to be sure!

Fix failing master lint

---

src/@dvcorg/gatsby-theme-iterative/components/data/styles.module.css
src/components/Blog/Feed/Item/styles.module.css

Thumbnails for blogpost header images are resized to a different aspect ratio. This results in some content being lost on the left and right sides, which can be problematic if there are logos or text in that area.
This change to the CSS resizes the images in a way that preserves the aspect ratio.
**Before:**
**After:**

Resize images for blogpost previews to preserve aspect ratio

---

src/@dvcorg/gatsby-theme-iterative/components/LayoutFooter/index.tsx
src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/Nav/Popup/index.tsx
src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/Nav/Popup/styles.module.css
src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/alert.tsx
src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/styles.module.css
src/@dvcorg/gatsby-theme-iterative/components/data/menu.ts
src/@dvcorg/gatsby-theme-iterative/components/data/styles.module.css
src/components/Features/index.tsx
src/components/Features/styles.module.css
static/img/vscode-icon.svg

Add Info about VS Code Extension

---

content/docs/sidebar.json
content/docs/studio/index.md
gatsby-config.js

Leave redirect for now.
Why? The nav is growing a lot (VS Code section coming soon) and CML is already linked in several places as well as in the "Other tools" widgets.

nav: remove CML link

---

content/docs/command-reference/exp/init.md

ref: update exp init --type value

---

src/components/DownloadButton/index.tsx
src/utils/front/useUserOS.ts

rough fix for #3633 
Main problem is that it has to update after first render which is a problem shared with live GitHub stars
We could either remove the description or make its update transition friendlier, anything with less drawbacks will take an order of magnitude more effort to implement.

Only update User OS after hydration

---

src/components/Blog/Layout/index.tsx

Gatsby 4.15 introduced a built-in `Script` component, which acts much like the HTML `script` element but does optimizations such as making scripts loaded with the Gatsby component load after Hydration, improving initial page load time.
It turns out this is the only `script` tag in the repo which isn't in the theme. There's another in `gatsby-ssr` but that one is meant to not be deferred. Probably won't gain us a ton of points, but figured I may as well push it.

Use Gatsby Script tag to add Reddit script

---

src/components/Blog/Layout/index.tsx

After finding something that implements the reddit embed API, I realized #3677 actually broke it. Seems like the `Script` tag is incompatible with `Helmet`, but that's not an issue since the `Script` tag already moves its scripts to the bottom of the page regardless of where they are.
See demo of broken reddit embed [on this page](http://dvc.org/blog/july-19-dvc-heartbeat#how-do-you-manage-your-machine-learning-experiments-discussion-on-reddit-is-full-of-insights).
broken:
fixed:

Move Script tag outside of helmet

---

content/docs/command-reference/remote/modify.md

Changes based on https://github.com/iterative/dvc/pull/7671 …

s3fs: Added documentation for SSE-C support

---

content/docs/install/linux.md

`apt-key` is deprecated. New install steps inspired by: https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions

Remove mention of deprecated apt-key

---

content/docs/sidebar.json

Per https://github.com/iterative/katacoda-scenarios/issues/70
Closes https://github.com/iterative/dvc.org/issues/3722

katacoda: remove all links from internal nav

---

content/docs/command-reference/update.md

Parts of the doc look like they predate `import-url`, so I added some text to clarify that it also updates external URLs from `import-url`.

ref: include import-url scenario in dvc update

---

content/docs/command-reference/metrics/index.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md

Companion to https://github.com/iterative/dvc/pull/7965

metrics: now support TOML files

---

content/docs/command-reference/config.md
content/docs/user-guide/project-structure/pipelines-files.md

config: Add `parsing` section.
Per https://github.com/iterative/dvc/pull/7907

templating: Add `dict unpacking` section.

---

content/docs/command-reference/remote/modify.md

ref: code blocks around `remote modify` `sse`, etc.

---

scripts/heroku-deploy.sh

I don't think we use this directory in production as all contents are copied to `public`. This will help us with our slug size issue on our websites, particularly with blogs.
The resulting slug is much smaller, and will probably scale just fine since it doesn't include infinitely scaling images.
```
-----> Compressing...
Done: 192.1M
```

Remove static directory after heroku build

---

content/docs/command-reference/config.md
content/docs/command-reference/exp/init.md
content/docs/command-reference/params/index.md
content/docs/sidebar.json
content/docs/start/experiments/visualization.md
content/docs/use-cases/experiment-tracking.md
content/docs/user-guide/experiment-management/index.md
content/docs/user-guide/experiment-management/running-experiments.md
content/docs/user-guide/project-structure/dvcyaml-files.md
content/docs/user-guide/project-structure/index.md
content/linked-terms.js
redirects-list.json

Closes #3734
Main changes in
- content/docs/sidebar.json
- content/docs/user-guide/project-structure/index.md &
- content/docs/user-guide/project-structure/dvcyaml-files.md
- content/docs/user-guide/experiment-management/running-experiments.md
- redirects-list.json
The rest are link updates.

guide: remove term "pipelines files" (stick to "dvc.yaml" files)

---

content/docs/command-reference/exp/gc.md
content/docs/command-reference/gc.md

related to PR: https://github.com/iterative/dvc/pull/7970 …

gc: Add `--time` flag to dvc gc and dvc exp gc

---

redirects-list.json

Per https://github.com/iterative/dvc.org/pull/3728#pullrequestreview-1041204655:
> We shouldn't change existing (301) redirects, especially if they're not quite old (1y+). We should only add more (subsequent) redirects

hotfix: redirects

---

.github/workflows/link-check-deploy.yml

I missed this in #3700 and only caught it when starting to add it to our other websites

Remove out-of-date comment on link check deploy workflow

---

src/components/Blog/Post/Markdown/styles.module.css

Fixes an issue where MLEM and CML commands aren't being highlighted in code blocks in the blog. You can see an example of this [on our "Serving Models with MLEM" blog post.](https://dvc.org/blog/serving-models-with-mlem#serve-with-fastapi)
Before:
After:
Basically, Prism depends on some special CSS to actually add styles to the tokens it generates. We updated those styles in the docs, but the blog has a completely separate stylesheet which wasn't updated. The relevant parts got `.token.mlem` classes, but that blog stylesheet only targeted `.token.dvc`.
Whether we should have these parallel stylesheets is a good question, but this PR just intends to fix the problem and leave any bigger implementation questions for later.
Some commands still aren't highlighted:
This is because `build` isn't …

Fix MLEM and CML highlighting in the blog

---

redirects-list.json

This one ([just added](https://github.com/iterative/dvc.org/pull/3621/files#diff-a6828b19e9794c1fbb6799ea95263fb7487b676d054932b5f6e3b315eb12a6a2)) should be 302 in prep for possible #3622

hotfix: 302 redirect

---

content/docs/use-cases/fast-data-caching-hub.md

I've added a missing preposition "to" in the "Fast and Secure Data Caching Hub" tutorial.
The change affects a few lines because of the required line wrap.

Add a missing preposition "to"

---

config/link-check/excluded-links.yml
content/blog/2021-03-15-March-21-dvc-heartbeat.md

The tweet that this PR changes recently became protected, likely due to the author marking their account protected for other reasons. This is a problem for us because `gatsby-remark-embedder` throws an error if it runs into a protected tweet, and even if we disabled that and went full client-side we still wouldn't be able to embed it.
This PR puts out the fire by changing the tweet in question into a static representation with a link to the original. The style is modeled after the original, and the change is nearly imperceptible.
https://user-images.githubusercontent.com/9111807/182909746-4f7555b5-613c-4d95-aea3-8aff160fe2e7.mp4

Replace protected tweet embed with a static representation

---

content/docs/dvclive/api-reference/live/index.md
content/docs/dvclive/api-reference/live/log.md
content/docs/dvclive/api-reference/live/log_image.md
content/docs/dvclive/api-reference/live/log_plot.md
content/docs/dvclive/api-reference/live/make_report.md
content/docs/dvclive/api-reference/live/next_step.md
content/docs/dvclive/api-reference/live/set_step.md
content/docs/dvclive/dvclive-with-dvc.md
content/docs/dvclive/get-started.md

Per https://github.com/iterative/dvclive/pull/266

live: markdown report support.

---

config/link-check/excluded-links.yml
content/blog/2021-03-15-March-21-dvc-heartbeat.md

Reverts iterative/dvc.org#3864
from https://github.com/iterative/dvc.org/issues/3865#issuecomment-1205653477
> > Just paste the tweet in as a blockquote
> 
> we can't do this, Twitter has certain rules about embedding their tweets (put a logo, etc).
> In this case I would just keep a quote and link to person's name.
I merged #3864 before I read this, so this PR changes to a static quote with a name and no tweet link.

Revert and remove static tweet

---

content/docs/command-reference/queue/start.md

I've fixed a broken link and turned a link to the "run-cache" (with a missing URL) docs into an abbreviation because I think that's more consistent with the rest of the docs.

Fix link and abbreviation

---

content/docs/contributing/core.md
content/docs/contributing/docs.md
content/docs/install/linux.md
content/docs/install/macos.md
content/docs/install/pre-release.md

DVC requires Python 3.8 at a minimum since [2.11.0](https://github.com/iterative/dvc/releases/tag/2.11.0) (https://github.com/iterative/dvc/pull/7826). Updating the docs to reflect that.

docs: mention that dvc requires Python 3.8 now

---

src/server/middleware/api/comments.js

check `url` exists before checking `url.startsWith`.
```
Aug 19 22:46:53 dvc-org app/web.1 ^
Aug 19 22:46:53 dvc-org app/web.1 TypeError: Cannot read properties of undefined (reading 'startsWith')
Aug 19 22:46:53 dvc-org app/web.1 at getCommentCount (/app/src/server/middleware/api/comments.js:23:12)
Aug 19 22:46:53 dvc-org app/web.1 at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
Aug 19 22:46:53 dvc-org app/web.1 at next (/app/node_modules/express/lib/router/route.js:144:13)
Aug 19 22:46:53 dvc-org app/web.1 at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
Aug 19 22:46:53 dvc-org app/web.1 at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
Aug 19 22:46:53 dvc-org app/web.1 at …
```

Quick fix for heroku crash

---

src/@dvcorg/gatsby-theme-iterative/components/HamburgerMenu/index.tsx
src/@dvcorg/gatsby-theme-iterative/components/data/menu.ts

Once we work on the categorization of blogs, I believe we will have a separate page for the DVC blog and we can link to that.
Related:
- https://github.com/iterative/cml.dev/pull/302
- https://github.com/iterative/mlem.ai/pull/157

Add blog to navbar

---

content/docs/command-reference/import-url.md
content/docs/command-reference/import.md
content/docs/command-reference/update.md

Add documentation for new `dvc import-url` `dvc update` flags  (`--no-download`)
related: https://github.com/iterative/dvc/pull/8024 (per iterative/dvc#7918)

import-url/update: add --no-download flag

---

content/docs/sidebar.json
content/docs/user-guide/project-structure/dvcyaml-files.md
content/docs/user-guide/visualizing-plots.md

Addresses post-merge comments in #3830

docs: cleanup of plots content

---

src/components/SubscribeSection/Form/index.tsx

Added hidden tags field to add Mailchimp tag (Website DVC).
Tested with temprory email as mine were already subscribed`vikadi2572@vpsrec.com` and archived.

Add DVC tag on Subscribe form

---

content/docs/command-reference/stage/add.md

@alex000kim showed me how to do this for a project in which I'm using Papermill to run an entire notebook from a single stage. As far as I could find, this approach isn't yet covered by the docs. Thought it might be worth highlighting, even though it's not always the most proper approach.

Show how to parse params into stage cmd

---

content/docs/command-reference/import.md

Prevents horizontal scrolling in https://dvc.org/doc/command-reference/import#synopsis.
> Edited from GH so couldn't combine with https://github.com/iterative/dvc.org/pull/3934, sorry.

ref: reorg and wrap `import` usage block

---

content/docs/command-reference/dag.md
content/docs/command-reference/exp/index.md
content/docs/command-reference/exp/init.md
content/docs/command-reference/move.md
content/docs/command-reference/params/index.md
content/docs/command-reference/repro.md
content/docs/command-reference/run.md
content/docs/command-reference/stage/add.md
content/docs/command-reference/stage/index.md
content/docs/start/data-management/pipelines.md
content/docs/user-guide/basic-concepts/pipeline.md
content/docs/user-guide/basic-concepts/stage.md
content/docs/user-guide/experiment-management/running-experiments.md
content/docs/user-guide/pipelines/index.md
content/docs/user-guide/project-structure/dvcyaml-files.md
content/docs/user-guide/project-structure/internal-files.md
content/docs/user-guide/related-technologies.md
content/docs/user-guide/what-is-dvc.md

Closes #3945
See for example link to "Avoiding unexpected behavior" at the end of https://dvc-org-guide-pipelines-6zpmjd.herokuapp.com/doc/user-guide/project-structure/internal-files (review app).
> Note that no redirect is needed because we never published path `/doc/user-guide/data-pipelines`, it was just an internal mistake in https://github.com/iterative/dvc.org/pull/3414/files.

guide: hotfix pipelines links

---

content/docs/api-reference/get_url.md
content/docs/api-reference/open.md
content/docs/api-reference/read.md

- Adding hanging indent where matters
- moving end-bracket to a newline (without indent) like how `black` does
- reducing indentations from 8 to 4
- trying to fit some code into a single line (I did not see any reason to hang some of them).

docs: fix code formatting/indentations

---

content/docs/command-reference/plots/index.md
content/docs/user-guide/project-structure/dvcyaml-files.md

Minor updates to address https://github.com/iterative/dvcyaml-schema/pull/16#discussion_r968801509 (and an unrelated change for `dvc plots templates`).
I don't see a good place to mention support for `plots outputs` dir support specifically. Since it's a subset of both `top-level plots` and `outputs`, both of which support dirs, I don't know if an explicit mention is needed, but open to suggestions.

plots: mention dir support and update templates

---

content/docs/command-reference/push.md
content/docs/user-guide/how-to/resolve-merge-conflicts.md

Core PR: https://github.com/iterative/dvc/pull/8360
The core PR adds merge driver support for changing or deleting files.
In review app: https://dvc-org-merge-driver-k01urtosm.herokuapp.com/doc/user-guide/how-to/resolve-merge-conflicts#directories

guide: merge driver can handle non-append conflicts

---

content/docs/dvclive/api-reference/live/index.md
content/docs/dvclive/api-reference/live/log_param.md
content/docs/dvclive/api-reference/live/log_params.md
content/docs/dvclive/dvclive-with-dvc.md
content/docs/dvclive/get-started.md
content/docs/dvclive/ml-frameworks/catalyst.md
content/docs/dvclive/ml-frameworks/fastai.md
content/docs/dvclive/ml-frameworks/huggingface.md
content/docs/dvclive/ml-frameworks/keras.md
content/docs/dvclive/ml-frameworks/lightgbm.md
content/docs/dvclive/ml-frameworks/pytorch-lightning.md
content/docs/dvclive/ml-frameworks/xgboost.md
content/docs/sidebar.json

documentation for `log_param`/`log_params` (https://github.com/iterative/dvclive/pull/292)

dvclive: docs for log_param/log_params

---

content/docs/user-guide/project-structure/dvcyaml-files.md

The format under https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#metrics-and-plots-outputs is currently all broken due to an open `<admon>` tag:

hotfix: dvc.yaml spec format

---

content/docs/command-reference/remote/modify.md

Per https://github.com/iterative/dvc/pull/8143

ssh: Document `password` and `passphrase` decoupling.

---

content/docs/command-reference/config.md

Adds missing `parsing` bullet to https://dvc.org/doc/command-reference/config#configuration-sections.

ref: add config.parsing section link

---

content/docs/api-reference/dvcfilesystem.md

I have proposed the `read_text`/`read_bytes` and their write counterparts' API in [fsspec][1]. If/when that gets merged, and we update DVC, we can start suggesting this API for reading text/binary contents from the file.
Till then, this should not be merged.
[1]: https://github.com/fsspec/filesystem_spec/pull/1047

docs: dvcfs: use read_bytes/read_text instead of cat_file

---

content/docs/start/data-management/data-and-model-access.md
content/docs/start/data-management/data-pipelines.md
content/docs/start/data-management/data-versioning.md
content/docs/start/data-management/metrics-parameters-plots.md
content/docs/start/experiment-management/experiments.md
content/docs/user-guide/how-to/stop-tracking-data.md
content/docs/user-guide/pipelines/defining-pipelines.md

so that they don't show up in the right ✋🏼 CONTENT sidebar; E.g.:
> Current https://dvc.org/doc/start/data-management/data-versioning

fix: H2->3 in <details> sections

---

content/docs/studio/troubleshooting.md
content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md
content/docs/studio/user-guide/projects-and-experiments/run-experiments.md

Closes https://github.com/iterative/studio/issues/4362
This Studio feature is already deployed in prod. So this PR can be merged as soon as it is approved.

Studio: [skip studio] functionality

---

package.json
src/server.js
yarn.lock

Similar to https://github.com/iterative/iterative.ai/pull/704 for `dvc.org`.
https://securityheaders.com/?q=https%3A%2F%2Fdvc-org-security-header-jrpdcu.herokuapp.com%2F&followRedirects=on

Add missing Security Headers

---

content/docs/user-guide/overview.md

The existing wording suggested that copy-on-write is safe because other copies get updated on write.
In fact it's the opposite: unlike symlinks, where an edit would also change the original, copy-on-write is a safe means of deduplicating content because you can write to the copy without changing the original.
The new wording clarifies this.

Fix wording of copy-on-write notes for git-annex

---

content/docs/sidebar.json
content/docs/studio/how-it-works.md
content/docs/studio/index.md
content/docs/studio/troubleshooting.md
content/docs/studio/user-guide/model-registry/add-a-model.md
content/docs/studio/user-guide/model-registry/assign-stage.md
content/docs/studio/user-guide/model-registry/register-version.md
content/docs/studio/user-guide/model-registry/view-models.md
content/docs/studio/user-guide/model-registry/what-is-a-model-registry.md
content/docs/studio/user-guide/prepare-your-repositories.md
content/docs/use-cases/model-registry.md

Reverts iterative/dvc.org#4131
per https://github.com/iterative/dvc.org/pull/4131#issuecomment-1331650296

Remove GTO docs from sidebar & update existing links (mainly Studio)

---

package.json
yarn.lock

- update gatsby-theme-iterative to fix SEO default population
Before:
After:

Fix SEO default population

---

content/docs/command-reference/metrics/index.md

misspelling  `ACU` to `AUC`

---

content/docs/studio/user-guide/projects-and-experiments/visualize-and-compare.md

Related to https://github.com/iterative/studio/issues/4369
@tapadipti I decided not to add lots of text about the feature as it is already described in DVC in details. The idea is to mention that it is supported by Studio and give a link to the description.

docs/studio: top-level plots

---

package.json
src/gatsby/models/github/index.js
yarn.lock

This fixes the stars issue we ran into with lapsing GH PATs + the new granular tokens. We switched to GraphQL on GitHub's recommendation, but the new granular tokens don't work with GraphQL, so back to REST it is.

Use GitHub REST API and new version of server

---

content/docs/user-guide/experiment-management/sharing-experiments.md

Show some options for how to share experiments without a DVC remote.

dvc/guide: share exps without dvc remote

---

content/docs/user-guide/project-structure/dvcyaml-files.md

dvc guide: detail plots spec for x and y

---

.github/workflows/update.yaml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands

test: replace set-output => GITHUB_OUTPUT

---

gatsby-node.js

I wanted to update the theme to the latest version in order to fix tooltip issue (https://github.com/iterative/gatsby-theme-iterative/pull/155). 
It will be covered on https://github.com/iterative/dvc.org/pull/4191 so I went ahead to fix the webpack config issue there.
I believe we want to keep the webpack config that prevents the warnings on the build as it will be hard to debug otherwise if anything happens. I remember I had applied a patch for a single use case https://github.com/iterative/dvc.org/pull/3988. 
I think this will be a better patch.

Fix webpack config

---

src/@dvcorg/gatsby-theme-iterative/components/Documentation/Layout/SearchForm/index.tsx

- Shadowed the Docssearch search form to use updated Algolia keys for DVC. 
- We want to do it in better way (https://github.com/iterative/gatsby-theme-iterative/issues/27)

Fix algolia keys for docs search

---

content/docs/command-reference/import-url.md
content/docs/command-reference/remote/modify.md
content/docs/command-reference/update.md
content/docs/sidebar.json
content/docs/user-guide/data-management/cloud-versioning.md

ref: document cloud versioned remotes

---

content/docs/command-reference/queue/kill.md

fix: #4182
related to https://github.com/iterative/dvc/pull/8657
Thank you for the contribution - we'll try …

Add `--force` and change the default doc to `dvc queue kill`

---

content/docs/contributing/docs.md

The current instruction on the supported Node.js versions needs to be more accurate. 
Running `yarn` with Node.js version `16.18.1` raises the following error:
```
$ yarn
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error @dvcorg/gatsby-theme-iterative@0.3.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.18.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Running the same command with Node.js version `18.x` succeeds.

docs/contributing: Clarify supported Node.js version

---

content/docs/command-reference/remote/modify.md

- remote modify: remove duplicated config options for s3
- remote modify: add timeout config options for http remote
Related: 
- iterative/dvc#8722
- iterative/dvc-http#29

ref: add `read_timeout` and `connect_timeout` config options (`remote add`)

---

src/components/Community/Learn/index.tsx

It's not showing the blog without the comments URL.

Show blog without comments url in blog feed

---

content/docs/sidebar.json
content/docs/user-guide/pipelines/run-cache.md

Follow up to discussion in https://github.com/iterative/dvc.org/pull/4220#discussion_r1080636192. I dropped the run cache description in the experiments guide, but here I'm adding it back as a separate page in the pipelines guide. It's short, but I'm not sure that's a bad thing. It's probably the most important feature of pipelines, so it seems reasonable to have its own page.

guide: add run cache page to pipelines

---

content/docs/studio/get-started.md
content/docs/studio/how-it-works.md
content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md
content/docs/studio/user-guide/projects-and-experiments/visualize-and-compare.md

Closes https://github.com/iterative/studio/issues/4941
Update Studio docs to include live metrics for local experiments. Most of the changes are in this file: `content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md`

Studio: Document live metrics for local experiments

---

content/docs/command-reference/remote/modify.md

@skshetry I added the additional option for using custom auth header with webdav remote to the documentation. …

include custom auth header for webdav

---

content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md

Make STUDIO_REPO_URL mandatory in CI job as per [this discussion](https://iterativeai.slack.com/archives/C03Q04KL6LQ/p1675429041743359?thread_ts=1675422386.926439&cid=C03Q04KL6LQ)

Studio: Live metrics - make STUDIO_REPO_URL mandatory in CI job

---

content/docs/dvclive/api-reference/index.md
content/docs/dvclive/api-reference/live/end.md
content/docs/dvclive/api-reference/live/index.md
content/docs/dvclive/api-reference/live/make_dvcyaml.md
content/docs/dvclive/api-reference/live/make_report.md
content/docs/dvclive/api-reference/live/make_summary.md
content/docs/dvclive/api-reference/live/next_step.md
content/docs/dvclive/how-it-works.md
content/docs/sidebar.json

Context:
We are working to quickly do a DVCLive 2.0 release, primarily to smooth the onboarding experience for existing DVC users. Onboarding worked well for new users but was being ignored in existing DVC projects. This was a conscious choice to avoid being overly intrusive for users who didn’t need the onboarding, but users find it unexpected and want to still get the benefits (like auto config of metrics/plots/params).
~I'm missing how to make `Live.make_dvcyaml()` appear as a hyperlink.~ Edit: resolved

dvclive: 2.0 docs (adds make_dvcyaml)

---

content/docs/command-reference/remote/modify.md

Minor fix of the parameters location:
https://user-images.githubusercontent.com/3659196/216786093-7f29b82a-9c2b-463b-a4c3-b7af3215ad74.mov

Fix cloud versioning params location

---

content/docs/command-reference/remote/modify.md
content/docs/command-reference/update.md
content/docs/user-guide/data-management/cloud-versioning.md

Drops worktree remotes.
~Still need to remove remote-specific info from https://dvc.org/doc/command-reference/remote/modify#available-parameters-per-storage-type, but this info is currently being moved in #4264 and related PRs, so not sure how best to proceed.~
Edit: I also removed it from the ref for `remote modify` now, so let's merge whenever it's ready and resolve any merge conflicts as needed.

drop worktree remotes

---

config/link-check/excluded-links.yml
content/docs/command-reference/data/status.md
content/docs/user-guide/basic-concepts/dvc-project.md

Following up #4302, this PR targets the remaining broken links on dvc.org
This has also revealed that our feature for making `basic-concepts` pages is currently broken, so I'll go to the theme repo to do that next.

Fix more links

---

content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md
content/docs/studio/user-guide/projects-and-experiments/visualize-and-compare.md

Add docs for studio export to CSV.
Depends on https://github.com/iterative/static/pull/17 for images.
It's how it should be after merging the above images.
Closes https://github.com/iterative/studio/issues/5064

Studio: document export to CSV

---

content/docs/start/data-management/data-versioning.md
content/docs/user-guide/data-management/cloud-versioning.md
content/docs/user-guide/how-to/update-tracked-data.md

Updates all docs to reflect cloud versioning. Fixes #4089.

Cloud versioning changes

---

content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md
content/docs/studio/user-guide/projects-and-experiments/run-experiments.md

Studio - Change "Experiment" button back to "Run"

---

content/basic-concepts/experiment.md

Related to #4393 and #4389. Updating the definition shown in the tooltip for DVC experiments should make it easier to grasp throughout the docs.

update definition of experiment

---

content/docs/studio/get-started.md
content/docs/studio/user-guide/account-management.md
content/docs/studio/user-guide/billing-and-payment.md
content/docs/studio/user-guide/change-team-plan-and-size.md
content/docs/studio/user-guide/projects-and-experiments/create-a-project.md
content/docs/studio/user-guide/projects-and-experiments/share-a-project.md
content/docs/studio/user-guide/teams.md

Make the docs consistent with the recent changes in our pricing structure (according to https://github.com/iterative/iterative.ai/issues/803).
I'll also replace the pricing screenshots in the [static repo](https://github.com/iterative/static).

Studio: Remove Teams plan from pricing structure

---

content/docs/start/experiments/building-pipelines.md

Hey @daavoo, as we discussed, I tried a little more in-depth approach to the building-pipelines page. We can take pieces of this without using it completely if any of it is helpful.
It does mention `dvc exp run` in the building pipelines page, which might be a little repetitive with the experiments-iterations page. I'd be fine with:
1. Leaving in the repetition.
2. Dropping the mentions to `exp run` in building-pipelines.
3. Cutting down some of the pipeline-related info in experiments-iterations.
PTAL 🙏

Add pipelines pages to experimens start guide: alternate

---

content/docs/command-reference/exp/push.md

Removing incorrect line from docs
https://github.com/iterative/mlem/issues/616?notification_referrer_id=NT_kwDOAGe5lLI1NjkxMDk3OTc5OjY3OTc3MTY#issuecomment-1467925374

Remove a warning that DVC can only auth with SSH

---

content/docs/sidebar.json
content/docs/user-guide/pipelines/defining-pipelines.md
content/docs/user-guide/pipelines/run-cache.md
content/docs/user-guide/pipelines/running-pipelines.md

This started as a way to address #4431, but it expanded into a page on running pipelines generally.

guide: add running-pipelines page

---

content/docs/user-guide/data-management/remote-storage/ssh.md

remote-storage: document max_sessions for ssh

---

content/docs/start/data-management/metrics-parameters-plots.md

We mention a next page at the end of the data mgmt trail that we have long since removed.

start: drop ref to next page that doesn't exist

---

content/docs/dvclive/live/log_image.md

Docs for the https://github.com/iterative/dvclive/pull/518
--------
Thank you for the contribution - we'll …

Support for `Path` and `str` to an existing image in `dvclive.log_image`

---

content/docs/sidebar.json
content/docs/studio/self-hosting/troubleshooting/support-bundle.md

This PR creates a new page in the Studio Self-hosting section about creating a support bundle that contains Studio's application logs. This support bundle can be shared with our support engineers for faster resolution of issues.

studio: Add page about creating a support bundle

---

content/docs/command-reference/exp/run.md

Per https://github.com/iterative/dvc/pull/9302

exp run: Add `--copy-paths`.

---

content/docs/command-reference/exp/push.md
content/docs/studio/user-guide/projects-and-experiments/live-metrics-and-plots.md
content/docs/user-guide/project-structure/configuration.md

Related #4440.
I did not add any visuals for `exp push` as I did not see if it fit into command reference. Maybe that should be accommodated in the guide or tutorials.

sharing exp: document studio.token

---

content/docs/studio/self-hosting/installation/index.md

This PR describes the system requirements for the AMI and Helm variants on the Installation page in Studio's self-hosting section.

studio: Add section with system requirements

---

content/docs/sidebar.json
content/docs/start/data-management/index.md
content/docs/start/experiments/index.md
content/docs/start/index.md
redirects-list.json

Get Started - Condensing landing page

---

content/docs/command-reference/params/index.md

The warning refers to an earlier code snippet where ruamel.yaml was in fact used. With introduction of params_show (https://github.com/iterative/dvc.org/commit/a43701b372f9f3edb34ae6d10de12f3a513094ca), this remark/warning does not make sense anymore.

remove deprecated warning about ruamel.yaml

---

content/docs/user-guide/how-to/run-dvc-on-windows.md

To enable long paths it might be needed to set a registry key. This is not covered by the currently linked guide, so linked to an additional guide. In some (my) case there was no group policy regarding long paths until after I set the registry key. Add dvc repro as possible trigger and add expected error code.
Please …

Add long path guide to run-dvc-on-windows.md

---

content/docs/command-reference/queue/remove.md

Old language made it sound like `dvc exp remove` only removes queue entries, but `dvc queue remove` removes the queue entries
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when …

clarifying language for dvc queue remove docs

---

content/docs/dvclive/ml-frameworks/pytorch-lightning.md

Adds examples of logging artifacts and hyperparameters

dvclive: add examples to lightning

---

content/docs/dvclive/how-it-works.md
content/docs/dvclive/live/log_metric.md
content/docs/dvclive/ml-frameworks/catalyst.md
content/docs/dvclive/ml-frameworks/fastai.md
content/docs/dvclive/ml-frameworks/huggingface.md
content/docs/dvclive/ml-frameworks/keras.md
content/docs/dvclive/ml-frameworks/lightgbm.md
content/docs/dvclive/ml-frameworks/pytorch-lightning.md
content/docs/dvclive/ml-frameworks/xgboost.md

Docs for https://github.com/iterative/dvclive/pull/584
Closes #4568 
I separated into two commits:
1. Basic docs update
2. Changed summary metric examples to use this
WDYT about 2? I think it's a more consistent API to suggest `live.log_metric("metric", val, plot=False)` over `live.summary["metric"] = val`. I left the summary dict in `live.make_summary()` so that it's still valid and can be found by people who want to use it (maybe they need to add an entire dict of metrics at once).

dvclive: log_metric(plot=False)

---

content/docs/command-reference/exp/list.md
content/docs/command-reference/exp/pull.md
content/docs/command-reference/exp/push.md
content/docs/user-guide/experiment-management/cleaning-experiments.md
content/docs/user-guide/experiment-management/comparing-experiments.md

See https://github.com/iterative/dvc/pull/9501

Update output format of dvc exp list

---

content/docs/command-reference/repro.md

Added Example: Only pull pipeline data as needed.

repro: Updated `--pull` and added `--allow-missing`.

---

content/docs/command-reference/add.md

Closes https://github.com/iterative/dvc.org/issues/4532.
I tried to incorporate all the things that `dvc add` is now capable of. `git` talks about index in `git add`, but the mechanics in dvc is more complex and we don't have a thing called `index` (at least not yet). So I centered the explanation around `.dvc` files.
These days, we are considering `.dvc` file as implementation detail as we also have `dvc.yaml` and `dvc.lock` files. I am not sure if it's a good idea in general, but it helped on leaning to `.dvc` file for supporting explanation in `dvc add`.
The explanation does feel a bit verbose (if it was not already before), and may not be fluid.

doc: document virtual operation in add

---

src/components/DownloadButton/index.tsx

With osxpkg building fixed and 3.0 package already available, we can now re-enable osx download button on dvc.org.

download: re-enable osx pkg

---

content/docs/user-guide/experiment-management/sharing-experiments.md

Updates to experiments sharing guide now that it is close to feature complete. Tried to cover it as one holistic end-to-end workflow, including:
* Trying to explain use cases for live metrics vs exp refs vs persistent commits and when and why you might want each
* Emphasize where Studio fits and how it helps
* Include features that aren't strictly sharing but are part of the overall workflow (finding shared experiments, persisting, cleaning)
* Deemphasize explaining all the different options in the CLI

guide: update exp sharing guide

---

content/docs/dvclive/how-it-works.md
content/docs/dvclive/live/log_artifact.md
content/docs/dvclive/ml-frameworks/pytorch.md

dvclive: update log_artifact options

---

content/docs/command-reference/repro.md

Closes #4692. 
`--keep-going`/`--ignore-errors` were introduced in https://github.com/iterative/dvc/pull/9712, and will be in the next release.

cmd-ref: document `--keep-going|--ignore-errors` in repro

---

content/docs/studio/self-hosting/configuration/ca.md

- Clarify use case for custom CAs
- Update configuration format to reflect the Helm chart (`customCaCert` (string) -> `customCaCerts` (list))

Update instructions for Studio Self-hosted CAs

---

content/docs/studio/troubleshooting.md

This will make it easier for users to find the ways to contact us.

Studio docs: Move Support to top of Troubleshooting page

---

content/docs/contributing/core.md

Formatting is broken on main.
`main` glows green, while PR CI was broken and is broken for new PRs https://github.com/iterative/dvc.org/pull/4727

docs: contrib: fix formatting

---

content/docs/api-reference/dvcfilesystem.md

I'm proposing that we document `DVCFileSystem(subrepos=True)` since we have had multiple requests about it:
* https://iterativeai.slack.com/archives/C03JS2V4MQU/p1691146482782569
* https://iterativeai.slack.com/archives/C03JS2V4MQU/p1689953511647149
* https://discuss.dvc.org/t/dvc-initialized-subdir-invisible-when-using-dvc-api-to-accecss-data-in-a-remote-github-repo/1711/2

dvcfs subrepos example

---

content/docs/studio/get-started.md

Completes 4th task in https://github.com/iterative/studio/issues/5426

Studio: Include project table with live plots in get-started page

---

content/docs/studio/user-guide/projects-and-experiments/visualize-and-compare.md
content/docs/studio/user-guide/team-collaboration/teams.md

Some screenshots of Studio have been updated in [a related PR](https://github.com/iterative/static/commit/e05dd3735bd427dc29ea931cbd54c2384b0b8af1).
This PR makes one small restructuring to better accommodate the plots gif (which replaces the old plots png), and makes a correction in the number of pages in a team dashboard.

Studio: Update text to match screenshot updates

---

content/docs/studio/user-guide/team-collaboration/change-team-plan-and-size.md

Moved one sentence around coz it explains what to do after the screenshot appeared, not before.

Studio minor change: Move one sentence around

---

content/docs/dvclive/live/log_image.md

https://github.com/iterative/dvclive/releases/tag/2.14.0

dvclive: Document support for `matplotlib` in `Live.log_image`

---

content/docs/user-guide/pipelines/running-pipelines.md

Recommend `repro --dry` over `exp run --dry` in the user guide and otherwise clean up `exp run` vs `repro` in the pipeline guide. `exp run --dry` may be unnecessarily expensive (like cloning import repos) and have unwanted side effects (see https://github.com/iterative/dvc/issues/9817).

guide: use repro for dry

---

content/docs/dvclive/ml-frameworks/pytorch-lightning.md

Update per https://github.com/iterative/dvclive/pull/659

dvclive: copy best lightning checkpoint

---

content/docs/dvclive/live/log_image.md

Minor fix to `log_image` example

dvclive: fix log_image example

---

content/docs/user-guide/project-structure/configuration.md

Based on research triggered by the support:
https://discuss.dvc.org/t/unexpected-changed-outs-on-status-and-link-type-reflink-is-not-available-on-pull/1739/3
Seems that we have the default value set to `0o444` for files and `0o2775` for dirs.

fix(config): update file mode in group shared cache

---

content/docs/studio/user-guide/projects-and-experiments/explore-ml-experiments.md

I had missed it in [this PR](https://github.com/iterative/dvc.org/pull/4812).

Minor fix to remove https://dvc.org from a link to a docs page

---

content/docs/start/data-management/metrics-parameters-plots.md

Updates to https://dvc.org/doc/start/data-management/metrics-parameters-plots to mirror the repo changes in https://github.com/iterative/example-repos-dev/pull/247.

start: drop extra eval step

---

src/components/Support/index.tsx
src/components/Support/styles.module.css

I noticed that for most support emails requesting help to debug DVC commands, our first response is to ask for output of running the commands with the `--verbose` (`-v`) flag. So I think it will be helpful to guide the users to include this output in their email.

Ask to include output of running the dvc command with --verbose flag

---

content/docs/user-guide/pipelines/run-cache.md

Fixes an `<abbr>` that was not closed, which caused the rest of the paragraph not to appear in the documentation.

Fix Run Cache in Pipelines documentation

---

content/docs/start/data-management/metrics-parameters-plots.md

Update docs per https://github.com/iterative/example-repos-dev/pull/251
Next steps:
- Need to drop badge in the README of the repo (if we keep metrics in cache we can't use badges anymore :( )
- Need to fetch and cache metrics automatically. With the current setup repo is slow and is not working w/o pull fetch - which is also hard to do for multiple revisions or experiments (commands do not accept revisions) cc @skshetry

feat(get-started): cache the whole eval directory

---

redirects-list.json

This is a change I forgot to add to https://github.com/iterative/dvc.org/pull/4852.

Fix a re-direct related to the docs re-org merged earlier today

---

content/docs/start/data-management/metrics-parameters-plots.md

Minor edits to simplify and clarify how to configure dvclive plots.

start: reword dvclive plots config

---

content/docs/studio/user-guide/experiments/configure-a-project.md
content/docs/studio/user-guide/experiments/create-a-project.md

Earlier, we had a separate section called `Scenarios where project settings are required`. This more-or-less duplicated what was already presented in the following section: `Configuring project settings`. Now, I've merged these into one. They don't need a separate section heading now, because of which the individual settings are at header level 2 (not 3). This has allowed me to create a `Commits and columns` header and include `Start date/time` and `Columns` within it - similar to how it is in Studio.
I also made some small changes to the create-a-project doc, coz it was based on an earlier version of the create project flow, where settings like data remotes were presented during the create project flow.

Write about start date/time setting, and related content adjustment

---

content/docs/gto/command-reference/assign.md
content/docs/gto/command-reference/deprecate.md
content/docs/gto/command-reference/register.md

Per https://github.com/iterative/gto/pull/417
Updates the `--push` CLI option in `gto register` and similar commands to reflect the current state of the commands.

fix(gto): update push option descriptions

---

content/basic-concepts/pipeline.md
content/docs/dvclive/how-it-works.md
content/docs/dvclive/index.md
content/docs/dvclive/live/index.md
content/docs/dvclive/live/log_artifact.md
content/docs/dvclive/live/log_param.md
content/docs/dvclive/live/log_params.md
content/docs/start/experiments/experiment-pipelines.md

I think this is enough to close https://github.com/iterative/dvclive/issues/648 and for now seems to me like a better solution than any kind of auto-conversion of dvclive-only workflows to pipelines. The experience is still not completely smooth, but the goal for this PR is to build on https://github.com/iterative/dvc.org/pull/4795 and explain the potential friction points and how to solve them.

Dvclive pipeline transition

---

content/docs/command-reference/exp/rename.md

Fix exp rename typo

---

content/docs/studio/user-guide/team-collaboration/index.md
content/docs/studio/user-guide/troubleshooting.md

Counterpart of https://github.com/iterative/studio/pull/7828

Studio: Rename 'force import' to 're-import'

---

content/docs/start/data-management/metrics-parameters-plots.md

Paths were from an old version of the example repo. Related to https://github.com/iterative/dvc.org/issues/4901.

start: fix metrics diff paths

---

content/docs/command-reference/exp/save.md

`exp save`: use -m for --message short option

---

content/docs/user-guide/experiment-management/visualizing-plots.md

* updates `/doc/user-guide/experiment-management/visualizing-plots#defining-plots` with a section for the VSCode Extension's Plot Wizard
Fixes #4885

Add Plot Wizard inside "Visualizing Plots" User Guide

---

content/docs/user-guide/upgrade.md

Adds a couple changes to the upgrade guide:
1. Mentions backwards compatibility only extends back to 2.0 (see https://github.com/iterative/dvc/issues/9878).
2. Mentions how to handle dvc remote migration (see https://github.com/iterative/dvc/issues/9924).

Upgrade guide edits

---

content/docs/dvclive/ml-frameworks/xgboost.md

Fixes: https://github.com/iterative/dvclive/issues/721
The XGBoost docs have a dangling `param` variable that isn't defined anywhere. Since this is where you define your metric, and this is an important part of experimentation, I added an example of how to use it to set a metric via the `eval_metric` param.

fix: add metric example to xgboost docs

---

content/docs/api-reference/get_url.md
content/docs/studio/rest-api.md
content/docs/user-guide/upgrade.md

Closes #4729. Other links mentioned there work for me.

fix broken links

---

content/docs/dvclive/ml-frameworks/pytorch.md

Adds instructions for setting rank 0, which is needed when using [pytorch ddp](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) for distributed training (such as multiple gpus). Tested on slurm cluster that this works (and the lightning callback works out of the box).

instructions for pytorch ddp

---

content/docs/command-reference/install.md
content/docs/command-reference/push.md
content/docs/user-guide/data-management/cloud-versioning.md

Clarifies that `dvc push` needs to happen before `git commit` when using version-aware remotes

push behavior with version-aware remotes

---

content/docs/command-reference/exp/show.md
content/docs/user-guide/experiment-management/comparing-experiments.md

* As discussed in planning, adds a mention of sorting in the vscode extension to the docs
In `/doc/command-reference/exp/show`
~https://github.com/iterative/dvc.org/assets/43496356/94663389-820d-485e-9982-c07ed3c6f7f8~
In `/doc/user-guide/experiment-management`:

Add DVC for VS Code Extension sorting demo 

---

content/docs/install/linux.md
content/docs/install/macos.md
content/docs/install/windows.md

https://github.com/iterative/dvc/releases does not have any packages now.

doc: install: remove github releases mention

---

content/docs/command-reference/exp/list.md
content/docs/command-reference/exp/remove.md
content/docs/command-reference/move.md
content/docs/command-reference/remove.md
content/linked-terms.js

Add aliases for common commands

---

content/docs/start/data-management/data-pipelines.md
content/docs/start/data-management/data-versioning.md

Adds some info about how to manage external data in the get started guide so that we address use cases where `dvc add` doesn't make sense.

start: address external data

---

content/docs/dvclive/how-it-works.md
content/docs/dvclive/live/log_metric.md
content/docs/dvclive/live/log_param.md
content/docs/dvclive/live/log_params.md

Adds `timestamp` param description to the `dvclive.log_metric` call. Plus a bit of cleanup around.
------------
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the …

fix(dvclive): add timestamp param to log metrics

---

content/docs/studio/user-guide/model-registry/use-models.md

This edits the `Use models` page (https://dvc.org/doc/studio/user-guide/model-registry/use-models) to link to `dvc artifacts get`'s command documentation page, rather than the `dvc get` one. Further down the doc we do still refer to `dvc get`, but as an alternative if you don't have access to Studio:
> ... Without these prerequisites, you can still [download a model artifact with DVC](http://localhost:8000/doc/command-reference/artifacts/get). ...
☝️ which does correctly link to the `dvc get` command doc page.

Change 'dvc get' to 'artifacts get'

---

content/docs/command-reference/plots/templates.md

`plots`: standardise across DVC/Studio/VS Code

---

content/docs/user-guide/project-structure/dvcyaml-files.md

Reflects changes to be able to show non-model artifacts in the registry

guide: mention non-model artifacts

---

content/docs/use-cases/data-registry/tutorial.md
content/docs/use-cases/model-registry.md
content/docs/user-guide/data-management/discovering-and-accessing-data.md

Adds info about how to use the studio model registry for non-model artifacts. 
Closes #5027 and #5077. 
TODO: Add Studio gifs/screenshots. Depends on https://github.com/iterative/dataset-registry/pull/43.

registry: add info for non-models

---

content/docs/dvclive/live/next_step.md

Fix a small typo in the example code block in the `dvclive/live` page.

Fix typo in dvclive/live codeblock

---

content/docs/user-guide/experiment-management/visualizing-plots.md

Adds video on plots debugging to `/doc/user-guide/experiment-management/visualizing-plots?tab=VSCode-Extension#visualizing-plots`
~https://github.com/iterative/dvc.org/assets/43496356/7180c824-c003-46ef-bfb0-1cbf41b20c78~
Fixes #5057

Mention VSCode Plot Debugging in docs

---

src/components/Home/Alert/index.tsx
src/components/Home/Hero/HeroTitleSection.tsx
src/components/Home/index.tsx
tailwind.config.js

- adds a banner to the hero section
- If we move forward with this, it closes https://github.com/iterative/dvc.org/issues/5113
Preview: 
This attracts complete attention to the section. Since we are really looking forward to the event, and this will be there only for a few days, it might be worth it.
Here is also a subtile version; let me know if we prefer that:

feat: add banner to hero section

---

src/server.js

- Fix the video added on https://github.com/iterative/dvc.org/pull/5121 was not showing up in https://dvc.org/doc/studio/user-guide/experiments/explore-ml-experiments
- It was due to CSP policy. Added https://static.iterative.ai to allowed list.

fix: video missing in docs

---

content/docs/studio/user-guide/experiments/live-metrics-and-plots.md
content/docs/user-guide/integrations/databricks.md
content/docs/user-guide/integrations/sagemaker.md

Docs for https://github.com/iterative/dvclive/pull/646. That PR is for DVCLive, but it's really about logging to Studio from platforms where code is not run inside a Git repo.
The docs PR covers:
- Live updates in Studio when working outside a Git repo
- Live updates in SageMaker jobs
- Live updates in Databricks Repos

Send live updates outside a git repo

---

content/docs/user-guide/env.md

Closes #4914. @mnrozhkov is using some of these like `DVC_EXP_NAME` in an upcoming blog post, and it seems good to have all of these documented anyway (except for few that look to either have unclear behavior or are intended to be private).

add more env vars

---

content/docs/studio/user-guide/experiments/live-metrics-and-plots.md
content/docs/user-guide/env.md
content/docs/user-guide/integrations/databricks.md
content/docs/user-guide/integrations/sagemaker.md
content/docs/user-guide/project-structure/configuration.md

Docs PR for #10345. This drops `DVC_STUDIO_REPO_URL` and instead uses `DVC_EXP_GIT_REMOTE` to set the URL for both live updates in Studio and pushing the final exp ref to the Git remote.

use exp git remote to set studio repo url

---

content/docs/command-reference/exp/push.md
content/docs/command-reference/install.md
content/docs/command-reference/push.md
content/docs/user-guide/data-management/cloud-versioning.md
content/docs/user-guide/data-management/remote-storage/amazon-s3.md
content/docs/user-guide/data-management/remote-storage/azure-blob-storage.md
content/docs/user-guide/data-management/remote-storage/google-cloud-storage.md
content/docs/user-guide/pipelines/external-dependencies-and-outputs.md

This PR would soft deprecate version-aware remotes. DVC can still support version-aware imports and recognize cloud versioning - this is only about pushing to version-aware dvc remotes. 
Reasons for this:
- Workflow discrepancies - we have warnings scattered throughout the docs and multiple open issues about operations that aren't supported with version-aware remotes. These aren't just due to lack of prioritization - there's often no obvious way to support them. Users also often get confused with differences like having to push to the dvc remote before committing to git.
- Performance - it seems to often scan the bucket and perform much worse than cache-like remotes
- Maintenance burden - too much work to support it, often encounter bugs
@shcheklein WDYT?

drop cloud versioned remotes

---

content/docs/studio/self-hosting/configuration/git-forges/github.md

* https://github.com/iterative/helm-charts/pull/70 ([current naming convention](https://github.com/iterative/helm-charts/blob/1340959594feb240c268e55e56a8b13836e3cd60/charts/studio/values.yaml#L129-L150))

Fix `scmProviders.github` naming conventions

---

content/docs/user-guide/data-management/large-dataset-optimization.md

Looks the admonition tags need a line break before the next paragraph for inline code to be properly recognized (see [here on the _Upgrading to DVC 3.0_ page](https://github.com/iterative/dvc.org/blob/dadb739a68e7ea354ab8e659f4bb5ac9207eff4b/content/docs/user-guide/upgrade.md?plain=1#L41)).

fix inline code syntax in callout

---

content/docs/start/data-pipelines/metrics-parameters-plots.md

Depends on https://github.com/iterative/example-repos-dev/pull/282. Corrects issues with how plots are configured in the docs by fixing the dvc.yaml and explaining `Live(dvcyaml=False)`.

start: correct plots configuration

---

content/docs/use-cases/data-registry/tutorial.md

fix: module import in example hitting ModuleNotFoundError
Going through the tutorial, and this specific example is hitting an error
```
ModuleNotFoundError: No module named 'dvc.api.open'
```
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-p …

fix: tutorial.md example import reaches an error

---

content/docs/user-guide/integrations/databricks.md

Databricks repos are now Databricks Git folders, but functionally it doesn't change anything with the DVC integration (still no way to access the repo itself AFAICT). See https://docs.databricks.com/en/repos/index.html

databricks repos -> databricks git folders

---

package.json
src/gatsby/hooks/stars.ts
src/gatsby/models/github/index.js
yarn.lock

- The main cause of the issue seems to be deep down related to `Sentry` not supporting way to parse headers with core `nodejs` causing server crash which caused the outage.
- Current issue should be fixed after the upgrade: https://github.com/getsentry/sentry-javascript/pull/10938
- `logs` looks fine
- Enabled Always online for `dvc.org`
- Used this opportunity to refactor error handling

fix: revert code, upgrade server

---

content/docs/studio/self-hosting/configuration/git-forges/github.md
content/docs/studio/self-hosting/configuration/git-forges/gitlab.md

Our examples were outdated, and made confusion to our client.
In GitLab I fixed the indentation.

feat(scm): Update SCM settings examples

---

content/docs/studio/user-guide/openid-connect.md

After https://studio.iterative.ai became https://studio.dvc.ai, authentication was failing on e.g. AWS:
```
InvalidIdentityTokenException:
An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithWebIdentity operation: No OpenIDConnect provider found in your account for https://studio.dvc.ai/api
```

Update OpenID Connect documentation for studio.dvc.ai

---

content/data/datachain.yml
src/components/Home/Alert/index.tsx
src/components/Home/Hero/BetterTogether/index.tsx
src/components/Home/Hero/GetStarted/GetStartedWithDatachain.tsx
src/components/Home/Hero/HeroSection.tsx
src/gatsby/hooks/stars.ts
src/utils/externalUrls.ts
src/utils/urls.ts

feat: datachain release banner and updates

---

content/data/datachain.yml
src/components/Home/Hero/BetterTogether/index.tsx
src/components/Home/Hero/HeroSection.tsx

Updates one of the DataChain code examples on the home page, and fixes a couple of uses of 'DataChain' that were not capitalized correctly.

Update 'Create datasets from query' example and capitalization of DataChain

---

content/docs/command-reference/import-db.md
content/docs/command-reference/update.md
content/docs/user-guide/project-structure/dvc-files.md

Merge when https://github.com/iterative/dvc/pull/10510 gets released.
Closes #5087. …

stabilize import db

---

content/docs/user-guide/data-management/remote-storage/google-drive.md

More context is here https://github.com/iterative/dvc/issues/10516

add warn to Google drive page about app is blocked

---

content/docs/command-reference/checkout.md

Adds `--allow-missing` option to `dvc checkout`.

docs(checkout): add allow missing arg

---

content/docs/command-reference/list.md

- https://github.com/iterative/dvc/pull/10573
- https://github.com/iterative/dvc/pull/10598

cmd reference: document new ls options

---

content/docs/command-reference/exp/remove.md

Fix #5325 : added --keep flag to dvc exp remove documentation as needed by the corresponding PR in the code : https://github.com/iterative/dvc/pull/10633

Fix #5325 : added --keep flag to dvc exp remove documentation

---

content/docs/install/linux.md

The script that we have is a huge security risk. We were adding our key unconditionally to be trusted by apt for any package from any repo.
Instead, we should create a `.list` file for the repository to tell apt where to find the key for that specific repo, which is what this PR does.
As recommended in https://manpages.ubuntu.com/manpages/jammy/en/man8/apt-key.8.html#deprecation.
Also, see https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key.
Also related: https://github.com/iterative/dvc.org/pull/3683.

install(ubuntu): place key in /etc/apt/keyrings

---

content/docs/command-reference/pull.md
content/docs/command-reference/push.md
content/docs/command-reference/remote/default.md
content/docs/command-reference/remote/index.md
content/docs/command-reference/remote/list.md

Update the documentation/usage of `dvc remote list` command to reference that the default remote is indicated in the output.
This relates to [issue 10708 in dvc](https://github.com/iterative/dvc/issues/10708) and the [ongoing PR for the fix in dvc]( https://github.com/iterative/dvc/pull/10711) 
Documentation updates to show the changes made there and hopefully make it clear to any end user what the asterisk means.

docs: show default remote in dvc remote list

---

content/docs/dvclive/ml-frameworks/scikit-learn.md

This PR fixes a typo in the documentation by correcting the import statement from `DVCLive` to `dvclive`.

fix: correct import from `DVCLive` to `dvclive`

---

content/docs/dvclive/ml-frameworks/xgboost.md

Previously, the "Using `live` to pass an existing `Live` instance"
code example was missing the `Live` instance being
passed into the `DVCLiveCallback`.
This PR properly includes the `Live` instance.

docs(dvclive/xgboost): corrects code example

---

content/docs/user-guide/project-structure/configuration.md

a quick and simple fix for a SHH typo that's meant to be SSH.

fixed SHH -> SSH typo
